'use strict';
/* ============ SALTY ISLE · balloon: the drop balloon rebuilt as a flying-fish festival balloon with an 8 m walkable deck; the player strolls the deck (WASD) and jumps from anywhere, bots ride along as passengers until they jump ============ */
const DECK = { half: 3.5, y: .3, slots: [] };
(() => { if (typeof SKIN === 'undefined' || !SKIN.on) return;
  const C = { coral: 0xff5a4e, cream: 0xfff6e6, teal: 0x2fa6a0, sun: 0xffd23f, navy: 0x2e3a59, wood: 0xa8754a, wood2: 0x8a5f3c, wick: 0xc99a4a, steel: 0x9aa7b0 };
  let src = null;
  planeModel = function () {
    if (!src) { const s = new Sk('sun'), O = t => ({ ..._islO, tint: t });
      /* envelope: fourteen lathe gores in festival stripes, a teardrop that narrows into the skirt */
      const prof = [[4.4, 9.4], [8.6, 11.8], [12.6, 16.5], [14.8, 22.5], [15.1, 27], [14.2, 32.5], [11.8, 37.5], [7.6, 41.4], [3, 43.3], [.01, 43.7]].map(p => new THREE.Vector2(p[0], p[1])), G2 = [C.coral, C.cream, C.teal, C.cream, C.sun, C.cream, C.coral, C.cream, C.teal, C.cream, C.sun, C.cream, C.coral, C.cream];
      G2.forEach((c, i) => s.add(new THREE.LatheGeometry(prof, 4, i / 14 * 6.2832, 6.2832 / 14), new THREE.Matrix4(), O(c)));
      s.add(new THREE.TorusGeometry(15.15, .18, 6, 56).rotateX(Math.PI / 2), new THREE.Matrix4().makeTranslation(0, 24.6, 0), O(C.navy)); s.add(new THREE.TorusGeometry(4.45, .16, 6, 28).rotateX(Math.PI / 2), new THREE.Matrix4().makeTranslation(0, 9.45, 0), O(C.navy));
      /* bunting round the belly */
      for (let i = 0; i < 32; i++) { const a0 = i / 32 * 6.2832, a1 = (i + .7) / 32 * 6.2832, am = (a0 + a1) / 2, r = 15.25, y = 24.4, c = [C.coral, C.sun, C.teal, C.cream][i % 4]; s.tri([Math.cos(a0) * r, y, Math.sin(a0) * r], [Math.cos(a1) * r, y, Math.sin(a1) * r], [Math.cos(am) * (r + .1), y - 1.5, Math.sin(am) * (r + .1)], 0, c); }
      /* the flying-fish face on the front (-z), a dorsal fin on top and a tail fin at the back */
      for (const q of [-1, 1]) { const ex = q * 5, ey = 27.5, ez = -13.9; islBall(s, 2.4, 2.6, .9, ex, ey, ez, 0xfffdf7, 14); islBall(s, 1.1, 1.3, .5, ex + q * .25, ey - .2, ez - .7, 0x1a1a22, 12); islBall(s, .35, .35, .2, ex + q * .55, ey + .5, ez - 1.05, 0xffffff, 8); islBall(s, 1.2, .5, .3, q * 7.6, 23.2, -12.6, 0xff8fb0, 8); }
      s.add(new THREE.TorusGeometry(3.4, .45, 8, 24, Math.PI), new THREE.Matrix4().compose(new V3(0, 22.4, -14.6), new THREE.Quaternion().setFromEuler(new THREE.Euler(-.25, 0, Math.PI)), new V3(1, .8, 1)), O(C.coral));
      for (let i = 0; i < 4; i++) { const z0 = -4 + i * 2.6; s.tri([0, 42.6 - i * .4, z0], [0, 42.6 - i * .5, z0 + 2.6], [0, 46.5 - i * .5, z0 + 1.6], 0, C.coral); s.tri([0, 42.6 - i * .4, z0], [0, 46.5 - i * .5, z0 + 1.6], [0, 42.6 - i * .5, z0 + 2.6], 0, C.coral); }
      for (const q of [-1, 1]) { const A = [0, 28, 14.6], B = [q * 4.5, 33, 19.5], D = [q * 4.5, 23, 19.5]; s.tri(A, B, D, 0, C.teal); s.tri(A, D, B, 0, C.teal); }
      /* skirt and burner */
      s.add(new THREE.CylinderGeometry(4.4, 2.3, 5.6, 16, 1, true), new THREE.Matrix4().makeTranslation(0, 6.6, 0), O(C.coral)); for (let i = 0; i < 16; i++) { const a = i / 16 * 6.2832; s.tri([Math.cos(a) * 2.3, 3.8, Math.sin(a) * 2.3], [Math.cos(a + .39) * 2.3, 3.8, Math.sin(a + .39) * 2.3], [Math.cos(a + .2) * 2.35, 3.2, Math.sin(a + .2) * 2.35], 0, i % 2 ? C.cream : C.sun); }
      for (const [x, z] of [[-1, -1], [1, -1], [-1, 1], [1, 1]]) for (const q of [-.12, .12]) islSeg(s, [x * 2.6 + q, DECK.y + 1.1, z * 2.6 - q], [x * .3, 3.95, z * .3], .03, .03, 0xc9a46a, 4); islCyl(s, .25, .25, .45, 0, 4.15, 0, 0xc08a3a, 12); islCyl(s, .27, .27, .06, 0, 4.38, 0, 0x8a5f3c, 12); islCyl(s, .27, .27, .06, 0, 3.94, 0, 0x8a5f3c, 12);
      /* ropes from the rail posts to the skirt ring */
      for (let i = 0; i < 8; i++) { const a = i / 8 * 6.2832 + .39, rx = Math.cos(a), rz = Math.sin(a), k = 1 / Math.max(Math.abs(rx), Math.abs(rz)); islSeg(s, [rx * k * 3.9, 1.5, rz * k * 3.9], [rx * 2.3, 3.8, rz * 2.3], .04, .04, 0xe9d6a8, 4); }
      /* deck: planks on beams, wicker hull below, rope rails on posts, a gap-free rim */
      islBox(s, 8, .3, 8, 0, DECK.y / 2, 0, C.wood); for (let i = -3.5; i <= 3.5; i += .5) islBox(s, .03, .012, 7.9, i, DECK.y + .006, 0, C.wood2); s.add(new THREE.CylinderGeometry(5.66, 4.3, 1.8, 4, 1).rotateY(Math.PI / 4), new THREE.Matrix4().makeTranslation(0, -.9, 0), O(C.wick)); for (const y of [-.4, -.9, -1.4]) s.add(new THREE.CylinderGeometry(5.66 - (-y) * .75 + .02, 5.66 - (-y) * .75 + .02, .1, 4, 1, true).rotateY(Math.PI / 4), new THREE.Matrix4().makeTranslation(0, y, 0), O(0x8a6a3a));
      for (let i = -4; i <= 4; i += 1) for (const [x, z] of [[i, -4], [i, 4], [-4, i], [4, i]]) islCyl(s, .06, .07, 1.1, x, DECK.y + .55, z, C.wood2, 6); for (const [a, b] of [[[-4, -4], [4, -4]], [[4, -4], [4, 4]], [[4, 4], [-4, 4]], [[-4, 4], [-4, -4]]]) { islSeg(s, [a[0], DECK.y + 1.1, a[1]], [b[0], DECK.y + 1.1, b[1]], .07, .07, C.wood, 6); islSeg(s, [a[0], DECK.y + .6, a[1]], [b[0], DECK.y + .6, b[1]], .03, .03, 0xe9d6a8, 4); }
      /* props near the rails: lifebuoys, crates, a barrel, lanterns, a flagpole with a fish flag, sandbags hanging outside */
      for (const [x, z, ry] of [[0, -4.05, 0], [0, 4.05, 0], [-4.05, 0, Math.PI / 2], [4.05, 0, Math.PI / 2]]) { const g = new THREE.TorusGeometry(.42, .12, 8, 16); g.rotateY(ry); s.add(g, new THREE.Matrix4().makeTranslation(x, DECK.y + .7, z), O(C.coral)); for (let i = 0; i < 4; i++) { const a = i * Math.PI / 2 + .3, g2 = new THREE.TorusGeometry(.42, .125, 8, 3, .45); g2.rotateZ(a); g2.rotateY(ry); s.add(g2, new THREE.Matrix4().makeTranslation(x, DECK.y + .7, z), O(C.cream)); } }
      islBox(s, .8, .7, .8, -3.2, DECK.y + .35, -3.2, C.wood2); islBox(s, .6, .5, .6, -3.2, DECK.y + .95, -3.15, C.wood); islCyl(s, .35, .35, .9, 3.25, DECK.y + .45, 3.2, C.teal, 12); islCyl(s, .36, .36, .06, 3.25, DECK.y + .7, 3.2, C.navy, 12);
      for (const [x, z] of [[-4, -4], [4, -4], [-4, 4], [4, 4]]) { islCyl(s, .05, .05, .9, x, DECK.y + 1.55, z, C.navy, 6); islBall(s, .2, .26, .2, x, DECK.y + 2.1, z, C.sun, 8); }
      islCyl(s, .06, .07, 4.2, 3.6, DECK.y + 2.1, -3.6, C.wood2, 6); s.tri([3.6, DECK.y + 4.1, -3.6], [3.6, DECK.y + 3.3, -3.6], [5.2, DECK.y + 3.7, -3.6], 0, C.coral); s.tri([3.6, DECK.y + 4.1, -3.6], [5.2, DECK.y + 3.7, -3.6], [3.6, DECK.y + 3.3, -3.6], 0, C.coral);
      for (const [x, z] of [[-4.2, -2], [-4.2, 2], [4.2, -2], [4.2, 2], [-2, 4.2], [2, -4.2]]) { islSeg(s, [x, DECK.y + 1.1, z], [x, DECK.y + .3, z], .015, .015, 0xe9d6a8, 3); islBall(s, .2, .28, .2, x, DECK.y + .1, z, 0xd9c08a, 7); }
      src = s.bake(fillMat({ objSpace: true, fog: .0025 }), null); }
    const g = new THREE.Group(), m = new THREE.Mesh(src.fill.geometry, src.fill.material); g.add(m);
    const fl = new THREE.Mesh(new THREE.ConeGeometry(.42, 1.6, 10), new THREE.MeshBasicMaterial({ color: 0xffb020, transparent: true, opacity: .9 })), fi = new THREE.Mesh(new THREE.ConeGeometry(.22, 1.0, 8), new THREE.MeshBasicMaterial({ color: 0xfff1a8 })); fl.scale.setScalar(.5); fi.scale.setScalar(.5); fl.position.set(0, 4.85, 0); fi.position.set(0, 4.75, 0); fl.material.color.set(0xffb347); g.add(fl, fi); g.flame = [fl, fi];
    g.traverse(o => { o.frustumCulled = false; }); return g; };
  /* deck slots for passengers: a loose grid that keeps the burner frame and the props clear */
  for (let a = -3.1; a <= 3.11; a += .9) for (const [x, z, ry] of [[a, -3.35, Math.PI], [a, 3.35, 0], [-3.35, a, -Math.PI / 2], [3.35, a, Math.PI / 2]]) { if ((x < -2.6 && z < -2.6) || (x > 2.6 && z > 2.6)) continue; DECK.slots.push([x, z, ry, 1]); } for (const [x, z] of [[-2, -1.9], [2, -1.9], [-2, 1.9], [2, 1.9], [0, -2.2], [0, 2.2]]) DECK.slots.push([x, z, Math.random() * 6.28, 0]);
  const toWorld = (x, z, out) => { const M = PLANE.model; M.updateMatrixWorld(); return out.set(x, DECK.y, z).applyMatrix4(M.matrixWorld); }, _w = new V3();
  const _pu = planeUpdate; planeUpdate = function (dt) { if (PLANE.on && PLANE.model) PLANE.model.rotation.y = PLANE.yaw; _pu(dt); if (!PLANE.on || !PLANE.model) return; const M = PLANE.model, t = G.now; if (M.flame) { const k = .8 + Math.sin(t * 23) * .12 + Math.sin(t * 37) * .08; M.flame[0].scale.set(1, k, 1); M.flame[1].scale.set(1, k * .9, 1); }
    let n = 0; for (const b of G.bots) { if (b.air !== 'plane' || !b.model) continue; const idx = n++; if (idx >= DECK.slots.length) { b.model.root.visible = false; continue; } const sl = DECK.slots[idx]; if (!b.deck) b.deck = { x: sl[0], z: sl[1], yaw: sl[2], rail: sl[3], wave: Math.random() < .3 }; toWorld(b.deck.x, b.deck.z, b.pos); b.yaw = b.deck.yaw + M.rotation.y; const m = b.model; if (Math.hypot(b.pos.x - camera.position.x, b.pos.z - camera.position.z, b.pos.y + 1.4 - camera.position.y) < 3) { m.root.visible = false; continue; } m.root.visible = true; m.gun.visible = false; m.lastP = { x: b.pos.x, z: b.pos.z, yaw: b.yaw }; b.onGround = true; b.air = null; animSoldier(b, dt); b.air = 'plane'; m.gun.visible = false; if (m.armR.elbow) { if (b.deck.wave) { const w = Math.sin(t * 6 + idx) * .12; islArmIK(m.armR, .32 + w, 1.0, -.05, 1, -.2, .3); } else if (b.deck.rail) { islArmIK(m.armR, .22, .3, -.42, .8, -.5, .2); islArmIK(m.armL, -.22, .3, -.42, -.8, -.5, .2); } } } };
  const _jo = jumpOut; jumpOut = function (e, forced) { if (e.air !== 'plane') return; const dk = e.deck || (e.isPlayer ? e.deck : null); const p = dk && PLANE.model ? toWorld(dk.x, dk.z, new V3()) : null; _jo(e, forced); if (p) { e.pos.set(p.x, p.y - .2, p.z); } e.deck = null; };
  window.deckPlayer = function (pl, dt, k) { const M = PLANE.model; if (!M) return false; if (!pl.deck) pl.deck = { x: 0, z: 2.6 }; const f = (k.KeyW ? 1 : 0) - (k.KeyS ? 1 : 0), sd = (k.KeyD ? 1 : 0) - (k.KeyA ? 1 : 0), ry = M.rotation.y, ly = pl.yaw - ry, wx = -Math.sin(ly) * f + Math.cos(ly) * sd, wz = -Math.cos(ly) * f - Math.sin(ly) * sd, wl = Math.hypot(wx, wz), sp = (k.ShiftLeft ? 4.6 : 2.6) * dt;
    const ox = pl.deck.x, oz = pl.deck.z; if (wl > 0) { pl.deck.x += wx / wl * sp; pl.deck.z += wz / wl * sp; } const H = DECK.half; pl.deck.x = Math.max(-H, Math.min(H, pl.deck.x)); pl.deck.z = Math.max(-H, Math.min(H, pl.deck.z)); if (Math.abs(pl.deck.x) < 1.45 && Math.abs(pl.deck.z) < 1.45) { if (Math.abs(pl.deck.x) > Math.abs(pl.deck.z)) pl.deck.x = Math.sign(pl.deck.x || 1) * 1.45; else pl.deck.z = Math.sign(pl.deck.z || 1) * 1.45; }
    const prev = toWorld(ox, oz, new V3()); toWorld(pl.deck.x, pl.deck.z, pl.pos); const m = pl.model; m.lastP = { x: pl.pos.x - (pl.pos.x - prev.x), z: pl.pos.z - (pl.pos.z - prev.z), yaw: pl.yaw }; { const c = Math.cos(ry), s2 = Math.sin(ry), dx = pl.deck.x - ox, dz = pl.deck.z - oz; m.lastP.x = pl.pos.x - (dx * c + dz * s2); m.lastP.z = pl.pos.z - (-dx * s2 + dz * c); }
    pl.onGround = true; pl.vel.set(0, 0, 0); const air = pl.air; pl.air = null; animSoldier(pl, dt); pl.air = air; m.root.visible = true; return true; };
})();
