'use strict';
/* ============ INK ISLAND · brain: the bots remember you between matches — where you land, where you sit each ring, how you fight — and grow sharper the more you win ============ */
const BRAIN = { key: 'inkisland_brain', data: null, cur: null, lastKills: 0, sampleT: 0, lastPos: null, ph: -1 };
const brainBlank = () => ({ v: 2, matches: 0, wins: 0, kills: 0, deaths: 0, shots: 0, hits: 0, land: {}, killTown: {}, ph: {}, still: 0, stillN: 0, kdist: 0, kdistN: 0, indoorK: 0 });
function brainLoad() { try { BRAIN.data = JSON.parse(localStorage.getItem(BRAIN.key)); } catch (e) { BRAIN.data = null; } if (!BRAIN.data || BRAIN.data.v !== 2) BRAIN.data = brainBlank(); else BRAIN.data = Object.assign(brainBlank(), BRAIN.data); for (const k in BRAIN.data.ph) if (!Array.isArray(BRAIN.data.ph[k][0])) BRAIN.data.ph[k] = [BRAIN.data.ph[k]]; brainDerive(); }
function brainSave() { try { localStorage.setItem(BRAIN.key, JSON.stringify(BRAIN.data)); } catch (e) { } }
function brainReset() { BRAIN.data = brainBlank(); brainSave(); brainDerive(); brainMenu(); }
/* what the record says about you: a 0–1 skill (K/D, accuracy, wins — only trusted after a few matches), a sniper flag, a camper flag, the town you land in most */
function brainDerive() { const d = BRAIN.data, m = d.matches || 0, kd = d.kills / Math.max(1, d.deaths), acc = d.shots > 20 ? d.hits / d.shots : .2, wr = d.wins / Math.max(1, m);
  d.skill = clamp((Math.min(1, kd / 6) * .5 + Math.min(1, acc / .45) * .25 + Math.min(1, wr * 2) * .25) * Math.min(1, m / 4), 0, 1); if (!isFinite(d.skill)) d.skill = 0; const s = d.skill * [1, .8, .6][G.diff || 0]; d.sniper = d.kdistN > 3 && d.kdist / d.kdistN > 55; d.camper = d.stillN > 12 && d.still / d.stillN > .55;
  let best = null; for (const k in d.land) if (k !== 'wild' && (!best || d.land[k] > d.land[best])) best = k; d.favTown = best; d.hunters = best && m >= 1 ? Math.min(5, 1 + Math.floor(m * .6)) : 0;
  d.skillD = s; G.brainMul = { react: 1 - .45 * s, err: 1 - .4 * s, see: 1 + .3 * s }; G.brainSniper = d.sniper; G.brainCamper = d.camper; }
const brainTownName = id => { const t = TOWNS.find(t => t.id === id); return t ? t.name : '野外'; };
function brainMenu() { const card = $('brainCard'), d = BRAIN.data; if (!card || !d) return; const h = (d.hist || []).filter(r => !r.quit), last = h[h.length - 1], wins = h.filter(r => r.win).length, kv = (k, v, tip) => `<div class="kv"${tip ? ` title="${tip}"` : ''}><b>${k}</b><span class="v">${v}</span></div>`;
  const ll = $('lastLine'); if (ll) ll.innerHTML = last ? `上局 <b>第 ${last.rank} 名</b> · 击杀 ${last.kills}${wins ? ` · 吃鸡 ×${wins}` : ''} · 共 ${h.length} 局` : '第一次？落地先找枪，白圈是下一圈，蓝圈外会掉血。';
  if (!d.matches) { card.innerHTML = '<h4>对手档案</h4><div>还没人认识你：打完一局，Bot 就会记住你的落点、路线和打法，下一局针对你。</div>'; return; }
  card.innerHTML = '<h4>对手档案</h4>' + kv('记忆', `${d.matches} 局`) + kv('锐度', `${Math.round(d.skill * 100)}%`, '对手按你的战绩变强：反应更快、散布更小、看得更远') + (d.favTown ? kv('常落', `${brainTownName(d.favTown)} · ${d.hunters} 名猎手会跟跳`) : '') + (d.sniper || d.camper ? kv('被看穿', [d.sniper && '爱远狙', d.camper && '爱蹲守'].filter(Boolean).join(' / ')) : '') + '<button id="brainReset">忘掉我</button>'; const b = $('brainReset'); if (b) b.onclick = () => { brainReset(); SFX.ui(); }; }
/* the match in progress: shots and hits, landing town, where you were when each ring was announced, how still you stand, how far your kills were */
function brainMatchStart() { BRAIN.cur = { shots: 0, hits: 0, land: null, ph: {}, still: 0, stillN: 0, kdist: 0, kdistN: 0, indoorK: 0, kills: 0 }; BRAIN.lastKills = 0; BRAIN.sampleT = 0; BRAIN.lastPos = null; BRAIN.ph = -1; }
function brainTick(dt) { const c = BRAIN.cur, pl = G.player; if (!c || !pl || G.state !== 'live') return;
  if (pl.alive && !pl.air && !c.land) { const t = MAP.townAt(pl.pos.x, pl.pos.z); c.land = t ? t.id : 'wild'; }
  if (ZONE.on && ZONE.ph !== BRAIN.ph && pl.alive && !pl.air) { BRAIN.ph = ZONE.ph; c.ph[ZONE.ph] = [pl.pos.x, pl.pos.z]; }
  BRAIN.sampleT += dt; if (BRAIN.sampleT > 6) { BRAIN.sampleT = 0; if (pl.alive && !pl.air && !pl.veh && ZONE.on) { if (BRAIN.lastPos) { c.stillN++; if (Math.hypot(pl.pos.x - BRAIN.lastPos.x, pl.pos.z - BRAIN.lastPos.z) < 5) c.still++; } BRAIN.lastPos = { x: pl.pos.x, z: pl.pos.z }; } }
  while (BRAIN.lastKills < G.killLog.length) { const k = G.killLog[BRAIN.lastKills++]; if (k[2] !== pl.name) continue; c.kills++; const v = G.ents.find(e => e.name === k[3]); if (v) { c.kdist += Math.hypot(v.pos.x - pl.pos.x, v.pos.z - pl.pos.z); c.kdistN++; } if (isIndoor(pl)) c.indoorK++; const t = MAP.townAt(pl.pos.x, pl.pos.z); if (t) BRAIN.cur.killTown = t.id; } }
function brainMatchEnd(win) { const c = BRAIN.cur, d = BRAIN.data; if (!c) return; BRAIN.cur = null; d.matches++; if (win) d.wins++; d.kills += c.kills; if (!G.player.alive) d.deaths++; d.shots += c.shots; d.hits += c.hits; if (c.land) d.land[c.land] = (d.land[c.land] || 0) + 1;
  for (const ph in c.ph) { const o = Array.isArray(d.ph[ph]) && Array.isArray(d.ph[ph][0]) ? d.ph[ph] : []; o.push(c.ph[ph]); d.ph[ph] = o.slice(-3); } d.still += c.still; d.stillN += c.stillN; d.kdist += c.kdist; d.kdistN += c.kdistN; d.indoorK += c.indoorK; brainDerive(); (d.hist = d.hist || []).push({ rank: win ? 1 : (G.rank || G.ents.filter(e => e.alive).length + 1), kills: c.kills, shots: c.shots, hits: c.hits, skill: +d.skill.toFixed(2), win: !!win, quit: !win && G.player.alive && G.state !== 'end', t: Date.now() }); d.hist = d.hist.slice(-20); brainSave(); brainMenu();
  const notes = []; if (c.land && c.land !== 'wild') notes.push(`记住了你落在 ${brainTownName(c.land)}`); else if (c.land) notes.push('记住了你落在野外'); if (d.favTown && d.hunters) notes.push(`下局 ${d.hunters} 名猎手会跟你跳 ${brainTownName(d.favTown)}`); if (d.skill > .25) notes.push(`反应 ×${G.brainMul.react.toFixed(2)} · 散布 ×${G.brainMul.err.toFixed(2)}`); if (d.sniper) notes.push('远狙被盯上了：Bot 会拉开后不停横移'); if (d.camper) notes.push('蹲守被盯上了：Bot 会守住你常待的位置'); return notes; }
/* where you usually are when this ring is called — bots camping for the ring pick spots that see that place */
function brainCampBonus(b, q) { const d = BRAIN.data, ps = d && d.ph[ZONE.ph]; if (!ps || !ps.length || !G.player.alive) return 0; const y = MAP.floorAt(q.x, q.z) + 1.6; for (const p of ps) { const dist = Math.hypot(q.x - p[0], q.z - p[1]); if (dist < 18 || dist > 70) continue; if (segClear(q.x, y, q.z, p[0], MAP.floorAt(p[0], p[1]) + 1.2, p[1])) return (b.hunter ? 26 : 9) * Math.min(1, d.matches / 3) * (d.camper ? 1.6 : 1); } return 0; }
/* hooks: wrap the game's own functions after they are defined — count shots and hits, mark hunters at drop time, add the learning line to the end panel */
(() => { const _fire = playerFire, _hurt = hurt, _fb = fireBullet, _sb = stepBullet, _drop = botPlanDrop, _start = startMatch, _end = endMatch, _hud = updateHUD;
  playerFire = function (pl, w, a) { if (BRAIN.cur) { BRAIN.cur.shots++; BRAIN.shotN = (BRAIN.shotN || 0) + 1; } return _fire(pl, w, a); };
  hurt = function (e, dmg, by, wkey, part, dir, pt) { if (BRAIN.cur && by && by.isPlayer && e !== by && e.alive && wkey && !WEAPONS[wkey].nade && !WEAPONS[wkey].melee && BRAIN.bullet && BRAIN.bullet.shotN && BRAIN.bullet.shotN !== BRAIN.hitN) { BRAIN.cur.hits++; BRAIN.hitN = BRAIN.bullet.shotN; } return _hurt(e, dmg, by, wkey, part, dir, pt); };
  fireBullet = function (sh, ox, oy, oz, dx, dy, dz, w, mx, my, mz, noTracer) { const n0 = BULLETS.length; _fb(sh, ox, oy, oz, dx, dy, dz, w, mx, my, mz, noTracer); if (sh && sh.isPlayer) for (let i = n0; i < BULLETS.length; i++) BULLETS[i].shotN = BRAIN.shotN; };
  stepBullet = function (b, dt) { BRAIN.bullet = b; const r = _sb(b, dt); BRAIN.bullet = null; return r; };
  botPlanDrop = function (b, i, n) { _drop(b, i, n); const d = BRAIN.data; b.hunter = false; if (d && d.favTown && d.favTown !== 'wild' && i < d.hunters) { const t = TOWNS.find(t => t.id === d.favTown); if (t) { const a = rand(6.2832), r = Math.sqrt(Math.random()) * t.r * .7, c = navSnap(t.x + Math.cos(a) * r, t.z + Math.sin(a) * r), p = navPos(c); b.drop = { x: p.x, z: p.z, town: t }; b.hunter = true; b.name = '猎手' + b.name.replace(/^猎手/, ''); } } };
  startMatch = function () { if (BRAIN.cur) brainMatchEnd(false); _start(); brainDerive(); brainMatchStart(); };   // leaving a match early still counts as a loss
  endMatch = function (win) { _end(win); const notes = brainMatchEnd(win); if (notes && notes.length) $('endStats').innerHTML += `<p class="brainNote">${notes.join(' · ')}</p>`; };
  updateHUD = function (dt) { brainTick(dt); return _hud(dt); };
  const q = $('quit'); if (q) q.addEventListener('click', () => { if (BRAIN.cur) brainMatchEnd(false); });
})();

/* ---------- in-match smarts: flank the last sighting instead of walking straight at it; get behind something before bandaging; a sharper record hears your shots further ---------- */
/* the last sighting was upstairs: nothing on the ground grid reaches it, so take the stair (bottom → top → exit → the spot) and sweep the room */
function botClearUpstairs(b) { const L = b.lastSeen, T = MAP.floorAtY(L.x, L.z, L.y), F0 = MAP.floorOf(b), now = G.now; if ((!T && !F0) || (!F0 && Math.hypot(L.x - b.pos.x, L.z - b.pos.z) > 60)) return null;
  if (T && F0 === T) { b.forcePath = [{ x: L.x, z: L.z, y: T.y }]; b.intent = '清房'; return { x: L.x, z: L.z }; }
  const chain = []; if (T) { chain.push(T); for (let u; (u = MAP.floorAtY(chain[chain.length - 1].bottom.x, chain[chain.length - 1].bottom.z, chain[chain.length - 1].bottom.y)) && chain.length < 6; ) chain.push(u); }
  const k = F0 ? chain.indexOf(F0) : -1;
  if (F0 && k < 0) { b.forcePath = [{ x: F0.exit.x, z: F0.exit.z, y: F0.y }, { x: F0.top.x, z: F0.top.z, y: F0.y }, { x: F0.bottom.x, z: F0.bottom.z, y: F0.bottom.y }]; b.stairT = now + 12; b.intent = '下楼再追'; return { x: F0.bottom.x, z: F0.bottom.z }; }
  const F = k >= 0 ? chain[k - 1] : chain[chain.length - 1], above = chain[chain.indexOf(F) - 1], end = above ? { x: above.bottom.x, z: above.bottom.z, y: above.bottom.y } : { x: L.x, z: L.z, y: F.y };
  if (Math.hypot(F.bottom.x - b.pos.x, F.bottom.z - b.pos.z) < 2.8 && Math.abs(b.pos.y - F.bottom.y) < .7) { b.forcePath = [{ x: F.top.x, z: F.top.z, y: F.y }, { x: F.exit.x, z: F.exit.z, y: F.y }, end]; b.stairT = now + 12; b.intent = '上楼清房'; return { x: end.x, z: end.z }; }
  if (!F0 && !MAP.reach[navSnap(F.bottom.x, F.bottom.z)]) return null; if (F0) b.forcePath = [{ x: F.bottom.x, z: F.bottom.z, y: F0.y }]; b.intent = '去楼梯口'; b.stairGoal = { x: F.bottom.x, z: F.bottom.z, y: F.bottom.y, t: now }; return { x: F.bottom.x, z: F.bottom.z }; }
function botFlank(b) { const up = botClearUpstairs(b); if (up) return up; if (MAP.floorOf(b)) return null; const d = BRAIN.data; if (!d || (!b.flankNext && Math.random() > .3 + .5 * (d.skillD || 0))) return null; b.flankNext = false; const L = b.lastSeen, dx = L.x - b.pos.x, dz = L.z - b.pos.z, dist = Math.hypot(dx, dz); if (dist < 8 || dist > 60) return null; const side = Math.random() < .5 ? 1 : -1, off = rand(8, 14), c = navSnap(L.x - dz / dist * side * off, L.z + dx / dist * side * off); if (!MAP.reach[c]) return null; const p = navPos(c); b.intent = '侧翼包抄'; return { x: p.x, z: p.z }; }
function brainCover(b, now) { if (b.air || (ZONE.on && (outsideZone(b) || (ZONE.stage === 'shrink' && !insideWhite(b.pos.x, b.pos.z, 10)))) || b.hp >= 55 || b.heal || b.targetVis || now - b.lastSeenT > 8 || !(b.meds.kit || b.meds.band || b.meds.medkit)) { b.coverPt = null; return null; }
  if (b.coverPt && now < b.coverT) { if (Math.hypot(b.coverPt.x - b.pos.x, b.coverPt.z - b.pos.z) < 2.2) { b.coverPt = null; b.coverT = now + 4; b.flankNext = true; return null; } b.quick = true; b.intent = '撤到掩体'; return b.coverPt; } if (now < (b.coverT || 0)) return null;
  const L = b.lastSeen, ly = MAP.floorAt(L.x, L.z) + 1.4; if (!segClear(L.x, ly, L.z, b.pos.x, b.pos.y + eyeY(b), b.pos.z)) return null;
  let best = null, bs = 1e9; for (let i = 0; i < 12; i++) { const a = rand(6.2832), r = rand(4, 12), c = navSnap(b.pos.x + Math.cos(a) * r, b.pos.z + Math.sin(a) * r); if (!MAP.reach[c]) continue; const p = navPos(c); if (segClear(L.x, ly, L.z, p.x, MAP.fh[c] + 1.4, p.z)) continue; if (r < bs) { bs = r; best = p; } }
  if (!best) { b.coverT = now + 3; return null; } b.coverPt = { x: best.x, z: best.z }; b.coverT = now + 6; b.quick = true; b.intent = '撤到掩体'; return b.coverPt; }
(() => { const _core = botObjectiveCore, _hear = botHear;
  botObjectiveCore = function (b, now) { const c = brainCover(b, now); if (c) { b.lootTarget = null; return c; } return _core(b, now); };
  botHear = function (pos, team, radius, kind) { if (G.player && team === G.player.team && BRAIN.data) radius *= 1 + .35 * (BRAIN.data.skillD || 0); return _hear(pos, team, radius, kind); };
})();

/* ---------- converge: a shot of yours that several bots hear sends them in from different sides instead of all up the same street ---------- */
function brainConverge(b, now) { const c = b.converge; if (!c) return null; if (now - c.t > 14 || !G.player.alive || b.targetVis || !(b.inv[1] || b.inv[2]) || (ZONE.on && (outsideZone(b) || (ZONE.stage === 'shrink' && !insideWhite(b.pos.x, b.pos.z, 10))))) { b.converge = null; return null; }
  if (!c.goal) { const dx = c.x - b.pos.x, dz = c.z - b.pos.z, d = Math.hypot(dx, dz) || 1, off = Math.min(14, d * .5), cell = navSnap(c.x - dz / d * c.side * off - dx / d * 6, c.z + dx / d * c.side * off - dz / d * 6); if (!MAP.reach[cell] || (ZONE.on && !insideWhite(navPos(cell).x, navPos(cell).z, 4))) { b.converge = null; return null; } c.goal = navPos(cell); }
  if (Math.hypot(c.goal.x - b.pos.x, c.goal.z - b.pos.z) < 3) { b.converge = null; b.lastSeen.set(c.x, MAP.floorAt(c.x, c.z), c.z); b.lastSeenT = now; b.state = 'hunt'; return null; }
  b.quick = true; b.intent = '合围枪声'; const r = routeToward(b.pos.x, b.pos.z, c.goal.x, c.goal.z, 30); return r ? { x: r.x, z: r.z } : { x: c.goal.x, z: c.goal.z }; }
(() => { const _core2 = botObjectiveCore, _hear2 = botHear;
  botObjectiveCore = function (b, now) { const g = brainConverge(b, now); if (g) { b.lootTarget = null; return g; } return _core2(b, now); };
  botHear = function (pos, team, radius, kind) { const r = _hear2(pos, team, radius, kind); const d = BRAIN.data; if ((kind || 'shot') === 'shot' && G.player && team === G.player.team && d && (d.skillD || 0) > .2) { let i = 0; for (const b of G.bots) { if (!b.alive || b.air || b.veh || b.heardT !== G.now || b.target || b.converge || Math.random() > .35 + .5 * d.skillD) continue; b.converge = { x: pos.x, z: pos.z, t: G.now, side: (i++ % 2) ? 1 : -1, goal: null }; b.path = null; b.waitT = 0; } } return r; };
})();

/* ---------- search fire: a target that went prone or wore the suit and vanished gets a few bursts into the grass where it was last seen ---------- */
function brainSearchFire(b, now) { if (!b.alive || b.air || b.veh || b.target || b.act || !b.lastProne || now - (b.lastProneT || -99) > 5 || now - b.lastSeenT < .6 || now < (b.searchT || 0) || now < (b.blindT || 0) || b.reloadT > 0 || b.mag <= 0 || G.state !== 'live') return; const w = WEAPONS[b.weapon]; if (w.melee || w.nade || w.crank) return; const L = b.lastSeen, dx = L.x - b.pos.x, dz = L.z - b.pos.z, d = Math.hypot(dx, dz); if (d < 4 || d > Math.min(45, w.range || 45)) return; const ey = b.pos.y + eyeY(b); if (SMOKES.length && smokeBlocks(b.pos.x, ey, b.pos.z, L.x, L.y + .8, L.z)) return; if (!segClear(b.pos.x, ey, b.pos.z, L.x, L.y + .5, L.z) && !segClear(b.pos.x, ey, b.pos.z, L.x, L.y + 1.1, L.z)) return;
  const want = Math.atan2(-dx, -dz); b.alertYaw = want; b.alertT = now + .4; b.intent = '扫射草丛'; if (Math.abs(angDiff(want, b.yaw)) > .12) return;
  b.searchT = now + Math.max(w.auto ? .14 : .45, w.rate * (w.auto ? 1 : 1.4)); b.searchN = (b.searchN || 0) + 1; if (b.searchN > 9) { b.lastProne = false; b.searchN = 0; return; } const yaw = want + gauss() * .035, pitch = Math.atan2(L.y + .5 - ey, d) + gauss() * .02, cp = Math.cos(pitch); b.pitch = pitch; G.botShoot(b, -Math.sin(yaw) * cp, Math.sin(pitch), -Math.cos(yaw) * cp); b.mag--; }
/* ---------- airdrop stand-off: someone else is near the crate — hold at range and watch it for a while before walking in ---------- */
function brainDropStandoff(b, goal, now) { if (!goal || b.intent !== '去空投') return goal; let drop = null, dd = 140; for (const d of ZONE.drops) { if (d.falling || d.smokeT <= 0 || d.taken) continue; const q = Math.hypot(d.x - b.pos.x, d.z - b.pos.z); if (q < dd) { dd = q; drop = d; } } if (!drop) return goal; const bd = Math.hypot(drop.x - b.pos.x, drop.z - b.pos.z); if (bd < 14 || bd > 45) return goal;
  const rival = G.ents.find(e => e !== b && e.alive && !e.air && e.team !== b.team && Math.hypot(e.pos.x - drop.x, e.pos.z - drop.z) < 35 && ((e.spottedBy && e.spottedBy[b.team] && now - e.spottedBy[b.team].t < 6) || segClear(b.pos.x, b.pos.y + eyeY(b), b.pos.z, e.pos.x, e.pos.y + 1, e.pos.z))); if (!rival) { b.dropWaitT = 0; b.dropWaitDrop = null; return goal; }
  if (b.dropWaitDrop !== drop) { b.dropWaitDrop = drop; b.dropWaitT = now + rand(6, 10); } if (now > b.dropWaitT) return goal; b.quick = false; b.intent = '空投对峙'; return { x: b.pos.x, z: b.pos.z, hold: true, face: { x: drop.x, z: drop.z } }; }
(() => { const _core3 = botObjectiveCore, _tick = botTick;
  botObjectiveCore = function (b, now) { const sg = b.stairGoal; if (sg && b.intent === '去楼梯口' && now - sg.t < 30 && now - b.lastSeenT < 25 && Math.hypot(sg.x - b.pos.x, sg.z - b.pos.z) < 2.8 && Math.abs(b.pos.y - sg.y) < .7) { b.stairGoal = null; const up = botClearUpstairs(b); if (up) { b.lootTarget = null; return up; } } return brainDropStandoff(b, _core3(b, now), now); };
  botTick = function (b, now) { _tick(b, now); brainSearchFire(b, now); };
})();
