'use strict';
/* ============ INK ISLAND · endgame: the last few survivors must be findable. Late rings pull bots in instead of letting them loot far outside; the final four hear each other and come to fight; the compass shows the rough direction of the last three ============ */
const ENDG = { pingT: 0, pings: [], told: false, hearT: 0 };
function endgameOut(e) { return ZONE.on && Math.hypot(e.pos.x - ZONE.white.x, e.pos.z - ZONE.white.z) > ZONE.white.r + 2; }
(() => { const _core = botObjectiveCore, _want = botWantedItem, _hud = updateHUD, _comp = drawCompass, _start = startMatch;
  /* from ring 3 on: a bot outside the white circle walks in (no detours for loot or far vehicles), and nobody loots outside the circle unless it is right at their feet */
  botObjectiveCore = function (b, now) { if (ZONE.on && ZONE.ph >= 2 && !b.air && !b.veh && b.inv && endgameOut(b) && !(typeof inFire === 'function' && inFire(b))) { b.lootTarget = null; b.wantVeh = null; return rotateGoal(b, true); } return _core(b, now); };
  botWantedItem = function (b) { const it = _want(b); if (it && ZONE.on && ZONE.ph >= 3 && !insideWhite(it.x, it.z, 2) && Math.hypot(it.x - b.pos.x, it.z - b.pos.z) > 8) return null; return it; };
  updateHUD = function (dt) { _hud(dt); if (G.state !== 'live') return; { const pl = G.player, sl = G.slip; if (sl && pl.alive && !pl.air) { if (sl.lx !== null) { const d = Math.hypot(pl.pos.x - sl.lx, pl.pos.z - sl.lz); if (d < 20) { if (pl.veh) sl.ride += d; else sl.walk += d; } } sl.lx = pl.pos.x; sl.lz = pl.pos.z; } } if (typeof SKIN !== 'undefined' && SKIN.on && $('help')) $('help').classList.toggle('fade', G.now > 30 && !G.paused); const pl = G.player, foes = G.ents.filter(e => e.alive && e !== pl), now = G.now;
    /* the counter tells how many of the survivors are outside the circle */
    const out = ZONE.on && ZONE.ph >= 2 ? foes.filter(endgameOut).length : 0, lab = $('top').children[0].querySelector('small'); if (lab) lab.textContent = out ? `存活 · ${out} 圈外` : '存活';
    /* final four: every 12 s the survivors hear each other (a fuzzed point), so campers come out */
    if (foes.length + (pl.alive ? 1 : 0) <= 4 && now > ENDG.hearT) { ENDG.hearT = now + 12; const all = G.ents.filter(e => e.alive && !e.air); for (const a of all) { const f = new THREE.Vector3(a.pos.x + rand(-9, 9), a.pos.y, a.pos.z + rand(-9, 9)); botHear(f, a.team, 400, 'shot'); } }
    /* last three enemies: compass pings, refreshed every 15 s, fuzzed by up to 18 m */
    if (pl.alive && foes.length && foes.length <= 3) { if (now > ENDG.pingT) { ENDG.pingT = now + 15; ENDG.pings = foes.map(e => ({ x: e.pos.x + rand(-18, 18), z: e.pos.z + rand(-18, 18), out: endgameOut(e), t: now })); if (!ENDG.told) { ENDG.told = true; banner(`最后 ${foes.length} 人`, '罗盘上的红点是他们的大致方位', 'go'); setTimeout(() => $('banner').classList.remove('on'), 2400); } } } else ENDG.pings = []; };
  { const _take = invTake; invTake = function (e, it) { const r = _take(e, it); if (r && e && e.isPlayer && G.slip) G.slip.picked++; return r; }; }
  drawCompass = function (g, W, pl) { _comp(g, W, pl); if (!ENDG.pings.length) return; const cx = W / 2, y = 64, span = 150, ppd = 2.2, yawDeg = (((-pl.yaw - (pl.fy || 0)) * 180 / Math.PI) % 360 + 360) % 360; g.save();
    const drawn = []; for (const p of ENDG.pings) { const a = Math.min(1, 1.6 - (G.now - p.t) / 10); if (a <= 0) continue; const b = ((Math.atan2(p.x - pl.pos.x, -(p.z - pl.pos.z)) * 180 / Math.PI) % 360 + 360) % 360, x = cx + ((b - yawDeg + 540) % 360 - 180) * ppd, edge = Math.abs(x - cx) > span * ppd / 2, xx = edge ? cx + Math.sign(x - cx) * (span * ppd / 2 - 6) : x;
      const dist = Math.round(Math.hypot(p.x - pl.pos.x, p.z - pl.pos.z) / 10) * 10, near = drawn.find(q => Math.abs(q.x - xx) < 40); if (near) { near.n++; near.d = Math.min(near.d, dist); continue; } drawn.push({ x: xx, n: 1, d: dist, a, out: p.out }); g.strokeStyle = '#2e3a59'; }
    for (const q of drawn) { const xx = q.x; g.globalAlpha = q.a; g.fillStyle = '#ff5a4e'; g.strokeStyle = '#2e3a59'; g.lineWidth = 2; g.beginPath(); g.moveTo(xx, y + 26); g.lineTo(xx - 7, y + 37); g.lineTo(xx + 7, y + 37); g.closePath(); if (q.out && q.n === 1) g.stroke(); else { g.fill(); g.stroke(); } g.font = '900 11px ui-rounded, "Arial Rounded MT Bold", system-ui, sans-serif'; g.textAlign = 'center'; g.fillStyle = '#2e3a59'; g.fillText((q.n > 1 ? '×' + q.n + ' · ' : '') + q.d + ' m', xx, y + 49); }
    g.restore(); };
  startMatch = function () { G.slip = { picked: 0, walk: 0, ride: 0, lx: null, lz: null }; ENDG.pingT = 0; ENDG.pings = []; ENDG.told = false; ENDG.hearT = 0; return _start(); };
})();
