'use strict';
/* ============ INK ISLAND · fxskin: effects in the harbour palette. Ink splashes become dust, confetti and stars; explosions get a white cartoon puff; squid smoke is a soft ink-purple cloud; fire is red-orange with yellow centres ============ */
const FXS = { puffs: [], conf: [0xff5a4e, 0xffd23f, 0xfffdf7, 0x2fa6a0] };
if (typeof gsHookTemplates === 'function') gsHookTemplates();
(() => { if (typeof SKIN === 'undefined' || !SKIN.on) return; const _burst = FX.burst.bind(FX), _decal = FX.decal.bind(FX), _explode = FX.explode.bind(FX), _smoke = smokeSpawn, _frame = frame;
  FX.burst = function (x, y, z, dx, dy, dz, n, color, speed, size, blood) { if (color === INK) { if (size < .03) return _burst(x, y, z, dx, dy, dz, n, 0xe9dba6, speed * .8, size * 1.1, blood); const k = Math.max(1, Math.ceil(n / FXS.conf.length)); for (const c of FXS.conf) _burst(x, y, z, dx, dy, dz, k, c, speed, size * .8, blood); return; } if (color === AMBER) { _burst(x, y, z, dx, dy, dz, Math.ceil(n * .6), 0xffb020, speed, size, blood); return _burst(x, y, z, dx, dy, dz, Math.ceil(n * .4), 0xff5a4e, speed * .8, size * 1.2, blood); } return _burst(x, y, z, dx, dy, dz, n, color, speed, size, blood); };
  FX.decal = function (x, y, z, nx, ny, nz, size, color, grow) { if (FXS.inExp && color === INK) { if (size < 2.5) return; color = 0xb59a7a; } if (color === INK) color = size > 2.5 ? 0x9a8468 : 0x4a4f63; return _decal(x, y, z, nx, ny, nz, size, color, grow); };
  /* explosion: confetti + a white puff that swells and fades in .45 s */
  FX.explode = function (x, y, z) { for (const r of FX.rings || []) { r.material.color.set(0xffffff); r.material.opacity = .6; } FXS.inExp = true; try { _explode(x, y, z); } finally { FXS.inExp = false; } let p = FXS.puffs.find(q => !q.m.visible); if (!p && FXS.puffs.length < 6) { const m = new THREE.Mesh(new THREE.IcosahedronGeometry(1, 1), new THREE.MeshLambertMaterial({ color: 0xffffff, transparent: true, opacity: .9, depthWrite: false })); m.userData.noShadow = true; scene.add(m); p = { m }; FXS.puffs.push(p); } if (p) { p.m.visible = true; p.m.position.set(x, y + 1, z); p.t = 0; p.m.scale.setScalar(.3); } };
  /* squid smoke: same footprint and timing, soft translucent purple, no ink lines */
  const SMK = { geo: new THREE.SphereGeometry(1, 16, 12), mats: [[0x7a68b8, .62], [0x9b8ad0, .45], [0xc2b6e6, .3], [0xd9d0f0, .25]].map(([c, o]) => new THREE.MeshLambertMaterial({ color: c, emissive: new THREE.Color(c).multiplyScalar(.3), transparent: true, opacity: o, depthWrite: false })) };
  smokeSpawn = function (x, y, z) { _smoke(x, y, z); const s = SMOKES[SMOKES.length - 1]; if (!s || !s.g) return; s.g.traverse(o => { if (o.isLineSegments2 || o.isMesh) o.visible = false; }); const puffs = []; for (let i = 0; i < 20; i++) { const a = rand(6.28), r = i < 16 ? Math.sqrt(Math.random()) * 3.1 : rand(3, 3.8), h = rand(.6, 3.3), m = new THREE.Mesh(SMK.geo, SMK.mats[i < 16 ? i % 3 : 3]); m.position.set(Math.cos(a) * r, h, Math.sin(a) * r); m.userData.r0 = (i < 16 ? rand(1.3, 2.2) : rand(.6, 1)) * (1 - h / 9); m.userData.v = rand(.05, .14); m.scale.setScalar(m.userData.r0); m.userData.noShadow = true; m.renderOrder = 2; s.g.add(m); puffs.push(m); } s.puffs = puffs; };
  frame = function (dt) { _frame(dt); for (const s of SMOKES) if (s.puffs) for (const m of s.puffs) { m.position.y += m.userData.v * dt; m.scale.setScalar(m.userData.r0 * (1 + Math.min(.35, s.age * .03))); } for (const p of FXS.puffs) { if (!p.m.visible) continue; p.t += dt; const u = p.t / .45; if (u >= 1) { p.m.visible = false; continue; } p.m.scale.setScalar(.3 + 3.2 * (1 - (1 - u) * (1 - u))); p.m.material.opacity = .9 * (1 - u); p.m.position.y += dt * 1.2; } };
})();
