'use strict';
/* ============ INK ISLAND · fxskin: effects in the harbour palette. Ink splashes become dust, confetti and stars; explosions get a white cartoon puff; squid smoke is a soft ink-purple cloud; fire is red-orange with yellow centres ============ */
const FXS = { puffs: [], conf: [0xff5a4e, 0xffd23f, 0xfffdf7, 0x2fa6a0] };
if (typeof gsHookTemplates === 'function') gsHookTemplates();
(() => { if (typeof SKIN === 'undefined' || !SKIN.on) return; const _burst = FX.burst.bind(FX), _decal = FX.decal.bind(FX), _explode = FX.explode.bind(FX), _smoke = smokeSpawn, _frame = frame;
  FX.burst = function (x, y, z, dx, dy, dz, n, color, speed, size, blood) { if (color === INK) { if (size < .03) return _burst(x, y, z, dx, dy, dz, n, 0xe9dba6, speed * .8, size * 1.1, blood); const k = Math.max(1, Math.ceil(n / FXS.conf.length)); for (const c of FXS.conf) _burst(x, y, z, dx, dy, dz, k, c, speed, size * .8, blood); return; } if (color === AMBER) { _burst(x, y, z, dx, dy, dz, Math.ceil(n * .6), 0xffb020, speed, size, blood); return _burst(x, y, z, dx, dy, dz, Math.ceil(n * .4), 0xff5a4e, speed * .8, size * 1.2, blood); } return _burst(x, y, z, dx, dy, dz, n, color, speed, size, blood); };
  FX.decal = function (x, y, z, nx, ny, nz, size, color, grow) { if (FXS.inExp && color === INK) { if (size < 2.5) return; color = 0xb59a7a; } if (color === INK) color = size > 2.5 ? 0x9a8468 : 0x4a4f63; return _decal(x, y, z, nx, ny, nz, size, color, grow); };
  /* explosion: confetti + a white puff that swells and fades in .45 s */
  FX.explode = function (x, y, z) { for (const r of FX.rings || []) { r.material.color.set(0xffffff); r.material.opacity = .6; } FXS.inExp = true; try { _explode(x, y, z); } finally { FXS.inExp = false; } let p = FXS.puffs.find(q => !q.m.visible); if (!p && FXS.puffs.length < 6) { const m = new THREE.Mesh(new THREE.IcosahedronGeometry(1, 1), new THREE.MeshLambertMaterial({ color: 0xffffff, transparent: true, opacity: .9, depthWrite: false })); m.userData.noShadow = true; scene.add(m); p = { m }; FXS.puffs.push(p); } if (p) { p.m.visible = true; p.m.position.set(x, y + 1, z); p.t = 0; p.m.scale.setScalar(.3); } };
  /* squid smoke: same footprint and timing, soft translucent purple, no ink lines */
  const SMK = { geo: new THREE.SphereGeometry(1, 16, 12), mats: [[0x7a68b8, .62], [0x9b8ad0, .45], [0xc2b6e6, .3], [0xd9d0f0, .25]].map(([c, o]) => new THREE.MeshLambertMaterial({ color: c, emissive: new THREE.Color(c).multiplyScalar(.3), transparent: true, opacity: o, depthWrite: false })) };
  smokeSpawn = function (x, y, z) { _smoke(x, y, z); const s = SMOKES[SMOKES.length - 1]; if (!s || !s.g) return; s.g.traverse(o => { if (o.isLineSegments2 || o.isMesh) o.visible = false; }); const puffs = []; for (let i = 0; i < 20; i++) { const a = rand(6.28), r = i < 16 ? Math.sqrt(Math.random()) * 3.1 : rand(3, 3.8), h = rand(.6, 3.3), m = new THREE.Mesh(SMK.geo, SMK.mats[i < 16 ? i % 3 : 3]); m.position.set(Math.cos(a) * r, h, Math.sin(a) * r); m.userData.r0 = (i < 16 ? rand(1.3, 2.2) : rand(.6, 1)) * (1 - h / 9); m.userData.v = rand(.05, .14); m.scale.setScalar(m.userData.r0); m.userData.noShadow = true; m.renderOrder = 2; s.g.add(m); puffs.push(m); } s.puffs = puffs; };
  const CH = { mesh: null, m: new THREE.Matrix4(), q: new THREE.Quaternion(), v: new THREE.Vector3(), s: new THREE.Vector3() };
  const _sw = setWeather; setWeather = function (k) { _sw(k); const w = WEATHER[k] || WEATHER.clear; G.fogBase = k === 'fog' ? .016 : FOG_D * .25 * w.fog; scene.fog.density = G.fogBase; scene.fog.color.set(k === 'fog' ? 0xd6e6ee : 0xcfe8f2); };
  frame = function (dt) { _frame(dt); if (G.fogBase && typeof camera !== 'undefined' && scene.fog) { const agl = camera.position.y - Math.max(MAP.terrainY(camera.position.x, camera.position.z), MAP.sea), u = Math.min(1, Math.max(0, (agl - 15) / 65)), k = u * u * (3 - 2 * u); scene.fog.density = G.fogBase * (1 - (G.weather === 'fog' ? .85 : .65) * k); } { const tt = performance.now() / 1000; for (const f of SKIN.floats || []) f.position.y = f.userData.y0 + Math.sin(tt * 3.1 + f.position.x) * .03; const sl = SKIN.sleeper; if (sl && typeof camera !== 'undefined') sl.zs.forEach((z, i) => { const u = (tt * .35 + i / 3) % 1; z.position.set(sl.x + u * .35, sl.y + u * .9, sl.z + u * .1); z.scale.setScalar(.5 + u * .8); z.material.opacity = u < .8 ? 1 : (1 - u) / .2; z.quaternion.copy(camera.quaternion); }); } if (MAP.chimneys && MAP.chimneys.length && typeof camera !== 'undefined') { if (!CH.mesh) { CH.mesh = new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1, 1), new THREE.MeshLambertMaterial({ color: 0xf2f2f2, transparent: true, opacity: .5, depthWrite: false }), MAP.chimneys.length * 5); CH.mesh.userData.noShadow = true; CH.mesh.frustumCulled = false; scene.add(CH.mesh); } const t = (G.now || 0) + performance.now() / 1000 * (G.state === 'menu' ? 1 : 0); let k = 0; for (const c of MAP.chimneys) for (let i = 0; i < 5; i++) { const u = ((t / 3.6) + c.ph + i / 5) % 1, fade = u > .6 ? 1 - (u - .6) / .4 : 1, r = (.12 + .5 * u) * fade; CH.v.set(c.x + u * 1.4 + Math.sin(u * 5 + c.ph * 6) * .12, c.y - .05 + u * 2.4, c.z + u * .35); CH.s.set(r, r * .85, r); CH.m.compose(CH.v, CH.q, CH.s); CH.mesh.setMatrixAt(k++, CH.m); } CH.mesh.instanceMatrix.needsUpdate = true; } for (const s of SMOKES) if (s.puffs) for (const m of s.puffs) { m.position.y += m.userData.v * dt; m.scale.setScalar(m.userData.r0 * (1 + Math.min(.35, s.age * .03))); } for (const p of FXS.puffs) { if (!p.m.visible) continue; p.t += dt; const u = p.t / .45; if (u >= 1) { p.m.visible = false; continue; } p.m.scale.setScalar(.3 + 3.2 * (1 - (1 - u) * (1 - u))); p.m.material.opacity = .9 * (1 - u); p.m.position.y += dt * 1.2; } };
})();
/* d17 sea life (skin only, visual only): three gull flocks circling off the coast and three little fishing boats bobbing further out */
(() => { if (typeof SKIN === 'undefined' || !SKIN.on) return; const _f = frame; let L = null;
  const coastR = a => { let r = 60; while (r < 330 && MAP.terrainY(Math.cos(a) * r, Math.sin(a) * r) > MAP.sea) r += 4; return r; };
  const build = () => { const root = new THREE.Group(), lam = c => new THREE.MeshLambertMaterial({ color: c, side: THREE.DoubleSide }), mw = lam(0xfffdf7), mt = lam(0x8c9ba8), mb = lam(0xffd23f), tri = p => { const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(p, 3)); g.computeVertexNormals(); return g; };
    const body = new THREE.SphereGeometry(1, 8, 6).scale(.12, .1, .32), beak = new THREE.ConeGeometry(.035, .12, 5).rotateX(-Math.PI / 2).translate(0, 0, -.36), wg = tri([0, 0, -.12, .55, .02, -.02, 0, 0, .14]), tg = tri([.55, .02, -.02, .95, -.04, .1, .5, .01, .08]), gulls = [], boats = [];
    [[.6, 26], [2.7, 32], [4.6, 22]].forEach(([a, h], fi) => { const r0 = coastR(a) + 8, cx = Math.cos(a) * r0, cz = Math.sin(a) * r0; for (let i = 0; i < 4; i++) { const g = new THREE.Group(), wings = []; g.add(new THREE.Mesh(body, mw)); g.add(new THREE.Mesh(beak, mb)); for (const sx of [1, -1]) { const w = new THREE.Group(); w.add(new THREE.Mesh(wg, mw)); w.add(new THREE.Mesh(tg, mt)); w.scale.x = sx; g.add(w); wings.push(w); } g.scale.setScalar(1.6); root.add(g); gulls.push({ g, wings, cx, cz, r: 9 + i * 6, h: h + i * 2.5, w: (.38 - i * .05) * (i % 2 ? -1 : 1), ph: fi * 2.1 + i * 1.7 }); } });
    [[.9, 0xe85a4f], [3.3, 0x2fa6a0], [5.2, 0xffb020]].forEach(([a, c], i) => { const r = coastR(a) + 70, x = Math.cos(a) * r, z = Math.sin(a) * r, b = new THREE.Group(), add = (geo, m, px, py, pz) => { const o = new THREE.Mesh(geo, m); o.position.set(px, py, pz); b.add(o); return o; };
      add(new THREE.BoxGeometry(4, .8, 1.3), lam(c), 0, .2, 0); add(new THREE.BoxGeometry(4.05, .12, 1.35), mw, 0, .55, 0); add(new THREE.ConeGeometry(.65, 1, 4).rotateZ(-Math.PI / 2).rotateX(Math.PI / 4).scale(1, .8, 1), lam(c), 2.45, .2, 0); add(new THREE.BoxGeometry(1.2, .9, 1), mw, -.6, 1.05, 0); add(new THREE.BoxGeometry(1.4, .12, 1.2), lam(0x2fa6a0), -.6, 1.56, 0); add(new THREE.CylinderGeometry(.05, .05, 3, 6), lam(0x8a5f3c), .6, 2.1, 0); add(tri([0, 0, 0, 0, -.45, 0, .7, -.22, 0]), mb, .62, 3.55, 0);
      b.position.set(x, MAP.sea, z); b.rotation.y = a + Math.PI / 2 + i; root.add(b); boats.push({ b, ph: i * 2.3 }); });
    scene.add(root); return { root, gulls, boats }; };
  frame = function (dt) { _f(dt); if (!L && typeof scene !== 'undefined' && MAP.hf) L = build(); if (!L) return; const t = performance.now() / 1000;
    for (const q of L.gulls) { const a = q.ph + q.w * t * .5, s = Math.sign(q.w); q.g.position.set(q.cx + Math.cos(a) * q.r, q.h + Math.sin(t * .7 + q.ph) * 1.2, q.cz + Math.sin(a) * q.r); q.g.rotation.set(0, -a + (s > 0 ? Math.PI : 0), s * .25); const amp = Math.sin(t * .45 + q.ph) > .35 ? .06 : .55, fl = Math.sin(t * 7 + q.ph * 3) * amp; q.wings[0].rotation.z = fl; q.wings[1].rotation.z = -fl; }
    for (const q of L.boats) { q.b.position.y = MAP.sea + Math.sin(t * 1.1 + q.ph) * .15; q.b.rotation.z = Math.sin(t * .9 + q.ph) * .05; } };
})();
