'use strict';
/* ============ INK ISLAND · game: player, third-person camera, combat, bots, HUD, loop ============ */
const G = { state: 'menu', mode: 'br', diff: 0, killLog: [], team: 'blue', ents: [], bots: [], player: null, now: 0, timescale: 1, paused: false, intel: {},
  keys: {}, fire: false, alt: false, altEdge: false, fireEdge: false, mdx: 0, mdy: 0, shake: 0, nades: [], feed: [], dmgDirs: [], hitT: 0, hitKill: false, splats: [], allyLabels: [], botSerial: 0, mapOpen: false, buyOpen: false,
  set: Object.assign({ sens: 1, fov: 80, vol: .7, xh: 'ink', xhStatic: 0, xhSize: 1, quality: 'balanced', motion: .35, inkFx: .5, aimMode: /Mac/.test(navigator.platform) ? 'trackpad' : 'mouse', actorStyle: 'scribe', diff: 0, bots: 23 }, JSON.parse(localStorage.getItem('inkisland') || '{}')),
  noLock: location.search.includes('auto') };
const saveSet = () => localStorage.setItem('inkisland', JSON.stringify(G.set));
let renderer, scene, camera, fxc, fxg, radar, rg, _hudT = 0;
const _cq = new THREE.Quaternion(), _ce = new THREE.Euler(0, 0, 0, 'YXZ'), _cv = new V3(), _cv2 = new V3();

function boot() {
  THREE.ColorManagement.enabled = false;
  renderer = new THREE.WebGLRenderer({ canvas: $('c'), antialias: true, powerPreference: 'high-performance' }); renderer.outputColorSpace = THREE.LinearSRGBColorSpace;
  renderer.autoClear = false; renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setClearColor(PAPER);
  scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(PAPER, FOG_D * .55); camera = new THREE.PerspectiveCamera(G.set.fov, 1, .06, 1600); camera.rotation.order = 'YXZ';
  fxc = $('fx'); fxg = fxc.getContext('2d'); radar = $('radar'); rg = radar.getContext('2d');
  buildMap(scene); FX.init(scene); VM.init(1); makeIcons(); lootInit(); bindInput(); if (touchWanted()) initTouch(); bindUI(); applyQuality(); if (typeof skinApply === 'function') skinApply(); brainLoad(); brainMenu(); onResize(); addEventListener('resize', onResize);
  $('loading').style.display = 'none';
  let last = performance.now(); const loop = t => { requestAnimationFrame(loop); const dt = Math.min(.05, (t - last) / 1000); last = t; if (!G.manualStep) frame(dt); }; requestAnimationFrame(loop);
}
function makeIcons() {
  const s = new THREE.Scene(); if (typeof skinLights === 'function' && SKIN.on && SKIN.lit) skinLights(s); const cam = new THREE.OrthographicCamera(-.66, .66, .24, -.24, .1, 20), fm = fillMat({ objSpace: true, freq: 75, fog: 0, hatch: .8, hw: .13 }), lm = lineMat({ width: 1.6, fog: false }); cam.position.set(5, 0, 0); cam.lookAt(0, 0, 0);
  renderer.setPixelRatio(1); renderer.setSize(330, 120, false); lm.resolution.set(330, 120); G.icons = {};
  for (const k in GUNS) { if (WEAPONS[k].nade) continue; const g = worldGun(k, fm, lm); g.traverse(o => o.frustumCulled = false); const bb = new THREE.Box3().setFromObject(g.children[0]), c = bb.getCenter(new V3()), hw = Math.max(.2, (bb.max.z - bb.min.z) / 2 * 1.12, (bb.max.y - bb.min.y) / 2 * 1.12 * 2.75);
    g.position.set(0, -c.y, -c.z); cam.left = -hw; cam.right = hw; cam.top = hw / 2.75; cam.bottom = -hw / 2.75; cam.updateProjectionMatrix();
    s.add(g); renderer.setClearColor(PAPER, 0); renderer.clear(); renderer.render(s, cam); G.icons[k] = renderer.domElement.toDataURL(); s.remove(g); }
  /* every other item gets a square icon from its ground model, seen from a three-quarter view above */
  const cam2 = new THREE.OrthographicCamera(-.3, .3, .3, -.3, .1, 20); cam2.position.set(3, 2.6, 3); cam2.lookAt(0, 0, 0); renderer.setSize(120, 120, false); lm.resolution.set(120, 120);
  for (const k in ITEMS) { if (ITEMS[k].kind === 'gun' || typeof lgTemplate !== 'function') continue; const t = lgTemplate(k); if (!t || !t.P.length) continue; const sk = new Sk('sun'); sk.P.push(...t.P); sk.T.push(...t.T); sk.C.push(...t.C); sk.L.push(...t.L); if (t.N && t.N.length === t.P.length) sk.N.push(...t.N); else for (let i = 0; i < t.P.length; i += 3) sk.N.push(0, 1, 0); const g = sk.bake(fm, lm); g.traverse(o => o.frustumCulled = false); const bb = new THREE.Box3().setFromObject(g.children[0]), c = bb.getCenter(new V3()), r = Math.max(.12, bb.getSize(new V3()).length() / 2 * .78);
    g.position.set(-c.x, -c.y, -c.z); cam2.left = -r; cam2.right = r; cam2.top = r; cam2.bottom = -r; cam2.updateProjectionMatrix(); s.add(g); renderer.setClearColor(PAPER, 0); renderer.clear(); renderer.render(s, cam2); G.icons[k] = renderer.domElement.toDataURL(); s.remove(g); g.traverse(o => o.geometry && o.geometry.dispose()); }
  renderer.setClearColor(PAPER, 1); renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
}
function applyQuality() { renderer.setPixelRatio(Math.min(devicePixelRatio, ({ low: 1, balanced: 1.5, high: 2 })[G.set.quality] || 1.5)); MAP.setDetail(G.set.quality); if (camera && VM.cam) onResize(); }
function onResize() { const w = innerWidth, h = innerHeight; renderer.setSize(w, h); camera.aspect = VM.cam.aspect = w / h; camera.updateProjectionMatrix(); VM.cam.updateProjectionMatrix(); G.fxDpr = Math.min(2, window.devicePixelRatio || 1); fxc.width = Math.round(w * G.fxDpr); fxc.height = Math.round(h * G.fxDpr); for (const m of LINE_MATS) m.resolution.set(w, h); }

/* ---------------- input ---------------- */
function bindInput() {
  addEventListener('keydown', e => { if (e.code === 'Escape') { if (G.state !== 'menu' && G.state !== 'end' && (G.noLock || G.paused || !document.pointerLockElement)) { setPause(!G.paused); return; } } if (['INPUT', 'SELECT'].includes(e.target.tagName)) return; if (e.code === 'Tab' || (G.state !== 'menu' && ['Space', 'ControlLeft', 'KeyF', 'KeyE', 'AltLeft', 'AltRight'].includes(e.code))) e.preventDefault(); if (e.repeat) return; if (G.paused) { onKey(e.code); return; } G.keys[e.code] = true; onKey(e.code); });
  addEventListener('keyup', e => { G.keys[e.code] = false; if (e.code === 'KeyV') G.alt = false; });
  addEventListener('blur', () => clearInput());
  addEventListener('mousemove', mouseLook); addEventListener('mouseout', e => { if (!e.relatedTarget) resetLook(); });
  addEventListener('mousedown', e => { if (e.target.closest && e.target.closest('button,input,select,.ov')) return; if (!locked()) { if (e.target === renderer.domElement && G.state !== 'menu' && !G.paused) lock(); return; } if (e.button === 0) { G.fire = true; G.fireEdge = true; } if (e.button === 2) { G.alt = true; G.altEdge = true; } });
  addEventListener('mouseup', e => { if (e.button === 0) G.fire = false; if (e.button === 2) G.alt = false; });
  addEventListener('contextmenu', e => e.preventDefault());
  addEventListener('wheel', e => { if (!locked() || !G.player || !G.player.alive || Math.abs(e.deltaY) < 12 || performance.now() < (G.wheelAt || 0)) return; G.wheelAt = performance.now() + 180; const pl = G.player, order = weaponOrder(pl), i = order.indexOf(pl.cur); switchTo(order[(i + (e.deltaY > 0 ? 1 : order.length - 1)) % order.length]); }, { passive: true });
  document.addEventListener('pointerlockchange', () => { resetLook(); if (!document.pointerLockElement && G.state === 'live' && !G.noLock && !G.uiUnlock) setPause(true); });
}
const locked = () => !G.paused && !G.mapOpen && !G.invOpen && !G.crateOpen && G.state === 'live' && (G.noLock || document.pointerLockElement === renderer.domElement);
function lock() { if (G.noLock || G.lockPending || document.pointerLockElement === renderer.domElement) return; const el = renderer.domElement, fail = e => { if (e && ['NotAllowedError', 'AbortError'].includes(e.name)) { $('captureMouse').textContent = '点击继续鼠标控制'; return; } G.noLock = true; banner('鼠标未锁定', '当前环境不支持指针锁定 · 用 Chrome / Safari 直接打开', 'lose'); };
  const request = raw => { try { const p = raw ? el.requestPointerLock({ unadjustedMovement: G.set.aimMode !== 'trackpad' }) : el.requestPointerLock(); if (p && p.then) { G.lockPending = true; p.then(() => { G.lockPending = false; }, e => { G.lockPending = false; if (raw && e.name === 'NotSupportedError') request(false); else fail(e); }); } } catch (e) { G.lockPending = false; fail(e); } }; request(true); }
function clearInput() { resetLook(); G.fire = G.alt = G.fireEdge = G.altEdge = false; G.keys = {}; G.mdx = G.mdy = 0; }
function unlockUI() { if (document.pointerLockElement) { G.uiUnlock = true; document.exitPointerLock(); setTimeout(() => G.uiUnlock = false, 100); } clearInput(); }
function setPause(v) { G.paused = v; $('pause').classList.toggle('on', v); clearInput(); if ($('devSet')) { if (v) { $('pauseSet').appendChild($('devSet')); $('devSet').classList.add('open'); const pl = G.player; $('pauseSum').textContent = `存活 ${G.ents.filter(e => e.alive).length} · 第 ${ZONE.on ? ZONE.ph + 1 : 1} 圈 · 击杀 ${pl ? pl.kills : 0}`; } else { const r = document.querySelector('#menu .menuR'); if (r && $('devSet').parentNode !== r) r.insertBefore($('devSet'), $('brainFoot')); $('devSet').classList.remove('open'); $('quitNote').hidden = true; G.quitArm = 0; } } if ($('touch')) $('touch').classList.toggle('dim', v); if (v) { G.mapOpen = false; $('bigmap').classList.remove('on'); G.invOpen = false; $('inv').classList.remove('on'); G.crateOpen = false; $('crate').classList.remove('on'); unlockUI(); } else lock(); }
function toggleInv(force) { const on = force === undefined ? !G.invOpen : force; G.invOpen = on; $('inv').classList.toggle('on', on); clearInput(); if (on) { unlockUI(); drawInv(); } else lock(); }
/* the bag panel: three columns — what lies at your feet, what you carry, what you wear and hold — every item with its paper icon */
const ATT_SLOTS = [['sup', '消音器'], ['mag', '扩容弹匣'], ['grip', '握把'], ['comp', '补偿器'], ['stock', '枪托'], ['dot', '红点']], ATT_KEY = { sup: 'sup', mag: 'xmag', grip: 'grip', comp: 'comp', stock: 'stock', dot: 'dot' };
function invIcon(k, cls = '') { return `<img class="${cls}" src="${G.icons && G.icons[k] || ''}" alt="">`; }
function invRow(k, drag, title, sub, btns) { const gun = ITEMS[k] && ITEMS[k].kind === 'gun'; return `<div class="it${gun ? ' gun' : ''}"${drag ? ` draggable="true" data-drag="${drag}"` : ''}>${invIcon(k)}<div class="itT"><b>${title}</b><small>${sub || ''}</small></div><div class="itB">${btns || ''}</div></div>`; }
function invBetter(pl, k) { const d = ITEMS[k]; if (!d) return false; if (d.kind === 'vest') return d.lv > pl.vestLv; if (d.kind === 'helm') return d.lv > pl.helmLv; if (d.kind === 'bag') return d.lv > pl.bagLv; if (d.kind === 'scope') return !pl.scope || ITEMS[pl.scope].lv < d.lv; if (d.kind === 'gun') return !pl.inv[WEAPONS[k].slot]; if (d.kind === 'att') return !pl.att[d.slot]; if (d.kind === 'suit') return !pl.ghillie; return false; }
function drawInv() { const pl = G.player, cap = BAG_CAP(pl.bagLv), load = invLoad(pl), B = (k, label, extra = '') => ` <button data-k="${k}"${extra} class="drop">${label}</button>`;
  $('invCap').textContent = `负重 ${load.toFixed(0)} / ${cap}`; $('invCap').classList.toggle('full', load >= cap - .01); $('invCapBar').classList.toggle('full', load >= cap - .01); $('invCapBar').firstElementChild.style.width = Math.min(100, load / cap * 100) + '%';
  // ground
  const ground = G.invGround = pl.alive && !pl.air ? lootNearList(pl, 3.5).slice(0, 14) : []; $('invGN').textContent = ground.length ? `${ground.length} 件` : ''; $('invG').innerHTML = ground.length ? ground.map((it, i) => invRow(it.k, 'g:' + i, ITEMS[it.k].name + (invBetter(pl, it.k) ? '<span class="up">↑ 升级</span>' : ''), it.qty > 1 ? '×' + it.qty : (ITEMS[it.k].kind === 'ammo' ? '' : invDesc(it.k)), `<button data-g="${i}" class="drop${invBetter(pl, it.k) ? ' pri' : ''}">拾取</button>`)).join('') : '<div class="empty">脚下没有东西 · 走近物品再打开 · F 直接拾取最近的</div>';
  // bag: ammo pools, meds, grenades
  const rows = []; for (const t of ['556', '762', '9mm', '12g', '45', '300', 'bolt']) if (pl.pool[t]) { const k = 'a' + t, u = ITEMS[k].qty; rows.push(invRow(k, 'b:' + k, ITEMS[k].name, `×${pl.pool[t]}`, B(k, '丢 ' + Math.min(u, pl.pool[t])) + (pl.pool[t] > u ? `<button class="drop more" data-more="1">…</button><div class="sub">${B(k, '拆半', ` data-n="${Math.ceil(pl.pool[t] / 2)}"`)}${B(k, '全丢', ` data-n="${pl.pool[t]}"`)}</div>` : ''))); }
  for (const [kc, k] of Object.entries(MED_KEYS)) if (pl.meds[k]) rows.push(invRow(k, 'b:' + k, `<span class="key">${kc.replace('Digit', '').replace('Minus', '-').replace('Equal', '=')}</span>${ITEMS[k].name}`, `×${pl.meds[k]} · ${invDesc(k)}`, `<button data-use="${k}" class="drop pri">用</button>` + B(k, '丢')));
  for (const k of NADES) if (pl.nades[k]) rows.push(invRow(k, 'b:' + k, `<span class="key">4</span>${ITEMS[k].name}`, `×${pl.nades[k]} · G 直接投掷`, B(k, '丢')));
  $('invBag').innerHTML = rows.join('') || '<div class="empty">背包是空的</div>';
  // gear: weapon slots with attachment chips, melee, armour cards
  const gunSlot = (n, k, hint) => { if (!k) return `<div class="slot empty"><span class="sn">${n}</span><div class="sEmpty">${hint}</div></div>`; const w = WEAPONS[k], a = pl.ammo[k], chips = n[0] !== '1' ? '' : ATT_SLOTS.map(([sl, nm]) => pl.att[sl] ? `<span class="chip" data-k="${ATT_KEY[sl]}" title="点击卸下">${ITEMS[ATT_KEY[sl]].name} ×</span>` : `<span class="chip empty">${nm}</span>`).join('') + (n[0] !== '1' ? (n[0] === '2' ? '<span class="chip empty">手枪不装配件</span>' : '') : w.scope || w.pellets ? '' : pl.scope ? `<span class="chip" data-k="${pl.scope}" title="点击卸下">${ITEMS[pl.scope].name} ×</span>` : '<span class="chip empty">瞄具</span>');
    return `<div class="slot${pl.cur === k ? ' cur' : ''}" draggable="true" data-drag="b:${k}"><span class="sn">${n}</span>${invIcon(k, 'gunIco')}<div class="sT"><b>${w.name}</b><small>${a ? `${a.mag} / ${a.res}` : ''} · ${AMMO[k] ? ITEMS['a' + AMMO[k]].name : ''} · 伤害 ${w.dmg}</small><div class="chips">${chips}</div></div><div class="itB">${B(k, '丢')}</div></div>`; };
  const card = (label, k, sub) => k ? `<div class="gcard" draggable="true" data-drag="b:${k}">${invIcon(k)}<b>${ITEMS[k].name}</b><small>${sub || ''}</small>${B(k, '丢')}</div>` : `<div class="gcard empty"><span>${label}</span><small>未装备</small></div>`;
  $('invGear').innerHTML = gunSlot('1 主武器', pl.inv[1], '捡一把步枪 / 狙击枪 / 霰弹枪') + gunSlot('2 副武器', pl.inv[2], '捡一把手枪') + `<div class="slot small"><span class="sn">3 近战</span>${invIcon('knife', 'gunIco')}<div class="sT"><b>${WEAPONS.knife.name}</b></div></div>`
    + `<div class="gear4">${card('头盔', pl.helmLv ? 'helm' + pl.helmLv : null, '减少头部伤害')}${card('护甲', pl.vestLv ? 'vest' + pl.vestLv : null, `${Math.ceil(pl.armor)} / ${ITEMS['vest' + (pl.vestLv || 1)].ap} AP`)}${card('背包', pl.bagLv ? 'bag' + pl.bagLv : null, `负重上限 ${cap}`)}${card('伪装', pl.ghillie ? 'ghillie' : null, 'Bot 更难发现你')}</div>`
    + `<div class="vitals"><span>生命 ${Math.min(100, Math.ceil(pl.hp))}</span><i style="width:${Math.max(0, Math.min(100, pl.hp))}%"></i></div><div class="vitals boost" title="能量：吃止痛药/饮料积累，缓慢回血并加快移动"><span>能量 ${Math.round(pl.boost || 0)}</span><i style="width:${Math.max(0, Math.min(100, pl.boost || 0))}%"></i></div>`;
}
function invDesc(k) { const d = ITEMS[k]; if (!d) return ''; if (d.kind === 'med') return d.heal ? `${d.t}s 回 ${d.heal}${d.cap < 100 ? '（至 ' + d.cap + '）' : ''}` : `${d.t}s 能量 +${d.boost}`; if (d.kind === 'vest') return `${d.ap} 护甲 · 挡身体伤害`; if (d.kind === 'bag') return `负重上限 ${BAG_CAP(d.lv)}`; if (d.kind === 'helm') return `${d.lv} 级 · 挡头部伤害`; if (d.kind === 'att') return { sup: '消音 · Bot 更难听见', mag: '弹匣 +10', grip: '后坐 −25%', comp: '后坐 −22%', stock: '散布 −15%', dot: '无瞄具的枪开镜更快' }[d.slot] || '配件'; if (d.kind === 'scope') return `${d.lv} 倍`; if (d.kind === 'nade') return '投掷物'; if (d.kind === 'suit') return '伪装'; if (d.kind === 'gun') return `伤害 ${WEAPONS[k].dmg}`; return ''; }
function combatNotice(t) { banner(t, '', 'go'); clearTimeout(G._nt); G._nt = setTimeout(() => $('banner').classList.remove('on'), 900); }
function mapClick(e) { const c = $('bigMapC'), r = c.getBoundingClientRect(), x = (e.clientX - r.left) / r.width * MAP.size + MAP.ox, z = (e.clientY - r.top) / r.height * MAP.size + MAP.oz; if (e.button === 2) G.marker = null; else G.marker = { x, z }; drawBigMap(); SFX.ui(); }
function toggleMap(force) { const on = force === undefined ? !G.mapOpen : force; G.mapOpen = on; $('bigmap').classList.toggle('on', on); clearInput(); if (on) { unlockUI(); drawBigMap(); } else lock(); }
function drawBigMap() { const c = $('bigMapC'), g = c.getContext('2d'), k = c.width / MAP.size, pl = G.player; g.drawImage(MAP.mini, 0, 0, c.width, c.height); if (typeof SKIN !== 'undefined' && SKIN.on) { g.save(); g.font = '900 15px "PingFang SC", system-ui, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; for (const t of TOWNS) { const x = (t.x - MAP.ox) * k, y = (t.z - MAP.oz) * k - t.r * k - 10, w = g.measureText(t.name).width + 18; g.fillStyle = '#2e3a59'; g.beginPath(); g.roundRect(x - w / 2, y - 11 + 3, w, 22, 11); g.fill(); g.fillStyle = '#fff8ec'; g.strokeStyle = '#2e3a59'; g.lineWidth = 2.5; g.beginPath(); g.roundRect(x - w / 2, y - 11, w, 22, 11); g.fill(); g.stroke(); g.fillStyle = '#2e3a59'; g.fillText(t.name, x, y + 1); } g.restore(); } if (typeof drawZoneOn === 'function') drawZoneOn(g, k); drawRedOn(g, k); drawVehOn(g, k); drawMarkerOn(g, k); if (PLANE.on) { g.save(); g.strokeStyle = UIC('#16161c'); g.lineWidth = 2; g.setLineDash([10, 8]); g.beginPath(); g.moveTo((PLANE.from.x - MAP.ox) * k, (PLANE.from.z - MAP.oz) * k); g.lineTo((PLANE.to.x - MAP.ox) * k, (PLANE.to.z - MAP.oz) * k); g.stroke(); g.setLineDash([]); g.translate((PLANE.pos.x - MAP.ox) * k, (PLANE.pos.z - MAP.oz) * k); g.rotate(-PLANE.yaw); g.fillStyle = UIC('#16161c'); g.beginPath(); g.moveTo(0, -12); g.lineTo(8, 8); g.lineTo(0, 4); g.lineTo(-8, 8); g.closePath(); g.fill(); g.restore(); } if (pl) { const x = (pl.pos.x - MAP.ox) * k, y = (pl.pos.z - MAP.oz) * k; g.save(); g.translate(x, y); g.rotate(-pl.yaw); g.fillStyle = UIC('#2d6cb3'); g.strokeStyle = UIC('#f5f2ea'); g.lineWidth = 2; g.beginPath(); g.moveTo(0, -9); g.lineTo(6, 6); g.lineTo(0, 3); g.lineTo(-6, 6); g.closePath(); g.fill(); g.stroke(); g.restore(); } }
function onKey(c) {
  if (c === 'KeyM' && G.state === 'live' && !G.paused && !G.invOpen) return toggleMap();
  const pl = G.player; if (G.state !== 'live' || !pl || G.paused || G.mapOpen || pl.climb) return; if (G.crateOpen) { if (c === 'KeyF' || c === 'Tab') crateClose(); return; } if (G.invOpen && c !== 'Tab') { if (MED_KEYS[c]) healStart(pl, MED_KEYS[c]); drawInv(); return; }
  if (!pl.alive) return;
  if (c === 'KeyV') { G.alt = G.altEdge = true; return; }
  if (c === 'Tab') return toggleInv();
  if (c === 'KeyF') { if (pl.veh) { vehExit(pl); return; } const cr = !pl.air && crateNear(pl); if (cr) { crateOpen(cr); return; } const it = lootNearList(pl)[0]; if (it && !pl.air) { const r = invTake(pl, it); if (r) { SFX.click(1400, .2); combatNotice(r); return; } if (!vehNear(pl)) { SFX.deny(); return; } } const v = !pl.air && vehNear(pl); if (v) { if (v.flipped) { vehRight(v); combatNotice('扶正 ' + v.t.name); } else vehEnter(pl, v); } return; }
  if (c === 'KeyZ') { if (!pl.air && !pl.wet) { pl.prone = !pl.prone; SFX.click(500, .2); } return; }
  if (c === 'KeyB') { const w = WEAPONS[pl.cur]; if (w.auto) { pl.modes[pl.cur] = pl.modes[pl.cur] === 'single' ? 'auto' : 'single'; SFX.click(1100, .2); combatNotice(pl.modes[pl.cur] === 'single' ? '单发' : '连发'); } return; }
  if (c === 'Digit4') { const l = nadeList(pl); if (l.length) switchTo(l[(l.indexOf(pl.cur) + 1) % l.length]); return; }
  if (c === 'KeyG') { const l = nadeList(pl); if (l.length && !WEAPONS[pl.cur].nade) switchTo(l[0]); return; }
  if (MED_KEYS[c]) healStart(pl, MED_KEYS[c]);
  else if (c === 'Digit1' && pl.inv[1]) switchTo(pl.inv[1]); else if (c === 'Digit2' && pl.inv[2]) switchTo(pl.inv[2]); else if (c === 'Digit3') switchTo('knife');
  else if (c === 'KeyQ' && pl.last && hasWeapon(pl.last)) switchTo(pl.last); else if (c === 'KeyR') startReload();
}
const NADES = ['he', 'flash', 'smoke', 'fire'], nadeList = pl => NADES.filter(k => pl.nades && pl.nades[k] > 0), weaponOrder = pl => [pl.inv[1], pl.inv[2], 'knife', ...nadeList(pl)].filter(Boolean);
const hasWeapon = k => { const pl = G.player; return k === 'knife' || pl.inv[1] === k || pl.inv[2] === k || (WEAPONS[k].nade && pl.nades[k] > 0); };
const LOOK = { x: null, y: null, native: false, skip: 0 };
function resetLook() { LOOK.x = LOOK.y = null; LOOK.skip = 1; }
function mouseLook(e) { const pl = G.player; if (!locked() || !pl || !pl.alive || (e.target.closest && e.target.closest('button,input,select,.ov'))) { LOOK.x = LOOK.y = null; return; } const native = document.pointerLockElement === renderer.domElement; let dx, dy; if (native !== LOOK.native) { LOOK.native = native; resetLook(); } if (native) { dx = e.movementX; dy = e.movementY; if (LOOK.skip) { LOOK.skip--; return; } } else { const x = e.clientX, y = e.clientY; if (LOOK.x === null) { LOOK.x = x; LOOK.y = y; return; } dx = x - LOOK.x; dy = y - LOOK.y; LOOK.x = x; LOOK.y = y; } if (!Number.isFinite(dx) || !Number.isFinite(dy)) return; const d = Math.hypot(dx, dy), pad = G.set.aimMode === 'trackpad'; if (d > (pad ? 180 : 500)) return; const cap = pad ? 65 : 180, f = d > cap ? cap / d : 1, k = (pad ? .00105 : .0021) * G.set.sens * (camera.fov / G.set.fov); dx *= f; dy *= f; if (G.keys.AltLeft || G.keys.AltRight) { pl.fy = clamp((pl.fy || 0) - dx * k, -2.7, 2.7); pl.fp = clamp((pl.fp || 0) - dy * k, -1.2, 1.2); return; } pl.yaw -= dx * k; pl.pitch = clamp(pl.pitch - dy * k, -1.35, 1.35); G.mdx += dx; G.mdy += dy; }

/* ---------------- player ---------------- */
function makePlayer() { const p = makeEnt('blue', '你', true); invInit(p); Object.assign(p, { prone: false, stam: 100, sprint: false, mantle: null, lean: 0, fy: 0, fp: 0, cur: 'knife', last: 'knife', landSlow: 0, act: null, nextFire: 0, reloadEnd: -1, reloadStart: 0, drawEnd: 0, shots: 0, lastShot: -9, recP: 0, recY: 0, recTP: 0, recTY: 0, punch: 0, roll: 0, scoped: 0, ads: 0, bobPhase: 0, pending: null, deathT: 0, fallDir: 1, styleId: G.set.actorStyle });
  p.model = buildSoldier('blue', p.styleId); scene.add(p.model.root); return p; }
const giveWeapon = invGive;
function switchTo(k) { const pl = G.player; if (!k || k === pl.cur && VM.key === k) return; if (k !== pl.cur) pl.last = pl.cur; pl.cur = k; pl.weapon = k; VM.show(k); if (typeof attachVisuals === 'function') attachVisuals(); setEntWeapon(pl, k); pl.drawEnd = G.now + WEAPONS[k].draw; pl.reloadEnd = -1; pl.scoped = 0; pl.shots = 0; pl.pending = null; SFX.click(700, .25); }
function startReload() { const pl = G.player, w = WEAPONS[pl.cur], a = pl.ammo[pl.cur]; if (!a || pl.reloadEnd >= 0 || a.mag >= magCap(pl, w) || a.res <= 0 || G.now < pl.drawEnd) return; pl.reloadStart = G.now; pl.reloadEnd = G.now + w.reload; pl.scoped = 0; VM.insp = 1; if (w.pump) { for (let i = 0; i < 5; i++) SFX.shellIn(w.reload * (.12 + i * .16)); SFX.pump(w.reload * .9); } else SFX.reload(w.snd, w.reload); }
function updatePlayer(dt) {
  const pl = G.player, now = G.now, k = G.keys, w = WEAPONS[pl.cur], frozen = G.state !== 'live';
  if (pl.air) { // in the plane or under canopy: WASD steers, look pitch dives, space jumps / opens the chute
    let f = (k.KeyW ? 1 : 0) - (k.KeyS ? 1 : 0), sd = (k.KeyD ? 1 : 0) - (k.KeyA ? 1 : 0), wx = -Math.sin(pl.yaw) * f + Math.cos(pl.yaw) * sd, wz = -Math.cos(pl.yaw) * f - Math.sin(pl.yaw) * sd; const wl = Math.hypot(wx, wz); if (wl > 0) { wx /= wl; wz /= wl; }
    if (pl.air === 'plane') { if (k.Space && planeOverLand() && !pl.spaceHeld) { jumpOut(pl); pl.spaceHeld = true; } pl.pos.copy(PLANE.pos); pl.ads = 0; return; }
    const dive = clamp((-pl.pitch - .35) / .9, 0, 1) * (f > 0 ? 1 : .6); if (!k.Space) pl.spaceHeld = false; airUpdate(pl, dt, wx, wz, dive, k.Space && !pl.spaceHeld && pl.agl > AIR.autoChute); if (k.Space) pl.spaceHeld = true; pl.ads = damp(pl.ads, 0, 14, dt); return; }
  // stance: C held = crouch, Z toggles prone (crouchAmt 2.7 lowers the eye to .35 m and flattens the hitbox)
  const wantC = pl.prone ? 2.7 : (k.KeyC || k.ControlLeft) ? 1 : 0; let tc = wantC; if (wantC < 1 && pl.crouchAmt > .05) { const h = pl.hgt; pl.hgt = 1.8; if (entOverlap(pl, pl.pos.x, pl.pos.y, pl.pos.z, MAP.near(pl.pos.x, pl.pos.z))) tc = 1; pl.hgt = h; }
  const oh = pl.hgt; pl.crouchAmt = damp(pl.crouchAmt, tc, pl.prone || pl.crouchAmt > 1.1 ? 7 : 13, dt); pl.hgt = pl.crouchAmt > 1 ? 1.35 - .25 * Math.min(1, (pl.crouchAmt - 1) / 1.7) : 1.8 - .45 * pl.crouchAmt; if (!pl.onGround) pl.pos.y += oh - pl.hgt;
  let f = (k.KeyW ? 1 : 0) - (k.KeyS ? 1 : 0), s = (k.KeyD ? 1 : 0) - (k.KeyA ? 1 : 0); if (frozen || pl.act) f = s = 0;
  let wx = -Math.sin(pl.yaw) * f + Math.cos(pl.yaw) * s, wz = -Math.cos(pl.yaw) * f - Math.sin(pl.yaw) * s; const wl = Math.hypot(wx, wz); if (wl > 0) { wx /= wl; wz /= wl; }
  healUpdate(pl, dt); if (inWater(pl)) pl.prone = false; const wet = inWater(pl), wantSprint = (k.ShiftLeft || k.ShiftRight) && f > 0 && pl.crouchAmt < .5 && !wet && !pl.heal && pl.ads < .3 && pl.stam > (pl.sprint ? 0 : 12); pl.sprint = wantSprint; pl.stam = clamp(pl.stam + (pl.sprint ? -dt * 100 / 6 : dt * 100 / 9), 0, 100); const walking = k.KeyX, sp = 5.1 * w.speed * (pl.crouchAmt > 1.3 ? .22 : pl.crouchAmt > .5 ? .45 : walking ? .52 : pl.sprint ? 1.42 : 1) * (pl.ads > .5 ? .55 : 1) * (pl.landSlow > 0 ? .58 : 1) * (wet ? .42 : 1) * (pl.heal ? .35 : 1); pl.landSlow -= dt; pl.wet = wet;
  if (pl.veh) { healUpdate(pl, dt); pl.ads = damp(pl.ads, 0, 14, dt); pl.lean = damp(pl.lean, 0, 10, dt); if (!(k.AltLeft || k.AltRight)) { pl.fy = damp(pl.fy || 0, 0, 12, dt); pl.fp = damp(pl.fp || 0, 0, 12, dt); } animSoldier(pl, dt); ridePose(pl, pl.veh); return; }
  const free = !!(k.AltLeft || k.AltRight); if (!free) { pl.fy = damp(pl.fy || 0, 0, 12, dt); pl.fp = damp(pl.fp || 0, 0, 12, dt); } pl.lean = damp(pl.lean, pl.prone || pl.sprint ? 0 : (k.KeyE ? 1 : 0) - (k.KeyQ ? 1 : 0), 10, dt);
  if (pl.mantle) { const mt = pl.mantle, dur = mt.to.through ? .75 : .55; mt.t += dt; const u = Math.min(1, mt.t / dur), ease = u * u * (3 - 2 * u); pl.pos.x = lerp(mt.from.x, mt.to.x, ease); pl.pos.z = lerp(mt.from.z, mt.to.z, ease); pl.pos.y = mt.to.through ? lerp(mt.from.y, mt.to.y, ease) + Math.sin(u * Math.PI) * .5 : lerp(mt.from.y, mt.to.y, Math.min(1, u * 1.6)); if (mt.to.through) pl.crouchAmt = Math.max(pl.crouchAmt, .9); pl.vel.set(0, 0, 0); pl.onGround = true; if (u >= 1) { pl.mantle = null; SFX.step(null, .25); } animSoldier(pl, dt); pl.model.root.visible = pl.ads < .85; return; }
  if (k.Space && !frozen && !wet && !pl.prone && !pl.spaceHeld2) { pl.spaceHeld2 = true; const fx = -Math.sin(pl.yaw), fz = -Math.cos(pl.yaw), ledge = findLedge(pl, fx, fz); if (ledge) { pl.mantle = { t: 0, from: pl.pos.clone(), to: ledge }; pl.crouchAmt = Math.max(pl.crouchAmt, .3); SFX.swish(); } else if (pl.onGround) { pl.vel.y = 5.95; pl.onGround = false; SFX.step(null, .2); } } if (!k.Space) pl.spaceHeld2 = false;
  groundMove(pl, wx, wz, wl ? sp : 0, dt, 14, 9);
  const hs = Math.hypot(pl.vel.x, pl.vel.z), cap = 5.1 * 1.6; if (hs > cap) { pl.vel.x *= cap / hs; pl.vel.z *= cap / hs; }
  const px = pl.pos.x, pz = pl.pos.z; moveEntity(pl, dt);
  if (pl.landed > 2.6) { pl.landSlow = .3; pl.vel.x *= .6; pl.vel.z *= .6; }
  if (pl.landed > 4) { VM.dip = Math.min(.06, pl.landed * .005); pl.punch += pl.landed * .004; SFX.land(null); if (pl.landed > 12.5) hurt(pl, Math.round((pl.landed - 12.5) * 9), null, null, 'legs', null); botHear(pl.pos, pl.team, 14, 'step'); }
  pl.stepSmooth = clamp(pl.stepSmooth, -.6, .6); pl.stepSmooth = damp(pl.stepSmooth, 0, 13, dt);
  const moved = Math.hypot(pl.pos.x - px, pl.pos.z - pz); if (pl.onGround) { pl.bobPhase += moved * 2.0; if (hs > 3 && !walking) { pl.stepAcc += moved; if (pl.stepAcc > 2.1) { pl.stepAcc = 0; SFX.step(null, .22, surfaceAt(pl.pos)); botHear(pl.pos, pl.team, 11, 'step'); } } }
  // ---- weapon ----
  if (pl.reloadEnd >= 0) { VM.reloadT = clamp((now - pl.reloadStart) / w.reload, 0, 1); if (now >= pl.reloadEnd) { const a = pl.ammo[pl.cur], n = Math.min(magCap(pl, w) - a.mag, a.res); a.mag += n; a.res -= n; pl.reloadEnd = -1; VM.reloadT = -1; } } else VM.reloadT = -1;
  if (now - pl.lastShot > .32) pl.shots = 0;
  if (now - pl.lastShot > .1) { pl.recTP = damp(pl.recTP, 0, 7, dt); pl.recTY = damp(pl.recTY, 0, 7, dt); }
  pl.recP = damp(pl.recP, pl.recTP, 30, dt); pl.recY = damp(pl.recY, pl.recTY, 30, dt); pl.punch = damp(pl.punch, 0, 9, dt); pl.roll = damp(pl.roll, -s * .012, 8, dt);
  const ready = now >= pl.drawEnd && pl.reloadEnd < 0 && !frozen && !pl.act && !pl.heal && !G.invOpen && !G.mapOpen && !G.crateOpen && !pl.sprint && !pl.mantle;
  // hold right mouse: shoulder camera glides into the eye and the first-person gun takes over
  const wantAds = G.alt && ready && !w.melee && !w.nade && !pl.wet && !pl.sprint && !free; pl.ads = damp(pl.ads, wantAds ? 1 : 0, 14, dt); if (wantAds && !pl.scoped) { pl.scoped = 1; pl.scopeSince = now; SFX.click(1200, .15); } if (!wantAds && pl.scoped) pl.scoped = 0;
  if (frozen) pl.pending = null; if (pl.pending && now >= pl.pending.t) { pl.pending.fn(); pl.pending = null; }
  if (ready && now >= pl.nextFire) {
    if (w.melee) { if (G.fire || G.alt) { const heavy = !G.fire; pl.nextFire = now + (heavy ? w.rate2 : w.rate); VM.atk = 0; VM.atkKind = heavy ? 1 : 0; pl.atkAnim = .32; SFX.swish(); pl.pending = { t: now + (heavy ? .16 : .09), fn: () => melee(pl, heavy ? w.dmg2 : w.dmg) }; } }
    else if (w.nade) { const kind = pl.cur; if (G.fireEdge && pl.nades[kind] > 0 && !free) { pl.nextFire = now + 1; VM.atk = 0; pl.pending = { t: now + .2, fn: () => { throwNade(pl, kind); pl.nades[kind]--; if (pl.nades[kind] <= 0) switchTo(nadeList(pl)[0] || pl.inv[1] || pl.inv[2] || 'knife'); } }; } }
    else if (((w.auto && pl.modes[pl.cur] !== 'single') ? G.fire : G.fireEdge) && !pl.wet && !free) { const a = pl.ammo[pl.cur]; if (a.mag > 0) playerFire(pl, w, a); else { if (G.fireEdge) SFX.click(1600, .25); if (a.res > 0) startReload(); } }
  }
  if (pl.ammo[pl.cur] && pl.ammo[pl.cur].mag === 0 && pl.ammo[pl.cur].res > 0 && pl.reloadEnd < 0 && now > pl.nextFire && ready) startReload();
  pl.spread = curSpread(pl, w);
  animSoldier(pl, dt); pl.model.root.visible = pl.ads < .85; pl.model.upper.rotation.z -= pl.lean * .32; if (pl.crouchAmt > 1) { const m = pl.model, kk = Math.min(1, (pl.crouchAmt - 1) / 1.7); m.root.rotation.x = -1.45 * kk; m.root.position.y = pl.pos.y + .32 * kk; m.upper.position.y = lerp(m.upper.position.y, .9, kk); m.upper.rotation.x = lerp(m.upper.rotation.x, .25, kk); m.legL.position.y = m.legR.position.y = lerp(m.legL.position.y, .9, kk); m.legL.rotation.set(lerp(m.legL.rotation.x, .1, kk), 0, -.1 * kk); m.legR.rotation.set(lerp(m.legR.rotation.x, .1, kk), 0, .1 * kk); m.legL.shin.rotation.x = m.legR.shin.rotation.x = lerp(m.legL.shin.rotation.x, 0, kk); } else pl.model.root.rotation.x = 0;
}
/* is there a ledge ahead we can pull ourselves onto? probe the standing box a step forward at rising heights */
function findLedge(pl, fx, fz) { const near = MAP.near(pl.pos.x + fx, pl.pos.z + fz), px = pl.pos.x + fx * .85, pz = pl.pos.z + fz * .85, hgt = pl.hgt, y0 = pl.pos.y; pl.hgt = 1.75;
  let best = null; for (let h = .55; h <= 2.35; h += .1) { const y = y0 + h; if (entOverlap(pl, px, y + .02, pz, near)) continue; const saved = pl.pos.x, savedz = pl.pos.z, savedy = pl.pos.y; pl.pos.x = px; pl.pos.z = pz; pl.pos.y = y + .02; const sup = supportY(pl, near); pl.pos.x = saved; pl.pos.z = savedz; pl.pos.y = savedy; if (sup > y0 + .5 && sup <= y + .03 && sup >= y - .35) { best = new V3(px, sup, pz); break; } }
  pl.hgt = hgt; if (!best) { const w = windowAhead(pl, fx, fz); if (!w) return null; if (!w.broken) breakGlass(w, pl); const lx = (w.axis === 'x' ? (w.s0 + w.s1) / 2 : w.fixed) + fx * 1.25, lz = (w.axis === 'x' ? w.fixed : (w.s0 + w.s1) / 2) + fz * 1.25; const sx = pl.pos.x, sz = pl.pos.z, sy = pl.pos.y; pl.pos.x = lx; pl.pos.z = lz; pl.pos.y = w.yb + .3; const ly = supportY(pl, MAP.near(lx, lz)); pl.pos.x = sx; pl.pos.z = sz; pl.pos.y = sy; const out = new V3(lx, ly, lz); out.through = true; return out; }
  const blocked = entOverlap(pl, pl.pos.x + fx * .45, y0 + .5, pl.pos.z + fz * .45, near) || rayWorld(pl.pos.x, y0 + 1.0, pl.pos.z, fx || 1e-9, 1e-9, fz || 1e-9, 1.0); return blocked ? best : null; }   // only when something is actually in the way
function curSpread(pl, w) { if (w.melee || w.nade) return .004; const sf = Math.hypot(pl.vel.x, pl.vel.z) / (5.1 * w.speed), settle = w.scope && pl.scoped ? clamp((G.now - (pl.scopeSince ?? -9)) / .38, 0, 1) : 1; let s = w.spread + (w.scope && !pl.scoped ? w.noScope : 0) + (sf > (w.scope ? .12 : .36) ? sf * sf * w.moveSp : 0) + (1 - settle) * .032 + (pl.onGround ? 0 : .08) + Math.min(pl.shots, 14) * w.sprayInc + (pl.ads < .5 ? .006 : 0); if (pl.crouchAmt > 1.5) s *= .55; else if (pl.crouchAmt > .5) s *= .78; if (pl.att && pl.att.stock) s *= .85; return w.pellets ? Math.max(w.spread, s) : s; }
/* Third person: the crosshair is the camera's centre ray; the bullet leaves the eye toward whatever that ray reaches. */
function aimPoint(pl, out) { _ce.set(pl.pitch + pl.recP, pl.yaw + pl.recY, 0); _cq.setFromEuler(_ce); const d = _cv2.set(0, 0, -1).applyQuaternion(_cq), o = camera.position; let t = 260;
  for (const e of G.ents) { if (!e.alive || e === pl) continue; const r = rayEnt(o.x, o.y, o.z, d.x, d.y, d.z, e); if (r && r.t < t) t = r.t; } const h = rayWorld(o.x, o.y, o.z, d.x || 1e-9, d.y || 1e-9, d.z || 1e-9, t); if (h) t = h.t; return out.set(o.x + d.x * t, o.y + d.y * t, o.z + d.z * t); }
function playerFire(pl, w, a) {
  const now = G.now; a.mag--; pl.nextFire = now + w.rate; pl.lastShot = now; const ey = pl.pos.y + eyeY(pl) + pl.stepSmooth, sp = curSpread(pl, w), lx = Math.cos(pl.yaw) * pl.lean * .5, lz = -Math.sin(pl.yaw) * pl.lean * .5;
  const tp = aimPoint(pl, _cv); let py = pl.pitch + pl.recP, yw = pl.yaw + pl.recY; if (pl.ads < .5) { const dx = tp.x - pl.pos.x - lx, dy = tp.y - ey, dz = tp.z - pl.pos.z - lz; yw = Math.atan2(-dx, -dz); py = Math.atan2(dy, Math.hypot(dx, dz)); }
  _ce.set(py, yw, 0); _cq.setFromEuler(_ce); const mz = _cv2.set(.12, -.09, -.75).applyQuaternion(_cq); const mx = pl.pos.x + mz.x, my = ey + mz.y, mzz = pl.pos.z + mz.z;
  fireWeaponVolley(pl, pl.pos.x + lx, ey, pl.pos.z + lz, py, yw, sp, w, mx + lx, my, mzz + lz, pl.ads > .5 || !!pl.att.sup);
  const n = ++pl.shots, c = pl.crouchAmt > .5 ? .8 : 1; const pt = w.pat[Math.min(n - 1, w.pat.length - 1)], gr = (pl.att.grip ? .75 : 1) * (pl.att.comp ? .78 : 1) * (pl.att.stock ? .9 : 1); pl.recTP += pt[0] * c * gr; pl.recTY += (pt[1] + gauss() * w.side * .05) * c * gr; pl.recTP = Math.min(pl.recTP, .24);
  VM.fire(w); G.shake = Math.min(1, G.shake + w.vm * 1.6); if (w.silent) SFX.twang(null); else SFX.shot(pl.att.sup ? 'm4' : w.snd, null, isIndoor(pl)); if (w.bolt || w.crank) SFX.bolt(.32); else if (w.pump) SFX.pump(.28); if (!w.bolt && !w.pellets && (!w.auto || Math.random() < .35)) SFX.shellDrop(1);
  if (pl.model) pl.model.fm.uniforms.uFlash.value = 0; FX.flash(mx, my, mzz, .2);
  botHear(pl.pos, pl.team, w.silent ? 5 : pl.att.sup ? 14 : w.snd === 'm4' ? 22 : 55);
}
function melee(pl, dmg) { const cp = Math.cos(pl.pitch), dx = -Math.sin(pl.yaw) * cp, dy = Math.sin(pl.pitch), dz = -Math.cos(pl.yaw) * cp, ey = pl.pos.y + eyeY(pl); let best = null, be = null;
  for (const e of G.ents) if (e.alive && e.team !== pl.team) { let r = rayEnt(pl.pos.x, ey, pl.pos.z, dx, dy, dz, e); if (r && r.t >= 2.1) r = null;
    if (!r) { const tx = e.pos.x - pl.pos.x, ty = e.pos.y + eyeY(e) * .72 - ey, tz = e.pos.z - pl.pos.z, d = Math.hypot(tx, ty, tz); if (d < 2.2 && (tx * dx + ty * dy + tz * dz) / (d || 1) > .84) r = { t: Math.max(.3, d - .3), part: 'chest' }; }
    if (r && (!best || r.t < best.t)) { best = r; be = e; } }
  const h = rayWorld(pl.pos.x, ey, pl.pos.z, dx, dy, dz, 2.0); if (h && h.s && h.s.glass) { breakGlass(h.s.win, pl); return; } if (be && (!h || h.t > best.t)) { const back = (-Math.sin(be.yaw) * dx - Math.cos(be.yaw) * dz) > .5; hurt(be, dmg * (back ? 3 : 1), pl, 'knife', 'chest', { x: dx, y: dy, z: dz }, { x: pl.pos.x + dx * best.t, y: ey + dy * best.t, z: pl.pos.z + dz * best.t }); G.shake += .15; }
  else if (h) { FX.decal(pl.pos.x + dx * h.t, ey + dy * h.t, pl.pos.z + dz * h.t, h.nx, h.ny, h.nz, .12, INK); SFX.impact(null); } }
function throwNade() {}

/* ---------------- combat ---------------- */
function fireWeaponVolley(sh, ox, oy, oz, pitch, yaw, spread, w, mx, my, mz, noTracer) { for (let i = 0; i < (w.pellets || 1); i++) { const r = spread ? Math.abs(gauss()) * spread * .7 : 0, an = spread ? rand(6.2832) : 0, p = pitch + Math.sin(an) * r, y = yaw + Math.cos(an) * r, cp = Math.cos(p); fireBullet(sh, ox, oy, oz, -Math.sin(y) * cp, Math.sin(p), -Math.cos(y) * cp, w, mx, my, mz, noTracer); } }
function fireBullet(sh, ox, oy, oz, dx, dy, dz, w, mx, my, mz, noTracer) {
  const length = Math.hypot(dx, dy, dz), range = w.range || 260; if (length < 1e-8) return; dx /= length; dy /= length; dz /= length;
  if (w.bolt && typeof botOnShot === 'function') botOnShot(sh, sh.weapon, new V3(ox, oy, oz), new V3(dx, dy, dz));
  dx = dx || 1e-9; dy = dy || 1e-9; dz = dz || 1e-9; let best = null, be = null;
  for (const e of G.ents) { if (!e.alive || e === sh || e.team === sh.team) continue; const r = rayEnt(ox, oy, oz, dx, dy, dz, e); if (r && r.t < range && (!best || r.t < best.t)) { best = r; be = e; } }
  let t0 = 0, mul = 1, endT = range, hitEnt = false;
  for (let pen = 0; pen < 2; pen++) { const h = rayWorld(ox + dx * t0, oy + dy * t0, oz + dz * t0, dx, dy, dz, range - t0); const wt = h ? t0 + h.t : range;
    if (best && best.t < wt && best.t >= t0) { hitEnt = true; endT = best.t; break; } endT = wt; if (!h) break;
    const ix = ox + dx * wt, iy = oy + dy * wt, iz = oz + dz * wt, nx = h.nx, ny = h.ny, nz = h.nz, thin = h.s && (h.tx - h.t) < .5, ex = t0 + h.tx;
    FX.decal(ix, iy, iz, nx, ny, nz, rand(.13, .24) * (w.dmg > 50 ? 1.5 : 1), INK); FX.burst(ix, iy, iz, nx, ny, nz, 4, INK, 2.5, .018); if (sh.isPlayer || Math.random() < .4) SFX.impact({ x: ix, y: iy, z: iz });
    if (thin && w.penetration !== 0 && pen === 0 && ex < range) { mul = w.penetration === undefined ? .55 : w.penetration; t0 = ex + .02; FX.decal(ox + dx * ex, oy + dy * ex, oz + dz * ex, -nx, -ny, -nz, .2, INK); FX.burst(ox + dx * ex, oy + dy * ex, oz + dz * ex, dx, dy, dz, 5, INK, 3, .02); continue; } break; }
  if (!noTracer || !sh.isPlayer) FX.tracer(mx, my, mz, ox + dx * endT, oy + dy * endT, oz + dz * endT);
  if (hitEnt) { const partMul = best.part === 'head' && w.headMult ? w.headMult : best.mul, dmg = w.dmg * partMul * mul * weaponFalloff(w, best.t); if (dmg > 0) hurt(be, dmg, sh, sh.weapon, best.part, { x: dx, y: dy, z: dz }, { x: ox + dx * best.t, y: oy + dy * best.t, z: oz + dz * best.t }); }
}
function hurt(e, dmg, by, wkey, part, dir, pt) {
  if (!e.alive || G.state === 'end') return; const w = wkey ? WEAPONS[wkey] : null, head = part === 'head';
  if (w && e.armor > 0 && part !== 'legs' && (!head || e.helmet)) { const d2 = dmg * (w.arm || .6); e.armor = Math.max(0, e.armor - Math.max(2, dmg - d2)); dmg = d2; }
  if (head && e.helmLv) dmg *= [1, .7, .55, .4][e.helmLv]; dmg = Math.max(1, Math.round(dmg)); e.hp -= dmg; healCancel(e); if (e.armor <= 0 && e.vestLv) { e.vestLv = 0; }
  if (pt && dir) { FX.burst(pt.x, pt.y, pt.z, dir.x, dir.y, dir.z, 6 + Math.min(16, dmg / 5 | 0), RED, 4.5, .03, true); FX.burst(pt.x, pt.y, pt.z, -dir.x, .3, -dir.z, 3, RED, 2, .025, true); SFX.flesh(e.isPlayer ? null : pt);
    const h = rayWorld(pt.x + dir.x * .4, pt.y + dir.y * .4, pt.z + dir.z * .4, dir.x + rand(-.15, .15) || 1e-9, dir.y - .12, dir.z + rand(-.15, .15) || 1e-9, 4.5); if (h) FX.decal(pt.x + dir.x * (.4 + h.t), pt.y + (dir.y - .12) * (.4 + h.t), pt.z + dir.z * (.4 + h.t), h.nx, h.ny, h.nz, rand(.35, .8) * (head ? 1.4 : 1), RED); }
  if (e.isPlayer) { SFX.hurt(); e.punch += .035 + dmg * .0012; G.shake += .25; if (by) G.dmgDirs.push({ x: by.pos.x, z: by.pos.z, t: 1.2 }); G.splats.push({ x: rand(.1, .9), y: rand(.1, .9), s: rand(60, 160) * (1 + dmg / 60), t: 1.6, r: rand(6) }); if (G.splats.length > 8) G.splats.shift(); if (typeof botOnDamage === 'function' && by) {} }
  if (by && !by.isPlayer && by.alive && e.hp - dmg < 55 && e !== by) { by.huntTarget = e; by.huntT = G.now; }
  else { e.flinch = 1; e.hurtT = G.now; e.model.fm.uniforms.uFlash.value = .85; if (typeof botOnDamage === 'function') botOnDamage(e, by, wkey); }
  if (by && by.isPlayer && e !== by) { G.hitT = .22; G.hitKill = e.hp <= 0; head ? SFX.head() : SFX.hit(); if (pt) FX.num(pt, dmg, head); }
  if (e.hp <= 0) kill(e, by, wkey, head, dir);
}
function kill(e, by, wkey, head, dir) {
  if (!e.alive) return; e.alive = false; e.hp = 0; e.deaths++; G.killLog.push([Math.round(G.now), wkey || (ZONE.on && outsideZone(e) ? 'zone' : 'env'), by ? by.name : '-', e.name, e.intent || '', !!e.path, +(e.pos.y - MAP.terrainY(e.pos.x, e.pos.z)).toFixed(1), e.pathFails || 0, ZONE.on ? Math.round(Math.hypot(e.pos.x - ZONE.white.x, e.pos.z - ZONE.white.z) - ZONE.white.r) : 0]); e.deathT = 0; const fl = MAP.floorAt(e.pos.x, e.pos.z); if (e.chute) { scene.remove(e.chute); e.chute = null; } e.air = null; if (e.veh) vehExit(e);
  if (by && by !== e) by.kills++;
  FX.decal(e.pos.x + rand(-.3, .3), Math.abs(e.pos.y - fl) < .4 ? fl : e.pos.y, e.pos.z + rand(-.3, .3), 0, 1, 0, rand(1.3, 2.1), RED, true); FX.burst(e.pos.x, e.pos.y + 1.2, e.pos.z, 0, 1, 0, 14, INK, 3.5, .03);
  addFeed(by, e, wkey, head); if (typeof botOnDeath === 'function') botOnDeath(e, by, wkey); e.act = null; e.killedBy = by && by.isPlayer && WEAPONS[wkey] ? WEAPONS[wkey].name : ''; if (e.inv) crateSpawn(e);
  const f = dir ? (-Math.sin(e.yaw) * dir.x - Math.cos(e.yaw) * dir.z) : -1; e.fallDir = f > 0 ? -1 : 1;
  if (e.isPlayer) { e.scoped = 0; e.ads = 0; G.deathCam = { t: 0, yaw: e.yaw, by }; unlockUI(); $('banner').classList.remove('on'); $('dead').classList.add('on'); $('deadStats').innerHTML = matchStats(); G.killer = by && by !== e ? by : null; $('deadBy').textContent = by && by !== e ? `被 ${by.name} 用 ${WEAPONS[wkey] ? WEAPONS[wkey].name : '环境'} 击杀 · 击杀 ${e.kills} 人` : wkey === null && ZONE.on && outsideZone(e) ? `倒在蓝圈外 · 击杀 ${e.kills} 人` : '你倒下了'; }
  else { e.target = null; e.model.mark.visible = false; }
  if (by && by.isPlayer && e !== by) { SFX.kill(); banner(head ? '爆头击杀' : '击杀', e.name, 'go'); setTimeout(() => $('banner').classList.remove('on'), 900); }
  checkEnd();
}
G.botShoot = (b, dx, dy, dz) => { const w = WEAPONS[b.weapon], ey = b.pos.y + eyeY(b); if (w.crank && b.target) { const d = Math.hypot(b.target.pos.x - b.pos.x, b.target.pos.z - b.pos.z) || 1, p = Math.atan2(dy, Math.hypot(dx, dz)) + Math.atan(.5 * 9.8 * (d / 95) ** 2 / d), yw = Math.atan2(-dx, -dz), cp = Math.cos(p); dx = -Math.sin(yw) * cp; dy = Math.sin(p); dz = -Math.cos(yw) * cp; } const mx = b.pos.x + dx * .8 + Math.cos(b.yaw) * .13, my = ey - .12, mz = b.pos.z + dz * .8 - Math.sin(b.yaw) * .13;
  fireWeaponVolley(b, b.pos.x, ey, b.pos.z, Math.atan2(dy, Math.hypot(dx, dz)), Math.atan2(-dx, -dz), w.pellets ? w.spread : 0, w, mx, my, mz);
  if (w.silent) { SFX.twang(b.pos); botHear(b.pos, b.team, 5); } else { FX.flash(mx, my, mz, .22); SFX.shot(w.snd, b.pos, isIndoor(b)); botHear(b.pos, b.team, 45); } };

/* ---------------- match flow ---------------- */
const TEST_BOTS = 23, BR_NAMES = ['墨鸦', '砚台', '宣纸', '狼毫', '朱砂', '飞白', '留白', '皴法', '勾线', '泼墨', '篆刻', '淡彩', '枯笔', '浓墨', '拓片', '镇纸', '印泥', '走笔', '折锋', '生宣', '熟宣', '焦墨', '藤黄', '花青', '石绿', '赭石', '洒金', '描红'];
function startMatch() { SFX.init();
  for (const b of G.bots) { scene.remove(b.model.root); if (b.chute) scene.remove(b.chute); } G.rank = 0; G.killLog = []; G.watching = false; G.spec = null; G.marker = null; BULLETS.length = 0; smokeClear(); FIRES.length = 0; crateClear(); G.crateOpen = false; $('crate').classList.remove('on'); for (const n of G.nades) scene.remove(n.m); REDZ.on = false; REDZ.next = 110; G.flashT = 0; G.ents = []; G.bots = []; G.feed = []; G.nades = []; G.now = 0; G.botSerial = 0; G.deathCam = null; FX.clearDecals && FX.clearDecals();
  if (G.player) scene.remove(G.player.model.root); const pl = G.player = makePlayer(); G.ents.push(pl); planeStart(); boardPlane(pl); pl.yaw = PLANE.yaw + Math.PI / 2; pl.pitch = -.35; pl.hp = 100;
  pl.cur = 'knife'; switchTo('knife'); VM.drawT = 1; lootPopulate(); vehPopulate(); zoneStart(); setWeather(pick(['clear', 'clear', 'fog', 'dusk'])); G.zoneHurtT = 0;
  G.diff = G.set.diff || 0; const NB = G.set.bots || 23; for (let i = 0; i < NB; i++) { const b = makeBot('red', BR_NAMES[i % BR_NAMES.length], scene); b.team = 'b' + i; G.bots.push(b); G.ents.push(b); const tw = TOWNS[0], p = navRandomIn({ x1: tw.x - 30, x2: tw.x + 30, z1: tw.z - 24, z2: tw.z + 24 }); b.pos.set(p.x, p.y, p.z); b.yaw = rand(6.28); b.hp = 100; b.model.mark.visible = false; invInit(b); b.mags = {}; setEntWeapon(b, 'knife'); b.mag = 0; b.lookYaw = b.yaw; resetBotAwareness && resetBotAwareness(b); boardPlane(b); botPlanDrop(b, i, TEST_BOTS); }
  G.state = 'live'; G.paused = false; for (const id of ['menu', 'dead', 'pause', 'end']) $(id) && $(id).classList.remove('on'); $('hud').classList.add('on'); clearInput(); lock(); banner('升空', '空格 跳伞 · 看准落点', 'go'); setTimeout(() => $('banner').classList.remove('on'), 2400);
}
function checkEnd() { const pl = G.player, alive = G.ents.filter(e => e.alive).length; if (!pl.alive) { if (!G.rank) { G.rank = alive + 1; $('deadT').textContent = `第 ${G.rank} 名`; } if (alive <= 1 && G.state === 'live') { const w = G.ents.find(e => e.alive); $('dead').classList.remove('on'); endMatch(false); $('endT').textContent = w ? (typeof SKIN !== 'undefined' && SKIN.on ? `${w.name} 抢走了今晚的鱼` : `${w.name} 吃到了纸`) : '对局结束'; } return; } if (alive === 1 && G.state === 'live') endMatch(true); }
function matchStats() { const pl = G.player, mine = G.killLog.filter(k => k[2] === pl.name), kv = (k, v) => `<div class="kv"><b>${k}</b><span>${v}</span></div>`, mm = t => `${(t / 60) | 0}:${String((t | 0) % 60).padStart(2, '0')}`; const gear = [pl.helmLv && ITEMS['helm' + pl.helmLv].name, pl.vestLv && ITEMS['vest' + pl.vestLv].name, pl.bagLv && ITEMS['bag' + pl.bagLv].name, pl.scope && ITEMS[pl.scope].name, pl.ghillie && '伪装衣'].filter(Boolean).join(' · ') || '空手';
  return kv('存活', mm(G.now)) + kv('击杀', `${pl.kills} 人`) + mine.map(k => `<div class="kl">${mm(k[0])} · ${k[3]} · ${WEAPONS[k[1]] ? WEAPONS[k[1]].name : k[1]}</div>`).join('') + kv('活到', `第 ${ZONE.on ? ZONE.ph + 1 : 1} 圈`) + kv('装备', gear); }
/* weather: fog thickens the paper haze and shortens bot sight; dusk warms the sheet */
const WEATHER = { clear: { name: '晴', fog: 1, see: 1, tint: 'transparent' }, fog: { name: '雾', fog: 2.6, see: .5, tint: 'rgba(214,212,206,.55)' }, dusk: { name: '黄昏', fog: 1.25, see: .85, tint: 'rgba(233,165,32,.13)' } };
function setWeather(k) { const w = WEATHER[k] || WEATHER.clear; G.weather = k; scene.fog.density = FOG_D * .55 * w.fog; { const seen = new Set(); for (const l of MAP.renderLayers) l.traverse(o => { const m = o.material; if (!m || !m.uniforms || !m.uniforms.uFog || seen.has(m)) return; seen.add(m); if (m.userData.fog0 === undefined) m.userData.fog0 = m.uniforms.uFog.value; m.uniforms.uFog.value = m.userData.fog0 * w.fog; }); } $('weatherOv').style.background = w.tint; G.seeMul = w.see; if (k !== 'clear') { banner(`天气 · ${w.name}`, k === 'fog' ? '视距缩短，听声音' : (typeof SKIN !== 'undefined' && SKIN.on ? '海面镀金' : '纸面泛黄'), 'go'); setTimeout(() => $('banner').classList.remove('on'), 2200); } }
const WIN_LINES = ['墨尽纸白 · 岛上只剩你', '一笔收山 · 纸上称王', '落笔定局 · 这岛归你了', '笔锋未钝 · 全场封喉', '纸短墨长 · 你是最后一划'];
function endMatch(win) { G.state = 'end'; zoneStop(); unlockUI(); const pl = G.player; $('endT').textContent = win ? WIN_LINES[Math.floor(Math.random() * WIN_LINES.length)] : '对局结束'; $('endS').textContent = `第 ${win ? 1 : G.rank || '—'} 名`; $('endStats').innerHTML = matchStats(); $('end').classList.add('on'); if (win) SFX.bell(true); }
function banner(t, s, cls) { const b = $('banner'); b.className = 'on ' + (cls ? 'b-' + cls : ''); $('bannerT').textContent = t; $('bannerS').textContent = s || ''; }
function addFeed(by, e, wkey, head) { G.feed.push({ t: G.now, html: `<span class="${by && by.isPlayer ? 'blue' : 'red'}">${by && by !== e ? by.name : ''}</span> <i>${head ? '◎' : '✕'}</i> <span class="${e.isPlayer ? 'blue' : 'red'}">${e.name}</span>`, me: (by && by.isPlayer) || e.isPlayer }); if (G.feed.length > 6) G.feed.shift(); drawFeed(); }
function drawFeed() { $('feed').innerHTML = G.feed.map(f => `<div class="${f.me ? 'me' : ''}">${f.html}</div>`).join(''); }

/* ---------------- HUD ---------------- */
function updateHUD(dt) { if (((G.frameNo || 0) & 127) === 0 && G.player) invCheck(G.player, 'hud');
  const pl = G.player; _hudT -= dt; if (_hudT <= 0) { _hudT = .1; const a = pl.ammo[pl.cur], w = WEAPONS[pl.cur];
    $('hp').textContent = Math.max(0, Math.ceil(pl.hp)); $('stamBar').style.width = pl.stam + '%'; $('stamBox').hidden = pl.stam >= 99.5; $('hpBar').style.width = clamp(pl.hp, 0, 100) + '%'; $('hpBox').classList.toggle('low', pl.hp <= 30); $('ar').textContent = Math.ceil(pl.armor); $('arBar').style.width = Math.min(100, pl.armor / 70 * 100) + '%';
    $('mag').textContent = a ? a.mag : (w.nade ? pl.nades[pl.cur] : '—'); $('res').textContent = a ? a.res : ''; $('wname').textContent = w.name + (w.auto ? (pl.modes[pl.cur] === 'single' ? ' · 单发' : ' · 连发') : ''); $('wen').textContent = w.en + (pl.att.sup ? ' · SUP' : '') + (pl.att.mag ? ' · +10' : '') + (pl.att.grip ? ' · GRIP' : ''); $('alive').textContent = G.ents.filter(e => e.alive).length; $('kills').textContent = pl.kills; const zl = zoneLabel(); $('timer').textContent = zl[0]; $('phase').textContent = zl[1]; $('timer').classList.toggle('warn', ZONE.on && ZONE.stage === 'shrink'); $('top').classList.toggle('outside', ZONE.on && pl.alive && !pl.air && outsideZone(pl)); $('zone').textContent = MAP.zoneAt(pl.pos.x, pl.pos.z) || '野外';
    $('slots').innerHTML = [[1, pl.inv[1]], [2, pl.inv[2]], [3, 'knife'], ...nadeList(pl).map(k => [4, k])].map(([n, k]) => k ? `<span class="${k === pl.cur ? 'cur' : ''}">${n} ${WEAPONS[k].name.split(' ')[0]}</span>` : '').join('');
    const near = pl.alive && !pl.air ? lootNearList(pl).slice(0, 6) : []; const vn = !near.length && pl.alive && !pl.air && !pl.veh ? vehNear(pl) : null, cr = pl.alive && !pl.air && !pl.veh ? crateNear(pl) : null; $('pickup').innerHTML = cr ? `<div class="near"><b>F</b>打开 ${cr.name} 的箱子<small>${cr.items.filter(i => i.alive).length} 件</small></div>` : pl.veh ? `<div class="near"><b>F</b>下车 · ${pl.veh.t.name} ${Math.round(Math.abs(pl.veh.speed) * 3.6)} km/h</div>` : vn ? `<div class="near"><b>F</b>${vn.flipped ? '扶正' : '驾驶'} ${vn.t.name}</div>` : near.map((it, i) => `<div class="${i ? '' : 'near'}">${i ? '' : '<b>F</b>'}${G.icons && G.icons[it.k] && typeof SKIN !== 'undefined' && SKIN.on ? `<img class="pi" src="${G.icons[it.k]}">` : ''}${ITEMS[it.k].name}${it.qty > 1 ? ' ×' + it.qty : ''}</div>`).join(''); $('gVest').textContent = pl.vestLv ? `甲 ${pl.vestLv} · ${Math.ceil(pl.armor)}` : '甲 —'; $('gHelm').textContent = pl.helmLv ? `盔 ${pl.helmLv}` : '盔 —'; $('gBag').textContent = `包 ${pl.bagLv} · ${invLoad(pl).toFixed(0)}/${BAG_CAP(pl.bagLv)}`; $('gScope').textContent = pl.scope ? ITEMS[pl.scope].name : ''; for (const [kc, mk] of Object.entries(MED_KEYS)) { const el = $('m_' + mk); if (el) { el.lastChild.textContent = pl.meds[mk]; el.classList.toggle('have', pl.meds[mk] > 0); } } $('boostBar').style.width = Math.round(pl.boost) + '%'; $('boostBox').hidden = pl.boost <= 0;
    const hl = pl.heal; $('prog').style.display = hl ? 'block' : 'none'; if (hl) { $('progBar').style.width = Math.round(hl.t / hl.dur * 100) + '%'; $('progLab').textContent = `${ITEMS[hl.k].name} ${Math.ceil(hl.dur - hl.t)}s`; }
    if (G.feed.length && G.now - G.feed[0].t > 6) { G.feed.shift(); drawFeed(); } $('scope').classList.toggle('on', !!(w.scope && pl.scoped && pl.alive && pl.ads > .9));
    $('weaponState').textContent = pl.air === 'plane' ? (planeOverLand() ? '空格 跳伞 · M 看航线' : `气球正在飘向岛屿 · ${Math.max(0, Math.ceil((Math.hypot(PLANE.pos.x, PLANE.pos.z) - MAP.size / 2) / AIR.speed))} s`) : pl.air === 'fall' ? `高度 ${Math.round(pl.agl || 0)} m · 空格 开伞 · 俯视加速` : pl.air === 'chute' ? `高度 ${Math.round(pl.agl || 0)} m · WASD 滑翔` : pl.wet ? '游泳中 · 无法射击' : pl.reloadEnd >= 0 ? `换弹中 ${Math.ceil((pl.reloadEnd - G.now) * 10) / 10}s` : a && a.mag <= Math.ceil(w.mag * .2) ? '余弹不足 · R 换弹' : ''; }
  if (G.flashT > 0) G.flashT -= dt; $('flashOv').style.opacity = clamp((G.flashT || 0) / .9, 0, 1); $('smokeOv').style.opacity = pl.alive ? inSmoke(camera.position) * .93 : 0; $('markerLab').textContent = G.marker && pl.alive ? `标记 ${Math.round(Math.hypot(G.marker.x - pl.pos.x, G.marker.z - pl.pos.z))} m` : '';
  $('captureMouse').hidden = G.noLock || !!document.pointerLockElement || !pl.alive || G.paused || G.state !== 'live';
  drawFx(dt); drawRadar();
}
function drawFx(dt) {
  const g = fxg, R = G.fxDpr || 1, W = fxc.width / R, H = fxc.height / R, pl = G.player, cx = W / 2, cy = H / 2; g.setTransform(1, 0, 0, 1, 0, 0); g.clearRect(0, 0, fxc.width, fxc.height); g.setTransform(R, 0, 0, R, 0, 0);
  for (let i = G.splats.length - 1; i >= 0; i--) { const s = G.splats[i]; s.t -= dt; if (s.t <= 0) { G.splats.splice(i, 1); continue; } g.globalAlpha = Math.min(1, s.t) * .8 * G.set.inkFx; g.fillStyle = UIC('#d42a2a'); const ex = s.x < .5 ? s.x * .3 : 1 - (1 - s.x) * .3, ey = s.y; g.save(); g.translate(ex * W, ey * H); g.rotate(s.r); g.beginPath(); for (let k = 0; k <= 18; k++) { const a = k / 18 * 6.2832, r = s.s * (.6 + .4 * Math.sin(k * 2.7 + s.r * 5) + (k % 3 === 0 ? .5 : 0)); k ? g.lineTo(Math.cos(a) * r, Math.sin(a) * r) : g.moveTo(Math.cos(a) * r, Math.sin(a) * r); } g.fill(); g.restore(); }
  if (ZONE.on && pl.alive && !pl.air && outsideZone(pl)) { const gr = g.createRadialGradient(cx, cy, H * .3, cx, cy, H * .75); gr.addColorStop(0, 'rgba(45,108,179,0)'); gr.addColorStop(1, `rgba(45,108,179,${.3 + (G.zoneHurtT > 0 ? .18 : 0)})`); g.fillStyle = gr; g.fillRect(0, 0, W, H); }
  if (G.burnT > 0 && pl.alive) { g.fillStyle = `rgba(233,165,32,${.18 * G.burnT / .6})`; g.fillRect(0, 0, W, H); }
  g.globalAlpha = 1; if (pl.alive && pl.hp <= 30) { const gr = g.createRadialGradient(cx, cy, H * .35, cx, cy, H * .8); gr.addColorStop(0, 'rgba(212,42,42,0)'); gr.addColorStop(1, `rgba(212,42,42,${(.25 + .1 * Math.sin(G.now * 5)) * G.set.inkFx})`); g.fillStyle = gr; g.fillRect(0, 0, W, H); }
  for (let i = G.dmgDirs.length - 1; i >= 0; i--) { const d = G.dmgDirs[i]; d.t -= dt; if (d.t <= 0) { G.dmgDirs.splice(i, 1); continue; } const a = angDiff(Math.atan2(-(d.x - pl.pos.x), -(d.z - pl.pos.z)), pl.yaw); g.save(); g.translate(cx, cy); g.rotate(-a); g.globalAlpha = Math.min(1, d.t); g.strokeStyle = UIC('#d42a2a'); g.lineWidth = 7; g.beginPath(); g.arc(0, 0, 120, -Math.PI / 2 - .32, -Math.PI / 2 + .32); g.stroke(); g.restore(); }
  g.globalAlpha = 1; g.font = 'bold 17px "IBM Plex Mono", monospace'; g.textAlign = 'center';
  for (const q of FX.nums) { _cv.set(q.x, q.y, q.z).applyMatrix4(camera.matrixWorldInverse); if (_cv.z > -.3) continue; _cv.set(q.x, q.y, q.z).project(camera); g.globalAlpha = 1 - q.t / .9; g.fillStyle = q.head ? UIC('#d42a2a') : UIC('#16161c'); g.fillText((q.head ? '◎ ' : '') + q.val, (_cv.x * .5 + .5) * W, (-_cv.y * .5 + .5) * H); }
  g.globalAlpha = 1; if (pl.alive && G.state === 'live') drawCompass(g, W, pl); if (!pl.alive || G.state !== 'live' || pl.air || pl.veh) return;
  if (!(pl.scoped && WEAPONS[pl.cur].scope && pl.ads > .9)) { const XC = UIC('#16161c'), sz = G.set.xhSize, gap = (4 + (pl.spread || 0) * 900) * sz, L = 8 * sz; g.lineCap = 'butt'; for (const [c, lw] of [[UIC('#f5f2ea'), 5 * sz], [XC, 2.4 * sz]]) { g.strokeStyle = c; g.lineWidth = lw; g.beginPath(); g.moveTo(cx - gap - L, cy); g.lineTo(cx - gap, cy); g.moveTo(cx + gap, cy); g.lineTo(cx + gap + L, cy); g.moveTo(cx, cy - gap - L); g.lineTo(cx, cy - gap); g.moveTo(cx, cy + gap); g.lineTo(cx, cy + gap + L); g.stroke(); } g.fillStyle = UIC('#f5f2ea'); g.fillRect(cx - 2, cy - 2, 4, 4); g.fillStyle = XC; g.fillRect(cx - 1, cy - 1, 2, 2); }
  if (G.hitT > 0) { G.hitT -= dt; const k = G.hitT / .22, r0 = 7 + (1 - k) * 5, r1 = r0 + (G.hitKill ? 11 : 7); g.strokeStyle = G.hitKill ? UIC('#d42a2a') : UIC('#16161c'); g.lineWidth = G.hitKill ? 3 : 2; g.globalAlpha = k; g.beginPath(); for (const [sx, sy] of [[1, 1], [1, -1], [-1, 1], [-1, -1]]) { g.moveTo(cx + sx * r0, cy + sy * r0); g.lineTo(cx + sx * r1, cy + sy * r1); } g.stroke(); g.globalAlpha = 1; }
}
function drawRadar() {
  const g = rg, S = 176, pl = G.player, k = 1.4, ms = MAP.miniScale; g.clearRect(0, 0, S, S); g.save(); g.beginPath(); g.arc(S / 2, S / 2, S / 2 - 2, 0, 6.2832); g.clip(); g.fillStyle = UIC('#f5f2ea'); g.fillRect(0, 0, S, S);
  g.translate(S / 2, S / 2); g.rotate(pl.yaw); g.scale(k / ms, k / ms); g.drawImage(MAP.mini, -(pl.pos.x - MAP.ox) * ms, -(pl.pos.z - MAP.oz) * ms); g.scale(ms / k, ms / k); g.translate(-(pl.pos.x - MAP.ox) * k, -(pl.pos.z - MAP.oz) * k); drawZoneOn(g, k); drawRedOn(g, k); drawVehOn(g, k); drawMarkerOn(g, k); g.restore();
  g.fillStyle = UIC('#16161c'); g.beginPath(); g.moveTo(S / 2, S / 2 - 7); g.lineTo(S / 2 + 5, S / 2 + 5); g.lineTo(S / 2, S / 2 + 2); g.lineTo(S / 2 - 5, S / 2 + 5); g.fill(); g.strokeStyle = UIC('#16161c'); g.lineWidth = 2; g.beginPath(); g.arc(S / 2, S / 2, S / 2 - 2, 0, 6.2832); g.stroke();
}
function bindUI() {
  const seg = (id, key, cast, obj = G.set) => $(id).querySelectorAll('button').forEach(b => { b.classList.toggle('sel', String(obj[key]) === b.dataset.v); b.onclick = () => { $(id).querySelectorAll('button').forEach(x => x.classList.remove('sel')); b.classList.add('sel'); obj[key] = cast(b.dataset.v); saveSet(); SFX.init(); SFX.ui(); }; });
  seg('optDiff', 'diff', Number); seg('optBots', 'bots', Number); seg('optAim', 'aimMode', String); seg('optQ', 'quality', v => { setTimeout(applyQuality, 0); return v; });
  for (const [id, key, fn] of [['sSens', 'sens', v => v], ['sVol', 'vol', v => { SFX.setVol(v); return v; }]]) { const el = $(id), lab = $(id + 'V'); el.value = G.set[key]; lab.textContent = G.set[key]; el.oninput = () => { G.set[key] = fn(+el.value); lab.textContent = el.value; saveSet(); }; }
  $('bigMapC').addEventListener('mousedown', mapClick); $('bigMapC').addEventListener('contextmenu', e => e.preventDefault()); $('inv').addEventListener('click', e => { const m = e.target.closest('[data-more]'); if (m) { m.closest('.it').classList.toggle('open'); return; } const tb = e.target.closest('[data-tab]'); if (tb) { $('inv').classList.toggle('tabB', tb.dataset.tab === 'b'); document.querySelectorAll('.invTabs button').forEach(x => x.classList.toggle('sel', x === tb)); return; } const pl = G.player; if (!pl || !pl.alive) return; const u = e.target.closest('[data-use]'); if (u) { if (healStart(pl, u.dataset.use)) { SFX.click(1200, .2); toggleInv(false); } else SFX.deny(); return; } const g = e.target.closest('[data-g]'); if (g) { const it = G.invGround && G.invGround[+g.dataset.g]; if (it && it.alive && invTake(pl, it)) SFX.click(1400, .2); else SFX.deny(); drawInv(); return; } const b = e.target.closest('[data-k]'); if (b) { if (b.dataset.n ? invDropN(pl, b.dataset.k, +b.dataset.n) : invDrop(pl, b.dataset.k)) { SFX.click(900, .2); drawInv(); } else SFX.deny(); } });
  // drag a row across: ground → body picks up, body → ground drops
  $('inv').addEventListener('dragstart', e => { const tr = e.target.closest('[data-drag]'); if (!tr) return; e.dataTransfer.setData('text/plain', tr.dataset.drag); e.dataTransfer.effectAllowed = 'move'; document.body.classList.add(tr.dataset.drag.startsWith('g:') ? 'dragG' : 'dragB'); }); $('inv').addEventListener('dragend', () => document.body.classList.remove('dragG', 'dragB')); $('inv').addEventListener('dblclick', e => { const tr = e.target.closest('[data-drag]'); const pl = G.player; if (!tr || !pl || !pl.alive) return; const s = tr.dataset.drag; let ok = false; if (s.startsWith('g:')) { const it = G.invGround && G.invGround[+s.slice(2)]; ok = it && it.alive && !!invTake(pl, it); } else ok = invDrop(pl, s.slice(2)); if (ok) SFX.click(1200, .2); else SFX.deny(); drawInv(); }); for (const [id, take] of [['invBag', true], ['invGear', true], ['invG', false]]) { const t = $(id); t.addEventListener('dragover', e => { e.preventDefault(); t.classList.add('over'); }); t.addEventListener('dragleave', () => t.classList.remove('over')); t.addEventListener('drop', e => { e.preventDefault(); t.classList.remove('over'); const s = e.dataTransfer.getData('text/plain'), pl = G.player; if (!pl || !pl.alive) return; let ok = false; if (take && s.startsWith('g:')) { const it = G.invGround && G.invGround[+s.slice(2)]; ok = it && it.alive && !!invTake(pl, it); } else if (!take && s.startsWith('b:')) ok = invDrop(pl, s.slice(2)); if (ok) SFX.click(ok && take ? 1400 : 900, .2); else SFX.deny(); drawInv(); }); }
  $('crateList').addEventListener('click', e => { const b = e.target.closest('button[data-k]'); if (b) crateTakeKind(b.dataset.k); }); $('crateAll').onclick = crateTakeAll; $('crateClose').onclick = crateClose;
  $('deadWatch').onclick = () => { $('dead').classList.remove('on'); G.watching = true; lock(); };
  $('start').onclick = () => startMatch(); if ($('startM')) $('startM').onclick = () => startMatch(); if ($('keysBtn')) { $('keysBtn').onclick = () => { $('keys').classList.add('on'); SFX.ui(); }; $('keysClose').onclick = () => $('keys').classList.remove('on'); } if ($('setBtn')) $('setBtn').onclick = () => { $('devSet').classList.toggle('open'); SFX.ui(); }; $('resume').onclick = () => setPause(false); $('captureMouse').onclick = () => { clearInput(); lock(); };
  $('pauseKeys').onclick = () => { $('keys').classList.add('on'); SFX.ui(); }; $('quit').onclick = () => { if (G.state === 'live' && G.player && G.player.alive && !(G.quitArm > performance.now())) { G.quitArm = performance.now() + 3000; $('quitNote').hidden = false; SFX.ui(); return; } G.state = 'menu'; G.paused = false; for (const id of ['pause', 'hud', 'dead', 'inv', 'bigmap']) $(id).classList.remove('on'); G.invOpen = G.mapOpen = false; $('menu').classList.add('on'); unlockUI(); };
  $('again').onclick = () => { $('dead').classList.remove('on'); startMatch(); }; $('endMenu').onclick = () => $('quit').onclick(); $('endReplay').onclick = () => { SFX.ui(); if (typeof replayStart !== 'function' || !replayStart(G.killer)) SFX.deny(); }; $('endAgain').onclick = () => { $('end').classList.remove('on'); startMatch(); };
}

/* ---------------- camera + frame ---------------- */
const CAM = { dist: 3.0, side: .78, up: .36 };
function updateCamera(dt) {
  const pl = G.player; let fov = G.set.fov; G.shake = damp(G.shake, 0, 9, dt); const motion = G.set.motion, sh = G.shake * .012 * motion;
  if (pl.alive) {
    const ex = pl.pos.x + Math.cos(pl.yaw) * pl.lean * .5, ey = pl.pos.y + eyeY(pl) + pl.stepSmooth, ez = pl.pos.z - Math.sin(pl.yaw) * pl.lean * .5, pitch = pl.pitch + pl.recP + pl.punch * .5 * motion + gauss() * sh + (pl.fp || 0), yaw = pl.yaw + pl.recY + gauss() * sh + (pl.fy || 0);
    // shoulder rig: pivot at the eye, slide back along the look axis, keep clear of walls
    _ce.set(pitch, yaw, 0); _cq.setFromEuler(_ce); const low = clamp((pl.crouchAmt - 1) / 1.7, 0, 1), back = _cv.set(CAM.side + .1 * low, CAM.up + 1.1 * low, (CAM.cur || CAM.dist) + .6 * low).applyQuaternion(_cq); let tx = ex + back.x, ty = ey + back.y, tz = ez + back.z;
    const L = Math.hypot(back.x, back.y, back.z), h = rayWorld(ex, ey, ez, back.x / L || 1e-9, back.y / L || 1e-9, back.z / L || 1e-9, L + .25); if (h) { const k = Math.max(0, h.t - .25) / L; tx = ex + back.x * k; ty = ey + back.y * k; tz = ez + back.z * k; }
    const a = pl.ads; camera.position.set(lerp(tx, ex, a), lerp(ty, ey, a), lerp(tz, ez, a)); camera.rotation.set(pitch, yaw, (pl.roll + pl.punch * .3) * motion - pl.lean * .14);
    if (pl.veh) { const v = pl.veh, cy = pl.yaw + (pl.fy || 0), cp = clamp(pl.pitch + (pl.fp || 0), -.3, 1.2); _ce.set(cp, cy, 0); _cq.setFromEuler(_ce); const back = _cv.set(0, 1.4, 6.5).applyQuaternion(_cq); let bx = v.pos.x + back.x, by = v.pos.y + 1.2 + back.y, bz = v.pos.z + back.z; const L = Math.hypot(back.x, back.y, back.z), h2 = rayWorld(v.pos.x, v.pos.y + 1.2, v.pos.z, back.x / L || 1e-9, back.y / L || 1e-9, back.z / L || 1e-9, L + .3); if (h2) { const kk = Math.max(0, h2.t - .3) / L; bx = v.pos.x + back.x * kk; by = v.pos.y + 1.2 + back.y * kk; bz = v.pos.z + back.z * kk; } camera.position.set(bx, Math.max(by, MAP.sea + .4), bz); camera.rotation.set(cp, cy, v.roll * .3); }
    else if (pl.air === 'plane') { camera.position.set(PLANE.model.position.x - Math.sin(pl.yaw) * 2.9, PLANE.model.position.y + 1.9, PLANE.model.position.z - Math.cos(pl.yaw) * 2.9); camera.rotation.set(pl.pitch, pl.yaw, 0); }   // leaning over the basket rim else if (pl.air) { CAM.cur = damp(CAM.cur || CAM.dist, 5.2, 3, dt); } else CAM.cur = damp(CAM.cur || CAM.dist, CAM.dist, 4, dt);
    if (pl.scoped && a > .5) fov = adsFovFor(pl);
  } else if (G.watching) { const s = G.spec && G.spec.alive ? G.spec : (G.spec = G.bots.find(b => b.alive)); if (s) { const bx = s.pos.x + Math.sin(s.yaw) * 3.2, bz = s.pos.z + Math.cos(s.yaw) * 3.2; _cv.set(bx, s.pos.y + 2.3, bz); camera.position.lerp(_cv, 1 - Math.exp(-6 * dt)); camera.rotation.set(damp(camera.rotation.x, s.pitch - .2, 6, dt), camera.rotation.y + angDiff(s.yaw, camera.rotation.y) * (1 - Math.exp(-6 * dt)), 0); } }
  else if (G.deathCam) { const d = G.deathCam; d.t += dt; const hh = Math.min(3.6, .6 + d.t * 1.6), bx = pl.pos.x + Math.sin(d.yaw) * hh * .8, bz = pl.pos.z + Math.cos(d.yaw) * hh * .8; camera.position.set(bx, pl.pos.y + hh, bz); camera.lookAt(pl.pos.x, pl.pos.y + .3, pl.pos.z); }
  if (Math.abs(camera.fov - fov) > .05) { camera.fov = damp(camera.fov, fov, 22, dt); camera.updateProjectionMatrix(); }
  SFX.L.x = camera.position.x; SFX.L.z = camera.position.z; SFX.L.yaw = camera.rotation.y;
}
function frame(dt) {
  if (G.state === 'menu') { const t = G.now += dt, m = MAP.menuCamera; camera.position.set(m.x + Math.sin(t * .08) * 6, m.y, m.z + Math.cos(t * .08) * 6); camera.lookAt(m.tx, m.ty, m.tz); touchUpdate(); MAP.lod(camera.position.x, camera.position.z); renderer.clear(); renderer.render(scene, camera); return; }
  if (!G.paused) { const sdt = dt * G.timescale; G.now += sdt; G.frameNo = (G.frameNo || 0) + 1; const pl = G.player;
    planeUpdate(sdt); zoneUpdate(sdt); redUpdate(sdt); vehUpdate(sdt); updateBullets(sdt); updateNades(sdt); smokeUpdate(sdt); firesUpdate(sdt); if (pl.alive) updatePlayer(sdt); else animSoldier(pl, sdt); for (const b of G.bots) { if (b.air && b.alive) botAir(b, sdt); else if (b.veh && b.alive) { healUpdate(b, sdt); botDrive(b, sdt); } else { if (b.alive) { healUpdate(b, sdt); botTick(b, G.now); } updateBot(b, sdt, G.now); } } lgFlush(); FX.update(sdt, camera); updateCamera(sdt); VM.update(sdt, pl, WEAPONS[pl.cur], G.mdx, G.mdy); updateHUD(dt);
    G.mdx = G.mdy = 0; G.fireEdge = G.altEdge = false; }
  touchUpdate(); MAP.lod(camera.position.x, camera.position.z); renderer.clear(); renderer.render(scene, camera); if (G.player && G.player.alive && G.player.ads > .85) { renderer.clearDepth(); renderer.render(VM.scene, VM.cam); }
}
window.render_game_to_text = () => JSON.stringify({ state: G.state, now: G.now, player: G.player && { pos: G.player.pos.toArray().map(v => +v.toFixed(2)), hp: G.player.hp, alive: G.player.alive, ads: +G.player.ads.toFixed(2), cur: G.player.cur }, alive: G.ents.filter(e => e.alive).length });
window.advanceTime = ms => { G.manualStep = true; const n = Math.round(ms / 16.67); for (let i = 0; i < n; i++) frame(1 / 60); };
