'use strict';
/* ============ SALTY ISLE · handy: floating item tags (category colour + name + what it means for you), auto-pickup of clearly useful things, H quick heal, the auto-pickup setting ============ */
const HANDY = { tags: [], pool: [], fr: 0, apT: 0, block: [], apNames: [], apT0: 0, _v: new THREE.Vector3() };
(() => { const css = document.createElement('style'); css.textContent = `
#ltags{position:fixed;inset:0;pointer-events:none;z-index:6}
.ltag{position:absolute;left:0;top:0;transform-origin:50% 100%;display:flex;align-items:center;gap:5px;padding:3px 9px 3px 3px;border-radius:999px;background:rgba(255,253,247,.94);border:2px solid #2e3a59;box-shadow:0 2px 0 #2e3a59;font:800 12px/1.1 "PingFang SC","Noto Sans SC",sans-serif;color:#2e3a59;white-space:nowrap;will-change:transform,opacity}
.ltag i{display:inline-grid;place-items:center;width:19px;height:19px;border-radius:50%;background:var(--c);color:#fff;font-style:normal;font-size:11px;font-weight:900;border:1.5px solid #2e3a59}
.ltag img{height:15px;margin:0 1px;filter:drop-shadow(0 1px 0 rgba(46,58,89,.35))}
.ltag s{text-decoration:none;font-weight:700;opacity:.7;font-size:11px}
.ltag em{font-style:normal;font-size:10.5px;font-weight:900;padding:1px 6px;border-radius:999px;background:#e9eef5;color:#2e3a59}
.ltag.up em{background:#33b877;color:#fff}.ltag.no{opacity:.55;filter:saturate(.4)}.ltag.no em{background:#d9d4c8;color:#6b6457}
.ltag kbd{font:900 10px ui-rounded,sans-serif;background:#ffd23f;border:1.5px solid #2e3a59;border-radius:5px;padding:0 4px;margin-left:2px}
.ltag.f{border-color:#ff8a3d;box-shadow:0 2px 0 #ff8a3d,0 0 0 3px rgba(255,138,61,.25)}
#pickup em.tg{font-style:normal;font-size:11px;font-weight:900;margin-left:6px;padding:1px 6px;border-radius:999px;background:#e9eef5;color:#2e3a59}
#pickup em.tg.up{background:#33b877;color:#fff}body.ltOn #pickup .pk{display:none}#pickup em.tg.no{background:#d9d4c8;color:#6b6457}`; document.head.appendChild(css); const d = document.createElement('div'); d.id = 'ltags'; document.body.appendChild(d); })();
function handyTag(i) { while (HANDY.pool.length <= i) { const el = document.createElement('div'); el.className = 'ltag'; el.style.display = 'none'; $('ltags').appendChild(el); HANDY.pool.push(el); } return HANDY.pool[i]; }
function handyPick(pl) { const out = [], cam = camera, v = HANDY._v; cam.updateMatrixWorld(); for (const it of LOOT.items) { if (!it.alive || it.inCrate) continue; const dx = it.x - pl.pos.x, dz = it.z - pl.pos.z; if (Math.abs(dx) > 9 || Math.abs(dz) > 9 || Math.abs(it.y - pl.pos.y) > 2.4) continue; const d = Math.hypot(dx, dz); if (d > 9) continue; v.set(it.x, it.y + .3, it.z).applyMatrix4(cam.matrixWorldInverse); if (v.z > -.3) continue; out.push([d, it]); }
  out.sort((a, b) => a[0] - b[0]); const res = []; const o = cam.position; for (const [d, it] of out) { if (res.length >= 5) break; const tx = it.x - o.x, ty = it.y + .3 - o.y, tz = it.z - o.z, L = Math.hypot(tx, ty, tz); if (L > .5 && typeof rayWorld === 'function') { const h = rayWorld(o.x, o.y, o.z, tx / L, ty / L, tz / L, L); if (h && h.t < L - .45) continue; } res.push(it); } return res; }
function handyTags() { const pl = G.player, on = G.state === 'live' && pl && pl.alive && !pl.air && !pl.veh && !G.paused && $('hud').classList.contains('on') && !document.querySelector('.ov.on:not(#turnPhone)') && !(pl.ads > .5); document.body.classList.toggle('ltOn', !!(on && HANDY.tags.length)); if (!on) { for (const el of HANDY.pool) el.style.display = 'none'; HANDY.tags = []; return; }
  if (HANDY.fr++ % 6 === 0) HANDY.tags = handyPick(pl); const W = innerWidth, H = innerHeight, v = HANDY._v, f = lootNearSorted(pl)[0], placed = []; let n = 0;
  for (const it of HANDY.tags) { if (!it.alive) continue; v.set(it.x, it.y + .42, it.z).project(camera); if (v.z > 1) continue; const x = (v.x * .5 + .5) * W; let y = (-v.y * .5 + .5) * H;
    const el = handyTag(n++), d = ITEMS[it.k], c = LOOT_CAT(it.k), u = lootUse(pl, it), dist = Math.hypot(it.x - pl.pos.x, it.z - pl.pos.z), rk = n - 1, key = it.k + '|' + (it.qty || 1) + '|' + (it.dur ?? '') + '|' + u.tag + '|' + u.ok + '|' + (it === f);
    if (el._k !== key) { el._k = key; const ic = G.icons && G.icons[it.k] ? `<img src="${G.icons[it.k]}">` : ''; el.innerHTML = `<i style="--c:${c[1]}">${c[2]}</i>${ic}<b>${d.name}</b>${it.qty > 1 ? `<s>×${it.qty}</s>` : ''}${it.dur !== undefined ? `<s>耐久 ${Math.ceil(it.dur)}/${d.ap}</s>` : ''}${u.tag ? `<em>${u.tag}</em>` : ''}${it === f ? '<kbd>F</kbd>' : ''}`; el.className = 'ltag' + (u.ok ? (u.up ? ' up' : '') : ' no') + (it === f ? ' f' : ''); } if (el._k2 !== HANDY.fr >> 3) { el._k2 = HANDY.fr >> 3; el.style.display = ''; el._w = el.offsetWidth; el._h = el.offsetHeight; }
    const far = rk >= 6 && it !== f, sc = far ? .85 : Math.max(.82, 1.06 - dist * .03), w = (el._w || 140) * sc, h = (el._h || 26) * sc;
    const hitAt = yy => placed.find(p => x - w / 2 < p[2] + 4 && x + w / 2 > p[0] - 4 && yy - h < p[3] + 4 && yy > p[1] - 4); let hit = hitAt(y); for (let k = 0; k < 6 && hit; k++) { y = hit[1] - 4; hit = hitAt(y); } if (hit) { el.style.display = 'none'; continue; } placed.push([x - w / 2, y - h, x + w / 2, y]);
    el.style.display = ''; el.style.opacity = String(far ? .45 : Math.max(.55, 1 - Math.max(0, dist - 4) * .09)); el.style.zIndex = String(100 - rk); el.style.transform = `translate(${x | 0}px,${y | 0}px) translate(-50%,-100%) scale(${sc.toFixed(2)})`; }
  for (let i = n; i < HANDY.pool.length; i++) HANDY.pool[i].style.display = 'none'; }
function handyAuto(dt) { const pl = G.player; HANDY.apT -= dt; if (HANDY.apT > 0) return; HANDY.apT = .2; if (G.set.autoPick === false || G.state !== 'live' || !pl || !pl.alive || pl.air || pl.veh || G.crateOpen) return;
  HANDY.block = HANDY.block.filter(b => Math.hypot(b.x - pl.pos.x, b.z - pl.pos.z) < 5); for (const it of lootNearList(pl, 1.7)) { if (HANDY.block.some(b => b.k === it.k && Math.hypot(b.x - it.x, b.z - it.z) < 3)) continue; if (!lootUse(pl, it).auto) continue; const r = invTake(pl, it); if (!r) continue; SFX.click(1500, .12); if (G.now - HANDY.apT0 > 1.4) HANDY.apNames = []; HANDY.apT0 = G.now; HANDY.apNames.push(ITEMS[it.k].name + (it.qty > 1 ? '×' + it.qty : '')); { const L = HANDY.apNames; combatNotice('自动拾取 · ' + L.slice(-2).join('、') + (L.length > 2 ? ` 等 ${L.length} 件` : '')); } if (typeof attachVisuals === 'function') attachVisuals(); break; } }
function quickHeal() { const pl = G.player; if (!pl || !pl.alive || pl.heal || G.state !== 'live') return; const hp = pl.hp, order = hp <= 45 ? ['medkit', 'kit', 'band'] : hp < 75 ? ['kit', 'band', 'medkit'] : hp < 100 ? ['medkit'] : []; if (pl.boost < 60) order.push('drink', 'pill', 'adren'); for (const k of order) if (pl.meds[k] && healStart(pl, k)) { combatNotice('快速治疗 · ' + ITEMS[k].name); return; } SFX.deny(); combatNotice(hp >= 100 ? '满血 · 不用吃药' : '没有合适的药'); }
(() => { const _f = frame; frame = function (dt) { _f(dt); handyAuto(dt); handyTags(); document.body.classList.toggle('inMatch', G.state === 'live'); if ((G.set.quality === 'low') === renderer.shadowMap.enabled) applyQuality(); if (SKIN.nearMats) { const pl = G.player, v = pl && pl.alive && (pl.ads || 0) > .5 ? 0 : 1; for (const m of SKIN.nearMats) m.uniforms.uNear.value = v; } };
  const _d = invDrop, _dn = invDropN; invDrop = function (e, k) { const r = _d(e, k); if (r && e && e.isPlayer) HANDY.block.push({ k, x: e.pos.x, z: e.pos.z }); return r; }; invDropN = function (e, k, n) { const r = _dn(e, k, n); if (r && e && e.isPlayer) HANDY.block.push({ k, x: e.pos.x, z: e.pos.z }); return r; };
  document.addEventListener('keydown', e => { if (e.code === 'KeyH' && !e.repeat && G.state === 'live' && !G.paused && !(e.target && /INPUT|TEXTAREA/.test(e.target.tagName))) quickHeal(); });
  const ds = $('devSet'); if (ds) { const o = document.createElement('div'); o.className = 'opt'; o.innerHTML = '<label>自动拾取</label><div id="optAuto" class="seg"><button data-v="1">开</button><button data-v="0">关</button></div>'; ds.appendChild(o); const sync = () => o.querySelectorAll('button').forEach(b => b.classList.toggle('sel', (b.dataset.v === '1') === (G.set.autoPick !== false))); sync(); o.addEventListener('click', ev => { const b = ev.target.closest('button'); if (!b) return; G.set.autoPick = b.dataset.v === '1'; saveSet(); sync(); SFX.ui(); }); }
  if (/[?&]go(&|$)/.test(location.search)) setTimeout(() => { const b = $('start'); if (b && G.state === 'menu') b.dispatchEvent(new MouseEvent('click', { bubbles: true })); }, 2500);
  /* phones in portrait: the HUD is laid out for landscape, so a sticker card asks to turn the phone while a match is running */
  { const css = document.createElement('style'); css.textContent = `#turnPhone{display:none;position:fixed;inset:0;z-index:20;align-items:center;justify-content:center;background:rgba(159,211,236,.92);padding:24px}
#turnPhone div{background:#fff8ec;border:3px solid #2e3a59;border-radius:22px;box-shadow:0 7px 0 #2e3a59;padding:26px 24px 22px;text-align:center;max-width:320px;font-family:"LXGW WenKai","PingFang SC",sans-serif;color:#2e3a59}
#turnPhone b{display:block;font:400 34px/1.2 "Ma Shan Zheng","LXGW WenKai",serif;color:#ffd23f;-webkit-text-stroke:.11em #2e3a59;paint-order:stroke fill;text-shadow:0 .08em 0 #2e3a59;margin:10px 0 6px}
#turnPhone i{display:inline-block;width:64px;height:40px;border:4px solid #2e3a59;border-radius:10px;background:#2fa6a0;animation:tp 1.6s ease-in-out infinite}
@keyframes tp{0%,30%{transform:rotate(-90deg)}60%,100%{transform:rotate(0)}}
@media (orientation:portrait) and (max-width:820px){body.touch.inMatch #turnPhone{display:flex}}`; document.head.appendChild(css); const d = document.createElement('div'); d.id = 'turnPhone'; d.innerHTML = '<div><i></i><b>把手机横过来</b>咸鱼也要侧着身子游<br>横屏才能看清整片海</div>'; document.body.appendChild(d); }
  /* every full-screen panel gets a round × (phones have no Tab / M key, and the touch layer ignores touches while a panel is open) */
  for (const [id, close] of [['inv', () => toggleInv(false)], ['bigmap', () => toggleMap(false)], ['crate', () => crateClose()]]) { const pan = document.querySelector('#' + id + ' .panel'); if (!pan || pan.querySelector('.ecX')) continue; pan.style.position = 'relative'; const x = document.createElement('button'); x.className = 'ecX'; x.title = '关闭'; x.textContent = '×'; x.style.zIndex = '3'; pan.appendChild(x); x.addEventListener('click', ev => { ev.stopPropagation(); close(); if (typeof lock === 'function' && !('ontouchstart' in window)) lock(); SFX.ui(); }); }
  /* phones start on the light preset (unless the player picked one); the light preset also drops the sun's shadow pass */
  try { const saved = JSON.parse(localStorage.getItem('inkisland') || '{}'); if (saved.quality === undefined && (matchMedia('(pointer: coarse)').matches || /[?&]touch/.test(location.search))) G.set.quality = 'low'; } catch (er) { }
  { const _aq = applyQuality; applyQuality = function () { _aq(); const on = G.set.quality !== 'low'; if (renderer.shadowMap.enabled !== on) { renderer.shadowMap.enabled = on; if (typeof SKIN !== 'undefined' && SKIN.sun) SKIN.sun.castShadow = on; if (typeof FILL_MATS !== 'undefined') for (const m of FILL_MATS) m.needsUpdate = true; } }; }
  /* d30 actor LOD for 50-player matches: bots beyond 70 m animate every other frame, beyond 150 m on the light preset they are not drawn (position still follows) */
  { const _an = animSoldier; let fN = 0; animSoldier = function (e, dt) { if (e.isPlayer || !e.model || typeof camera === 'undefined') return _an(e, dt); const m = e.model, d2 = (e.pos.x - camera.position.x) ** 2 + (e.pos.z - camera.position.z) ** 2;
      if (e.alive && G.set.quality === 'low' && d2 > 150 * 150 && !e.air) { m.root.visible = false; m.lodHid = true; m.root.position.copy(e.pos); return; } if (m.lodHid) { m.lodHid = false; m.root.visible = true; }
      if (e.alive && d2 > 70 * 70 && !e.veh && !e.air) { m.lodAcc = (m.lodAcc || 0) + dt; if ((++m.lodN & 1) === 1 || isNaN(m.lodN)) { m.lodN = m.lodN || 1; m.root.position.copy(e.pos); m.root.rotation.y = e.yaw; return; } const t = m.lodAcc; m.lodAcc = 0; return _an(e, t); } return _an(e, dt); }; }
  const hp = $('help'); if (hp) hp.textContent = hp.textContent.replace('F 拾取/上车/开箱', 'F 拾取/上车/开箱 · H 快速治疗 · 有用的东西自动捡');
})();
