'use strict';
/* ============ INK ISLAND · ladder: iron rungs up the outside of flat roofs. The player climbs with W/S (Space lets go); a bot treats the roof as one more floor whose stair happens to be vertical ============ */
const LADDER = { spd: 2.1, botSpd: 2.4 };
/* the ladder a body could take right now: at its foot (within a metre, standing on the ground) or at its top (on the roof, by the parapet). `want` is +1 for up, -1 for down, 0 for either */
function ladderNear(e, want = 0) { const L = MAP.ladders; if (!L) return null; for (let i = 0; i < L.length; i++) { const l = L[i]; if (want >= 0 && Math.abs(e.pos.y - l.y1) < 1.0 && Math.hypot(e.pos.x - l.x, e.pos.z - l.z) < 1.1) return { l, dir: 1 }; if (want <= 0 && Math.abs(e.pos.y - l.y2) < .8 && Math.hypot(e.pos.x - l.top.x, e.pos.z - l.top.z) < 1.2) return { l, dir: -1 }; } return null; }
function climbStart(e, l, dir) { e.climb = { l, dir, lock: dir < 0 && e.isPlayer }; e.vel.set(0, 0, 0); e.onGround = false; e.prone = false; e.sprint = false; e.ads = 0; if (dir > 0) { e.pos.x = l.x; e.pos.z = l.z; } else { e.pos.x = l.x; e.pos.z = l.z; e.pos.y = l.y2 + .02; } e.yaw = l.yaw; e.stuckT = 0; e.hgt = 1.8; e.crouchAmt = 0; if (e.isPlayer) e.spaceHeld2 = true; if (e.model) e.model.gun.visible = false; SFX.swish && SFX.swish(); }
function climbDrop(e) { if (!e.climb) return; e.climb = null; e.onGround = false; if (e.model) e.model.gun.visible = true; }
function climbEnd(e, atTop) { const l = e.climb.l; e.climb = null; e.vel.set(0, 0, 0); e.onGround = true; if (atTop) { e.pos.set(l.exit.x, l.exit.y, l.exit.z); } else { e.pos.x = l.x; e.pos.z = l.z; e.pos.y = Math.max(l.y1, MAP.floorAt(l.x, l.z)); } if (e.model) e.model.gun.visible = true; if (!e.isPlayer && e.path) { const n = e.path[e.pi]; if (n && Math.hypot(n.x - e.pos.x, n.z - e.pos.z) < 1.4) e.pi++; } SFX.step(e.isPlayer ? null : e.pos, .22); }
/* one frame on the rungs: the body stays on the ladder column, moves only in y; a bot always heads for its waypoint, the player for whichever way W/S says */
function climbUpdate(e, dt) { const c = e.climb, l = c.l, dir = e.isPlayer ? c.dir : c.dir, sp = e.isPlayer ? LADDER.spd : LADDER.botSpd; e.pos.x = l.x; e.pos.z = l.z; e.vel.set(0, 0, 0); e.onGround = false; e.hitWall = false; e.landed = 0; e.stuckT = 0; e.crouchAmt = damp(e.crouchAmt, 0, 12, dt); if (e.isPlayer) e.yaw = l.yaw + clamp(angDiff(e.yaw, l.yaw), -1, 1); else e.yaw = l.yaw;
  if (dir) { e.pos.y += dir * sp * dt; c.phase = (c.phase || 0) + sp * dt; } if (e.pos.y >= l.y2 + .02) { if (dir > 0 || (!e.isPlayer && dir >= 0)) climbEnd(e, true); else e.pos.y = l.y2 + .02; } else if (e.pos.y <= l.y1) { if (dir < 0 || (!e.isPlayer && dir <= 0)) climbEnd(e, false); else e.pos.y = l.y1; } }
/* the pose: hands and feet on alternate rungs, body hugging the wall, gun put away */
function climbPose(e) { const m = e.model, c = e.climb; if (!m || !c) return; const ph = (c.phase || 0) * 2.6, a = Math.sin(ph), b = Math.sin(ph + Math.PI); m.root.position.copy(e.pos); m.root.rotation.set(0, e.yaw, 0); m.upper.rotation.set(-.18, 0, 0); m.head.rotation.set(-.55 * (c.dir >= 0 ? 1 : -.4), 0, 0); m.armR.rotation.set(-2.75 + a * .25, .15, -.18); m.armL.rotation.set(-2.75 + b * .25, -.15, .18);
  for (const [L, s] of [[m.legL, a], [m.legR, b]]) { L.rotation.set(-.75 - s * .45, 0, 0, 'ZXY'); L.shin.rotation.x = 1.25 + s * .45; L.foot.rotation.set(-.5, 0, 0, 'XZY'); } m.gun.visible = false; }
(() => { const _move = moveEntity, _anim = animSoldier, _up = updatePlayer, _hud = updateHUD, _kill = kill;
  kill = function (e, by, wkey, head, dir) { if (e && e.climb) climbDrop(e); return _kill(e, by, wkey, head, dir); };
  moveEntity = function (e, dt) { if (e.climb) return climbUpdate(e, dt); if (!e.isPlayer && e.alive && e.path && !e.air && !e.veh) { const n = e.path[e.pi]; if (n && n.y !== undefined) { const dy = n.y - e.pos.y; if (dy > 1.5) { const r = ladderNear(e, 1); if (r && Math.abs(r.l.y2 - n.y) < 1.2) { climbStart(e, r.l, 1); return; } } else if (dy < -1.5) { const r = ladderNear(e, -1); if (r && Math.abs(r.l.y1 - n.y) < 1.8) { climbStart(e, r.l, -1); return; } } } } return _move(e, dt); };
  animSoldier = function (e, dt) { _anim(e, dt); if (e.climb && e.alive) climbPose(e); };
  updatePlayer = function (dt) { const pl = G.player, k = G.keys; if (pl.climb) { if (!pl.alive || G.state !== 'live') { climbDrop(pl); return _up(dt); } const c = pl.climb; if (c.lock && !k.KeyW) c.lock = false; c.dir = G.paused ? 0 : (k.KeyW && !c.lock ? 1 : 0) - (k.KeyS ? 1 : 0); if (k.Space && !pl.spaceHeld2) { pl.spaceHeld2 = true; const l = c.l; climbDrop(pl); pl.vel.set(Math.sin(l.yaw) * 1.6, 1.2, Math.cos(l.yaw) * 1.6); } if (!k.Space) pl.spaceHeld2 = false; healUpdate(pl, dt); pl.ads = damp(pl.ads, 0, 14, dt); pl.lean = damp(pl.lean, 0, 10, dt); pl.fy = damp(pl.fy || 0, 0, 12, dt); pl.fp = damp(pl.fp || 0, 0, 12, dt); if (pl.climb) { climbUpdate(pl, dt); animSoldier(pl, dt); pl.model.root.visible = true; return; } }
    if (pl.alive && G.state === 'live' && !G.paused && !pl.air && !pl.veh && !pl.mantle && !pl.act && !pl.heal && k.KeyW && pl.onGround && !pl.prone) { const r = ladderNear(pl); if (r) { const fx = -Math.sin(pl.yaw), fz = -Math.cos(pl.yaw), wx = -Math.sin(r.l.yaw), wz = -Math.cos(r.l.yaw), face = r.dir > 0 ? fx * wx + fz * wz : -(fx * wx + fz * wz); if (face > .5) { climbStart(pl, r.l, r.dir); animSoldier(pl, dt); return; } } }
    return _up(dt); };
  updateHUD = function (dt) { _hud(dt); const pl = G.player; if (!pl || !pl.alive || G.state !== 'live') return; const el = $('pickup'); if (pl.climb) { el.innerHTML = '<div class="near"><b>W</b>上 · <b>S</b>下 · 空格松手</div>'; return; } if (!el.innerHTML && !pl.air && !pl.veh) { const r = ladderNear(pl); if (r) { const f = (-Math.sin(pl.yaw)) * (-Math.sin(r.l.yaw)) + (-Math.cos(pl.yaw)) * (-Math.cos(r.l.yaw)); if ((r.dir > 0 ? f : -f) > .5) el.innerHTML = `<div class="near"><b>W</b>${r.dir > 0 ? '上梯' : '下梯 · 然后按 S 下行'}</div>`; } } };
})();
