'use strict';
/* ============ INK ISLAND · replay: the last eight seconds before you fell, seen from the killer's eyes ============ */
const REPLAY = { buf: [], max: 160, acc: 0, on: false, i: 0, t: 0, from: null, saved: null };
function replayRecord(dt) { if (G.state !== 'live' || REPLAY.on || (!G.player.alive && G.player.deathT > 1)) return; REPLAY.acc += dt; if (REPLAY.acc < .05) return; REPLAY.acc = 0; const pl = G.player, f = { t: G.now, p: [pl.pos.x, pl.pos.y, pl.pos.z, pl.yaw, pl.pitch, pl.crouchAmt, pl.alive ? 1 : 0], b: [] }; for (const b of G.bots) f.b.push(b.alive ? [b.pos.x, b.pos.y, b.pos.z, b.yaw, b.pitch, b.crouchAmt] : null); REPLAY.buf.push(f); if (REPLAY.buf.length > REPLAY.max) REPLAY.buf.shift(); }
function replayClear() { REPLAY.buf.length = 0; REPLAY.acc = 0; REPLAY.kill = null; replayKillLine(false); }
/* start: freeze the match, remember where everyone stands, then play the buffer back at real speed through the killer's eyes (or the player's own if nobody killed them) */
function replayStart(killer) { if (REPLAY.on || REPLAY.buf.length < 10) return false; const pl = G.player; REPLAY.on = true; REPLAY.i = 0; REPLAY.t = 0; REPLAY.from = killer && killer.alive && G.bots.includes(killer) ? G.bots.indexOf(killer) : -1;
  REPLAY.saved = { deathT: pl.deathT, rx: pl.model.root.rotation.x, p: [pl.pos.clone(), pl.yaw, pl.pitch, pl.crouchAmt], b: G.bots.map(b => [b.pos.clone(), b.yaw, b.pitch, b.crouchAmt, b.model.root.rotation.x]) }; $('dead').classList.remove('on'); $('hud').classList.remove('on'); $('replayTag').classList.add('on'); $('replayTxt').textContent = (REPLAY.from >= 0 ? `回放 · ${G.bots[REPLAY.from].name} 的视角` : '回放 · 你的视角') + ' · 点此跳过'; unlockUI(); return true; }
function replayStop() { if (!REPLAY.on) return; const s = REPLAY.saved, pl = G.player; pl.pos.copy(s.p[0]); pl.yaw = s.p[1]; pl.pitch = s.p[2]; pl.crouchAmt = s.p[3]; G.bots.forEach((b, i) => { b.pos.copy(s.b[i][0]); b.yaw = s.b[i][1]; b.pitch = s.b[i][2]; b.crouchAmt = s.b[i][3]; if (!b.alive) { b.model.root.visible = b.deathT < 14; b.model.root.rotation.x = s.b[i][4]; } }); pl.deathT = s.deathT; pl.model.root.rotation.x = s.rx; replayKillLine(false); REPLAY.on = false; REPLAY.saved = null; $('replayTag').classList.remove('on'); if (G.state === 'live') $('hud').classList.add('on'); if (!pl.alive && G.state === 'live' && !G.watching) $('dead').classList.add('on'); }
/* the shot that dropped you: remembered at the moment of death, drawn as a red ink line once the tape reaches it; the tape crawls at .3× around that moment */
function replayKillLine(show) { if (!REPLAY.kill) return; if (show && !REPLAY.line) { const k = REPLAY.kill, g = new LineSegmentsGeometry(); g.setPositions([k.from[0], k.from[1], k.from[2], k.to[0], k.to[1], k.to[2]]); REPLAY.line = new LineSegments2(g, lineMat({ width: 3, color: RED, fog: false, depthTest: false })); REPLAY.line.frustumCulled = false; REPLAY.line.renderOrder = 5; scene.add(REPLAY.line); $('replayTxt').textContent = `${REPLAY.kill.who} · ${WEAPONS[REPLAY.kill.w] ? WEAPONS[REPLAY.kill.w].name : ''} · ${Math.round(REPLAY.kill.dist)} m · ${REPLAY.kill.head ? '爆头' : '命中'} · 点此跳过`; } if (!show && REPLAY.line) { scene.remove(REPLAY.line); REPLAY.line.geometry.dispose(); REPLAY.line = null; } }
function replayFrame(dt) { if (G.state !== 'live') return replayStop(); const B = REPLAY.buf; const kAt = REPLAY.kill ? REPLAY.kill.t - B[0].t : -1, slow = REPLAY.kill && REPLAY.t > kAt - 1.3 && REPLAY.t < kAt + .6; REPLAY.t += dt * (slow ? .3 : 1); if (REPLAY.kill && REPLAY.t >= kAt) replayKillLine(true); while (REPLAY.i < B.length - 1 && B[REPLAY.i + 1].t - B[0].t <= REPLAY.t) REPLAY.i++; const f = B[REPLAY.i], g = B[Math.min(B.length - 1, REPLAY.i + 1)], u = g.t > f.t ? clamp((REPLAY.t - (f.t - B[0].t)) / (g.t - f.t), 0, 1) : 0, L = (a, b) => a + (b - a) * u;
  const pl = G.player; pl.pos.set(L(f.p[0], g.p[0]), L(f.p[1], g.p[1]), L(f.p[2], g.p[2])); pl.yaw = f.p[3] + angDiff(g.p[3], f.p[3]) * u; pl.pitch = L(f.p[4], g.p[4]); pl.crouchAmt = L(f.p[5], g.p[5]); { const a = pl.alive; pl.alive = true; pl.model.root.rotation.x = 0; animSoldier(pl, dt); pl.alive = a; } pl.model.root.visible = true;
  G.bots.forEach((b, i) => { const a = f.b[i], c = g.b[i] || a; if (!a) { b.model.root.visible = false; return; } b.model.root.visible = true; b.pos.set(L(a[0], c[0]), L(a[1], c[1]), L(a[2], c[2])); b.yaw = a[3] + angDiff(c[3], a[3]) * u; b.pitch = L(a[4], c[4]); b.crouchAmt = L(a[5], c[5]); const alive = b.alive; b.alive = true; b.model.root.rotation.x = 0; animSoldier(b, dt); b.alive = alive; });
  const k = REPLAY.from >= 0 ? G.bots[REPLAY.from] : pl, eye = REPLAY.from >= 0 && f.b[REPLAY.from] ? k : pl, ey = eye.pos.y + eyeY(eye), back = eye === pl ? 2.6 : 2.0, side = .7; camera.position.set(eye.pos.x + Math.sin(eye.yaw) * back + Math.cos(eye.yaw) * side, ey + .35, eye.pos.z + Math.cos(eye.yaw) * back - Math.sin(eye.yaw) * side); camera.rotation.set(eye.pitch, eye.yaw, 0, 'YXZ'); camera.fov = G.set.fov; camera.updateProjectionMatrix();
  FX.update(dt, camera); MAP.lod(camera.position.x, camera.position.z); renderer.clear(); renderer.render(scene, camera); $('replayBar').style.width = Math.round(REPLAY.t / (B[B.length - 1].t - B[0].t) * 100) + '%'; if (REPLAY.i >= B.length - 1) replayStop(); }
(() => { const _frame = frame, _hud = updateHUD, _start = startMatch, _hurt = hurt;
  hurt = function (e, dmg, by, wkey, part, dir, pt) { const was = e && e.alive; _hurt(e, dmg, by, wkey, part, dir, pt); if (was && e && e.isPlayer && !e.alive && by && by !== e && pt && wkey && WEAPONS[wkey] && !WEAPONS[wkey].nade && !WEAPONS[wkey].melee) { const fy = by.pos.y + eyeY(by); REPLAY.kill = { t: G.now, from: [by.pos.x, fy, by.pos.z], to: [pt.x, pt.y, pt.z], w: wkey, who: by.name, head: part === 'head', dist: Math.hypot(by.pos.x - pt.x, fy - pt.y, by.pos.z - pt.z) }; } };
  frame = function (dt) { if (REPLAY.on) return replayFrame(dt); return _frame(dt); };
  updateHUD = function (dt) { replayRecord(dt); return _hud(dt); };
  startMatch = function () { if (REPLAY.on) replayStop(); replayClear(); return _start(); };
  const btn = $('deadReplay'); if (btn) btn.onclick = () => { SFX.ui(); if (!replayStart(G.killer)) SFX.deny(); }; $('replayTag').onclick = () => replayStop(); const q = $('quit'); if (q) q.addEventListener('click', () => replayStop());
  addEventListener('keydown', e => { if (REPLAY.on && (e.code === 'Escape' || e.code === 'Space')) { e.preventDefault(); e.stopImmediatePropagation(); replayStop(); } }, { capture: true });
  addEventListener('mousedown', e => { if (REPLAY.on && !(e.target.closest && e.target.closest('button,.ov'))) { e.stopImmediatePropagation(); replayStop(); } }, { capture: true });
})();
/* far gunfire: beyond 120 m a shot is not a crack but a dull thump that arrives late and tells you roughly where */
(() => { const _shot = SFX.shot.bind(SFX);
  SFX.shot = function (kind, pos, indoor) { if (!this.ctx || !pos || !this.L) return _shot(kind, pos, indoor); const d = Math.hypot(pos.x - this.L.x, pos.z - this.L.z); if (d < 100) return _shot(kind, pos, indoor); const k = clamp((d - 100) / 60, 0, 1), p = this.SHOT[kind] || this.SHOT.rifle;
    if (k < 1) { const g0 = p.gain; p.gain = g0 * (1 - k); try { _shot(kind, pos, indoor); } finally { p.gain = g0; } }
    const near = 1 / (1 + Math.pow(100 / 10, 1.7)), comp = (1 + Math.pow(d / 10, 1.7)) * near * 1.6 / (1 + Math.pow((d - 100) / 170, 2)), o = this.out(pos, p.gain * .55 * comp * k, .9), delay = Math.max(0, Math.min(1.2, d / 340) - this.dly); this.noise(.14 + p.thump[3], 340, 80, 1.1, o, 'lowpass', .7, delay); this.tone(Math.max(50, p.thump[1] * .6), 40, .4, .7, o, 'sine', delay); this.noise(.04, 900, 400, .18, o, 'bandpass', 2, delay); };
})();
