'use strict';
/* ============ INK ISLAND · skin: the harbour-afternoon colour skin (palette of concept 5, scene language of concept 7). Flat colour + three-step toon light, indigo shadows, faint lines ============ */
const SKIN = { on: true, c: {
  sky: 0x9fd3ec, horizon: 0xdceff4, ink: 0x2e3a59, shadow: 0x3b4a72,
  grass: 0x7cc47f, grass2: 0x62b56e, sand: 0xe2cf92, rock: 0xc4bba8, shallow: 0x5fd2d0, deep: 0x1c6fb0, sea: 0x2a84c7, foam: 0xd8f4f8,
  cream: 0xf6f1e4, wood: 0xc99a62, glass: 0x9fd8e8, grey: 0x8c9ba8,
  coral: 0xff5a4e, sun: 0xffd23f, indigo: 0x2e3a59, teal: 0x2fa6a0,
  walls: [0xf7f2e6, 0xfff8ec, 0xe8f1ec, 0xf4e6cf, 0xe9eef5], roofs: [0x2e3a59, 0xff5a4e, 0xffd23f, 0x2fa6a0, 0x3a5a8c, 0xd94c3d],
  trunk: 0x8a5f3c, leaf: 0x3f9d63, leaf2: 0x58b872, palm: 0x4fae6a,
  cloth: 0x2e3a59, clothBot: 0x6f7f6a, skin: 0xe9b97a, hat: 0xc9a05a, pack: 0x7a5a3a,
  jeep: 0x6b7a4a, boat: 0xf2e7d0, moto: 0x2e3a59,
  grass3: 0x95d18a, dry: 0xa9c46f, wet: 0xd4c48f, dirt: 0xd6c48e, leaves: [0x3f9d63, 0x58b872, 0x2f8f5b, 0x8fc96a, 0x6fb35a, 0x4a9e5c], bushes: [0x4fae6a, 0x7cc47f, 0x3f9d63, 0x8fc96a], flowers: [0xff5a4e, 0xffd23f, 0xffffff, 0xff8fb0, 0x9fd8e8], frond: 0x4fae6a, coconut: 0x8a5f3c,
  trims: [0xfffdf7, 0xff5a4e, 0x2fa6a0, 0xffd23f, 0x2e3a59, 0xfffdf7], doors: [0xff5a4e, 0x2fa6a0, 0xffd23f, 0x2e3a59, 0xd94c3d, 0x8a5f3c], props: [0x2fa6a0, 0xff5a4e, 0xffd23f, 0x2e3a59, 0x8c9ba8], sandbag: 0xc9b98a, cloud: 0xffffff } };
SKIN.dark = (hex, k = .82) => { const c = new THREE.Color(hex); c.multiplyScalar(k); return c.getHex(); };
/* the paper palette is remapped at bake time: every PAPER surface becomes cream, every WOOD surface warm wood, etc. */
SKIN.map = { [PAPER]: SKIN.c.cream, [WOOD]: SKIN.c.wood, [GLASS]: SKIN.c.glass, [GREY]: SKIN.c.grey, [RED]: SKIN.c.coral, [AMBER]: SKIN.c.sun, [BLUE]: 0x2e6fa8 };
SKIN.remap = t => SKIN.on && SKIN.map[t] !== undefined ? SKIN.map[t] : t;
SKIN.pickR = (R, arr) => arr[Math.floor(R() * arr.length) % arr.length];
/* the sky: a screen-fixed vertical gradient (cheap, phones included) plus matching fog and clear colour */
function skinSky() { const c = document.createElement('canvas'); c.width = 4; c.height = 256; const g = c.getContext('2d'), gr = g.createLinearGradient(0, 0, 0, 256); const h = x => '#' + x.toString(16).padStart(6, '0'); gr.addColorStop(0, h(SKIN.c.sky)); gr.addColorStop(.62, h(SKIN.c.horizon)); gr.addColorStop(1, h(SKIN.c.horizon)); g.fillStyle = gr; g.fillRect(0, 0, 4, 256); const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.LinearSRGBColorSpace; return t; }
/* clouds: a dozen clusters of flattened spheres high over the sea, lit by the same toon light; a pale sun disc where the light comes from */
function skinClouds() { const s = new Sk('none'), R = rng(99); for (let i = 0; i < 16; i++) { const a = R() * 6.2832, r = 260 + R() * 420, cx = Math.cos(a) * r, cz = Math.sin(a) * r, cy = 150 + R() * 60, n = 3 + Math.floor(R() * 4), w = 18 + R() * 26; for (let k = 0; k < n; k++) { const rad = 10 + R() * 12; s.add(new THREE.SphereGeometry(rad, 10, 7).scale(1.5 + R() * .7, .6 + R() * .2, 1.2 + R() * .4), new THREE.Matrix4().makeTranslation(cx + (R() - .5) * w * .7, cy + (R() - .5) * 4, cz + (R() - .5) * w * .4), { tint: SKIN.c.cloud, tone: 0, edges: false }); } }
  const cm = fillMat({ fog: .0007 }); cm.uniforms.uShadow.value.set(0xe3ecf4); const g = s.bake(cm, lineMat({ width: 1 })); g.traverse(o => { o.frustumCulled = false; o.userData.noShadow = true; }); (SKIN.cloudGroups = SKIN.cloudGroups || []).push(g); scene.add(g); const sun = new THREE.Mesh(new THREE.CircleGeometry(46, 24), new THREE.MeshBasicMaterial({ color: 0xfff1b8, fog: false, depthWrite: false })); const d = SUN.clone().negate().multiplyScalar(1350); sun.position.copy(d); sun.lookAt(0, 0, 0); scene.add(sun); }
function skinApply() { if (!SKIN.on) return; const hz = SKIN.c.horizon; renderer.setClearColor(hz); scene.background = skinSky(); scene.fog = new THREE.FogExp2(0xcfe8f2, FOG_D * .25); skinClouds();
  for (const m of FILL_MATS) { m.uniforms.uSkin.value = 1; m.uniforms.uPaper.value.set(0xcfe8f2); m.uniforms.uInk.value.set(SKIN.c.ink); m.uniforms.uShadow.value.set(SKIN.c.shadow); }
  for (const m of LINE_MATS) { if (m.userData.keep) continue; m.color.set(SKIN.c.ink); m.transparent = true; m.opacity = Math.min(m.opacity ?? 1, .2); m.linewidth *= .6; m.needsUpdate = true; } }
/* ---- lit renderer: real lights and shadow maps instead of the flat toon branch. The material keeps a `uniforms` proxy so gameplay code (hit flash, team ink, weather fog) still talks to it ---- */
SKIN.lit = true;
function skinMat(o = {}) { const m = new THREE.MeshLambertMaterial({ side: THREE.DoubleSide, polygonOffset: true, polygonOffsetFactor: o.offset ?? 1, polygonOffsetUnits: o.offset ?? 1 }); m.fog = o.fog !== 0;
  const U = m.uniforms = { uPaper: { value: new THREE.Color(SKIN.c.horizon) }, uInk: { value: new THREE.Color(SKIN.c.ink) }, uFreq: { value: 0 }, uHatch: { value: 0 }, uHw: { value: 0 }, uFog: { value: o.fog ?? FOG_D }, uFlash: { value: 0 }, uFlashC: { value: new THREE.Color(SKIN.c.coral) }, uSkin: { value: 1 }, uShadow: { value: new THREE.Color(SKIN.c.shadow) }, uSun: { value: new V3() }, uRim: { value: 0 } };
  m.onBeforeCompile = sh => { sh.uniforms.uFlash = m.uniforms.uFlash; sh.uniforms.uFlashC = m.uniforms.uFlashC; sh.uniforms.uInk = m.uniforms.uInk; sh.uniforms.uRim = m.uniforms.uRim;
    sh.vertexShader = 'attribute float tone; attribute vec3 tint; varying float vTone; varying vec3 vTint; varying float vWNy;\n' + sh.vertexShader.replace('#include <begin_vertex>', '#include <begin_vertex>\n  vTone = tone; vTint = tint; vWNy = normalize(mat3(modelMatrix) * objectNormal).y;');
    sh.fragmentShader = 'uniform float uFlash, uRim; uniform vec3 uFlashC, uInk; varying float vTone; varying vec3 vTint; varying float vWNy;\n' + sh.fragmentShader
      .replace('#include <color_fragment>', '#include <color_fragment>\n  diffuseColor.rgb = vTone > .9 ? uInk : vTint * (vTone > .6 ? .82 : (vTone > .2 ? .93 : 1.)) * (vTone < 0. ? 1. + vTone * .5 : 1.);')
      .replace('#include <dithering_fragment>', '#include <dithering_fragment>\n  if (vWNy < -.5) gl_FragColor.rgb += vec3(1., .97, .92) * .12;\n  if (uRim > 0.) { float rim = pow(1. - abs(dot(normalize(normal), normalize(vViewPosition))), 3.); gl_FragColor.rgb += vec3(1., .95, .85) * rim * uRim; }\n  { float lu = dot(gl_FragColor.rgb, vec3(.3, .59, .11)); gl_FragColor.rgb = mix(gl_FragColor.rgb * vec3(.92, .95, 1.06), gl_FragColor.rgb, smoothstep(.35, .75, lu)); }\n  gl_FragColor.rgb = max(gl_FragColor.rgb, diffuseColor.rgb * .74);\n  gl_FragColor.rgb = mix(gl_FragColor.rgb, uFlashC, uFlash);'); };
  m.customProgramCacheKey = () => 'skinLambert'; m.clone = () => { const c = skinMat(o); for (const k in m.uniforms) { const v = m.uniforms[k].value; c.uniforms[k].value = v && v.clone ? v.clone() : v; } return c; }; return m; }
/* lights for any scene (world, first-person gun, inventory icons, portrait stage); the world sun also casts a shadow map that follows the camera */
function skinLights(sc, shadow) { const hemi = new THREE.HemisphereLight(0xa9c4ff, 0xf3e3c8, 2.15); sc.add(hemi); sc.add(new THREE.AmbientLight(0xffe9d0, .18)); const sun = new THREE.DirectionalLight(0xfff1d6, 1.95); sun.position.copy(SUN).multiplyScalar(-60); sc.add(sun); sc.add(sun.target);
  if (shadow) { sun.castShadow = true; const s = sun.shadow; s.mapSize.set(2048, 2048); const c = s.camera; c.left = -40; c.right = 40; c.top = 40; c.bottom = -40; c.near = 1; c.far = 260; s.bias = -.0012; s.normalBias = .045; SKIN.sun = sun; } return sun; }
function skinFishermen() { if (!SKIN.on || typeof buildSoldier !== 'function') return; const spots = []; const tl = TOWNS.find(t => t.id === 'light'), tw = TOWNS.find(t => t.id === 'wharf'); if (tl) spots.push({ x: tl.x + 14, z: tl.z + 6 + 25.2, y: Math.max(MAP.terrainY(tl.x + 14, tl.z + 31), MAP.sea) + .5, yaw: Math.PI }); if (tw) spots.push({ x: tw.x - 20 - 42.6, z: tw.z - 2 + 1.2, y: Math.max(MAP.terrainY(tw.x - 62, tw.z - 2), MAP.sea) + .6, yaw: Math.PI / 2 });
  for (const sp of spots) { const m = buildSoldier('red', 'scribe'); const r = m.root; r.position.set(sp.x, sp.y - .45, sp.z); r.rotation.y = sp.yaw; for (const L of [m.legL, m.legR]) { L.rotation.x = -1.45; L.shin.rotation.x = 1.35; } m.armR.rotation.set(-.9, 0, -.1); m.armL.rotation.set(-.7, 0, .2); if (typeof islArmIK === 'function' && m.armR.elbow) { islArmIK(m.armR, .03, -.21, -.44, .9, -.5, .3); islArmIK(m.armL, -.02, -.1, -.6, -.9, -.5, .3); } m.upper.rotation.x = .12; m.head.rotation.x = .25; m.gun.visible = false; if (m.gear) { m.gear.hat.visible = true; m.gear.helm.forEach(o => o.visible = false); m.gear.bag.forEach((o, i) => o.visible = i === 1); m.gear.vest.forEach(o => o.visible = false); } m.mark.visible = false; scene.add(r);
    const s = new Sk('sun'); islSeg(s, [0, .62, -.35], [0, 2.1, -2.4], .02, .008, 0x8a5f3c, 5); islSeg(s, [0, 2.1, -2.4], [0, -.9, -2.5], .002, .002, 0xfff8ec, 3); islCyl(s, .2, .16, .32, .55, .16, .1, 0xc99a62, 10); for (let i = 0; i < 3; i++) { islBall(s, .025, .03, .09, .5 + i * .05, .34, .1, 0xc9d6de, 6); } islCyl(s, .16, .16, .35, -.05, -.27, .25, 0x8a5f3c, 8); const g = s.bake(fillMat({ objSpace: true, fog: .0045 }), null); g.position.set(sp.x, sp.y - .45, sp.z); g.rotation.y = sp.yaw; scene.add(g);
    const fl = new THREE.Mesh(new THREE.SphereGeometry(.05, 8, 6), new THREE.MeshLambertMaterial({ color: 0xff5a4e })); const fw = new THREE.Vector3(0, 0, -2.5).applyAxisAngle(new THREE.Vector3(0, 1, 0), sp.yaw); fl.position.set(sp.x + fw.x, MAP.sea + .03, sp.z + fw.z); fl.userData.y0 = MAP.sea + .03; scene.add(fl); (SKIN.floats = SKIN.floats || []).push(fl);
    if (spots.indexOf(sp) === 1) { m.head.rotation.set(.45, 0, .35); m.armR.rotation.set(-.3, 0, -.1); if (typeof islArmIK === 'function' && m.armR.elbow) { islArmIK(m.armR, .1, -.44, -.22, 1, -.3, .3); islArmIK(m.armL, -.1, -.44, -.24, -1, -.3, .3); } const zs = []; for (let i = 0; i < 3; i++) { const z = new THREE.Mesh(new THREE.PlaneGeometry(.22, .22), new THREE.MeshBasicMaterial({ map: textTex('Z', { w: 64, h: 64, color: '#ffffff', font: '900 52px sans-serif' }), transparent: true, depthWrite: false, side: THREE.DoubleSide })); scene.add(z); zs.push(z); } SKIN.sleeper = { x: sp.x + .5, y: sp.y + 1.55, z: sp.z, zs }; } } }
function skinShadowFollow(cam) { const sun = SKIN.sun; if (!sun) return; const sx = Math.round(cam.position.x / 2) * 2, sz = Math.round(cam.position.z / 2) * 2, sy = cam.position.y; sun.target.position.set(sx, sy - 4, sz); sun.position.set(sx - SUN.x * 120, sy - 4 - SUN.y * 120, sz - SUN.z * 120); sun.target.updateMatrixWorld(); }
/* every second: lit meshes cast and receive shadows (clouds and sky bits opt out) */
function skinShadowFlags() { scene.traverse(o => { if (!o.isMesh || !o.material || !o.material.isMeshLambertMaterial) return; if (o.userData.noShadow) { o.castShadow = o.receiveShadow = false; return; } o.castShadow = !o.userData.noCast; o.receiveShadow = true; }); }
(() => { const _apply = skinApply; skinApply = function () { _apply(); if (!SKIN.on || !SKIN.lit) return; renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; skinLights(scene, true); scene.traverse(o => { if (o.isMesh && o.geometry && o.geometry.type === 'CircleGeometry') o.userData.noShadow = true; }); for (const g of SKIN.cloudGroups || []) g.traverse(o => o.userData.noShadow = true); skinShadowFlags(); try { skinFishermen(); } catch (e) { console.warn('fishermen', e); } scene.onBeforeRender = (r, s, cam) => skinShadowFollow(cam); if (MAP.shells && MAP.shells.length) { const im = new THREE.InstancedMesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({ colorWrite: false, depthWrite: false }), MAP.shells.length), M = new THREE.Matrix4(); MAP.shells.forEach(([a, b, c, d, e, f], i) => { M.compose(new THREE.Vector3((a + d) / 2, (b + e) / 2, (c + f) / 2), new THREE.Quaternion(), new THREE.Vector3(d - a, e - b, f - c)); im.setMatrixAt(i, M); }); im.castShadow = true; im.receiveShadow = false; im.frustumCulled = false; im.userData.noShadow = false; scene.add(im); } if (MAP.lanterns && MAP.lanterns.length) { const c = document.createElement('canvas'); c.width = c.height = 64; const g = c.getContext('2d'), gr = g.createRadialGradient(32, 32, 0, 32, 32, 32); gr.addColorStop(0, 'rgba(255,216,144,1)'); gr.addColorStop(1, 'rgba(255,226,160,0)'); g.fillStyle = gr; g.fillRect(0, 0, 64, 64); const tex = new THREE.CanvasTexture(c), geo = new THREE.PlaneGeometry(2.4, 2.4).rotateX(-Math.PI / 2), mat = new THREE.MeshBasicMaterial({ map: tex, transparent: true, opacity: .32, depthWrite: false, blending: THREE.AdditiveBlending, polygonOffset: true, polygonOffsetFactor: -3, polygonOffsetUnits: -3 }), im = new THREE.InstancedMesh(geo, mat, MAP.lanterns.length), M = new THREE.Matrix4(); MAP.lanterns.forEach((l, i) => { M.makeTranslation(l.x, l.y, l.z); im.setMatrixAt(i, M); }); im.userData.noShadow = true; im.renderOrder = 2; scene.add(im); } setInterval(() => { if (scene) skinShadowFlags(); }, 1000); }; })();
/* ---- UI palette: every hard-coded canvas colour (compass, minimap, big map, stats chart, signs) goes through UIC ---- */
SKIN.ui = { '#16161c': '#2e3a59', '#f5f2ea': '#fff8ec', '#d42a2a': '#ff5a4e', '#2d6cb3': '#1c6fb0', '#e9a520': '#ffb020', '#c9d8df': '#2a84c7', '#dbe8ee': '#5fd2d0', '#ece4cf': '#efe0a8', '#e4e0d4': '#a9c46f', '#ebe8dd': '#8fca82', '#f3f0e6': '#7cc47f', '#7f9bb0': '#e8fbff', '#8c877a': 'rgba(46,58,89,.32)', '#c2bdae': 'rgba(46,58,89,.12)', '#8c7b5a': '#f7e7b4', '#b9b3a4': '#f2c7a8', '#d8d3c6': '#fff1dc' };
function UIC(c) { if (typeof SKIN === 'undefined' || !SKIN.on) return c; if (SKIN.ui[c]) return SKIN.ui[c]; if (c.startsWith('rgba(22,22,28,')) return 'rgba(46,58,89,' + c.slice(14); if (c.startsWith('rgba(245,242,234,')) return 'rgba(255,248,236,' + c.slice(17); return c; }
if (SKIN.on) document.body.classList.add('skin');
