'use strict';
/* ============ INK ISLAND · towns: building kit and the six named places ============ */
/* All footprints are integer metres on the town pad; floors are 3 m; stairs rise 0.25 m per 0.5 m tread. Sides: N = z1 face, S = z2, W = x1, E = x2. */
function buildTowns(K) {
  const { solid, skAt, detAt, rr, R, tY, sign, spot, rock, floor, ladder, win, building } = K, T = .3, FL = 3, e = .012;
  const sk = (x, z) => skAt(x, z), dt = (x, z) => detAt(x, z);
  /* a wall along one axis with openings cut out: {a: start along the axis, w: width, y: sill height, h: opening height, glass: bool} */
  function face(axis, a1, a2, fixed, y0, h, openings = [], o = {}) {
    const box = (s0, s1, yb, yt) => axis === 'x' ? solid(s0, fixed - T / 2, s1, fixed + T / 2, yb, yt, o) : solid(fixed - T / 2, s0, fixed + T / 2, s1, yb, yt, o);
    let cur = a1; const ops = openings.slice().sort((p, q) => p.a - q.a);
    for (const op of ops) { const s0 = Math.max(a1, op.a), s1 = Math.min(a2, op.a + op.w); if (s0 > cur) box(cur, s0, y0, y0 + h); if (op.y > 0) box(s0, s1, y0, y0 + op.y); if (op.y + op.h < h) box(s0, s1, y0 + op.y + op.h, y0 + h);
      const s = axis === 'x' ? sk((s0 + s1) / 2, fixed) : sk(fixed, (s0 + s1) / 2), yb = y0 + op.y, yt = yb + op.h;
      if (op.glass) { win({ axis, s0: s0 + .05, s1: s1 - .05, yb: yb + .05, yt: yt - .05, fixed }); if (axis === 'x') s.box(s1 - s0 + .2, .06, T + .24, (s0 + s1) / 2, yb - .03, fixed, { tone: .66 }); else s.box(T + .24, .06, s1 - s0 + .2, fixed, yb - .03, (s0 + s1) / 2, { tone: .66 }); if (axis === 'x') { s.line([s0 + .05, (yb + yt) / 2, fixed - .05, s1 - .05, (yb + yt) / 2, fixed - .05, (s0 + s1) / 2, yb, fixed - .05, (s0 + s1) / 2, yt, fixed - .05, s0 - .1, yb - .04, fixed - .2, s1 + .1, yb - .04, fixed - .2]); }
        else { s.line([fixed - .05, (yb + yt) / 2, s0 + .05, fixed - .05, (yb + yt) / 2, s1 - .05, fixed - .05, yb, (s0 + s1) / 2, fixed - .05, yt, (s0 + s1) / 2, fixed - .2, yb - .04, s0 - .1, fixed - .2, yb - .04, s1 + .1]); } }
      else { /* door: frame posts, lintel, threshold board, and a leaning leaf */
        if (op.leaf !== false) { if (axis === 'x') { for (const xx of [s0 - .06, s1 + .06]) s.box(.12, op.h + .1, T + .1, xx, yb + op.h / 2 + .05, fixed, { tint: WOOD, tone: .66 }); s.box(s1 - s0 + .24, .12, T + .1, (s0 + s1) / 2, yt + .06, fixed, { tint: WOOD, tone: .66 }); s.box(s1 - s0, .04, T + .3, (s0 + s1) / 2, yb + .02, fixed, { tint: WOOD, tone: .33 }); } else { for (const zz of [s0 - .06, s1 + .06]) s.box(T + .1, op.h + .1, .12, fixed, yb + op.h / 2 + .05, zz, { tint: WOOD, tone: .66 }); s.box(T + .1, .12, s1 - s0 + .24, fixed, yt + .06, (s0 + s1) / 2, { tint: WOOD, tone: .66 }); s.box(T + .3, .04, s1 - s0, fixed, yb + .02, (s0 + s1) / 2, { tint: WOOD, tone: .33 }); } }
        if (axis === 'x') { s.line([s0, yb, fixed - .2, s0, yt, fixed - .2, s1, yb, fixed - .2, s1, yt, fixed - .2, s0, yt, fixed - .2, s1, yt, fixed - .2]); if (op.leaf !== false) s.box(op.w * .92, op.h - .06, .06, s0 + op.w * .46 * .35 + .02, yb + op.h / 2 - .02, fixed + (op.in ? .5 : -.5), { tint: WOOD, tone: .33, r: [0, op.in ? 1.2 : -1.2, 0] }); }
        else { s.line([fixed - .2, yb, s0, fixed - .2, yt, s0, fixed - .2, yb, s1, fixed - .2, yt, s1, fixed - .2, yt, s0, fixed - .2, yt, s1]); if (op.leaf !== false) s.box(.06, op.h - .06, op.w * .92, fixed + (op.in ? .5 : -.5), yb + op.h / 2 - .02, s0 + op.w * .46 * .35 + .02, { tint: WOOD, tone: .33, r: [0, op.in ? 1.2 : -1.2, 0] }); } }
      cur = Math.max(cur, s1); }
    if (cur < a2) box(cur, a2, y0, y0 + h);
  }
  /* stair: 0.25 m risers on 0.5 m treads, 1.2 m wide, ascending along +z/-z/+x/-x from (x,z) */
  function stair(x, z, y0, y1, dir, w = 1.2, d = .5) { const n = Math.round((y1 - y0) / .25); for (let i = 0; i < n; i++) { const top = y0 + .25 * (i + 1), s = i * d, t = (i + 1) * d;
      const yb = top - .28;   // thin treads: the flight above keeps its headroom, and the space under a stair is real
      if (dir === '+z') solid(x, z + s, x + w, z + t, yb, top, { stair: true }); else if (dir === '-z') solid(x, z - t, x + w, z - s, yb, top, { stair: true }); else if (dir === '+x') solid(x + s, z, x + t, z + w, yb, top, { stair: true }); else solid(x - t, z, x - s, z + w, yb, top, { stair: true }); }
    const len = n * d, a = []; { const k = sk(x, z); if (dir === '+z') { k.poly([[x + w, y0, z], [x + w, y1, z + len], [x + w, y1 - .3, z + len], [x + w, y0 - .3, z]], true); k.line([x + w + .04, y0 + .95, z + .1, x + w + .04, y1 + .95, z + len - .1, x + w + .04, y0 + .95, z + .1, x + w + .04, y0, z + .1, x + w + .04, y1 + .95, z + len - .1, x + w + .04, y1, z + len - .1]); } else if (dir === '-z') { k.poly([[x + w, y0, z], [x + w, y1, z - len], [x + w, y1 - .3, z - len], [x + w, y0 - .3, z]], true); } else if (dir === '+x') { k.poly([[x, y0, z + w], [x + len, y1, z + w], [x + len, y1 - .3, z + w], [x, y0 - .3, z + w]], true); } else { k.poly([[x, y0, z + w], [x - len, y1, z + w], [x - len, y1 - .3, z + w], [x, y0 - .3, z + w]], true); } }
    for (let i = 1; i < n; i++) { const top = y0 + .25 * i + e, s = i * d; if (dir === '+z') a.push(x + .05, top, z + s, x + w - .05, top, z + s); else if (dir === '-z') a.push(x + .05, top, z - s, x + w - .05, top, z - s); else if (dir === '+x') a.push(x + s, top, z + .05, x + s, top, z + w - .05); else a.push(x - s, top, z + .05, x - s, top, z + w - .05); } sk(x, z).line(a); return len; }
  function slab(x1, z1, x2, z2, y, hole) { // floor slab with an optional rectangular hole
    if (!hole) return solid(x1, z1, x2, z2, y - .25, y, { tone: .33, slab: true }); const [hx1, hz1, hx2, hz2] = hole;
    if (hz1 > z1) solid(x1, z1, x2, hz1, y - .25, y, { tone: .33, slab: true }); if (hz2 < z2) solid(x1, hz2, x2, z2, y - .25, y, { tone: .33, slab: true }); if (hx1 > x1) solid(x1, hz1, hx1, hz2, y - .25, y, { tone: .33, slab: true }); if (hx2 < x2) solid(hx2, hz1, x2, hz2, y - .25, y, { tone: .33, slab: true });
    const s = sk((x1 + x2) / 2, (z1 + z2) / 2); s.line([hx1, y + e, hz1, hx2, y + e, hz1, hx1, y + e, hz1, hx1, y + e, hz2, hx2, y + e, hz1, hx2, y + e, hz2]); }  // ink edge around the stair hole
  /* roof: flat with parapet, or gable along the long axis (collision slab under it) */
  function roof(x1, z1, x2, z2, y, kind, tint = PAPER) { const s = sk((x1 + x2) / 2, (z1 + z2) / 2);
    if (kind === 'gable') { const alongX = x2 - x1 >= z2 - z1, rise = Math.min(2.2, (alongX ? z2 - z1 : x2 - x1) * .32), ov = .5; solid(x1, z1, x2, z2, y - .25, y, { tone: .33, slab: true });
      if (alongX) { const zm = (z1 + z2) / 2; s.quad([x1 - ov, y, z1 - ov], [x1 - ov, y + rise, zm], [x2 + ov, y + rise, zm], [x2 + ov, y, z1 - ov], .33, tint); s.quad([x1 - ov, y, z2 + ov], [x2 + ov, y, z2 + ov], [x2 + ov, y + rise, zm], [x1 - ov, y + rise, zm], 0, tint); s.tri([x1, y, z1], [x1, y + rise, zm], [x1, y, z2], 0, tint); s.tri([x2, y, z1], [x2, y, z2], [x2, y + rise, zm], 0, tint);
        s.line([x1 - ov, y + rise, zm, x2 + ov, y + rise, zm, x1 - ov, y, z1 - ov, x2 + ov, y, z1 - ov, x1 - ov, y, z2 + ov, x2 + ov, y, z2 + ov, x1 - ov, y, z1 - ov, x1 - ov, y + rise, zm, x1 - ov, y, z2 + ov, x1 - ov, y + rise, zm, x2 + ov, y, z1 - ov, x2 + ov, y + rise, zm, x2 + ov, y, z2 + ov, x2 + ov, y + rise, zm, x1, y, z1, x1, y, z2, x2, y, z1, x2, y, z2]);
        const a = []; for (let x = x1 + 1; x < x2; x += 1.5) a.push(x, y + .02, z1 - ov + .1, x, y + rise - .05, zm - .02, x + .4, y + .02, z2 + ov - .1, x + .4, y + rise - .05, zm + .02); dt(x1, z1).line(a); }
      else { const xm = (x1 + x2) / 2; s.quad([x1 - ov, y, z1 - ov], [x1 - ov, y, z2 + ov], [xm, y + rise, z2 + ov], [xm, y + rise, z1 - ov], .33, tint); s.quad([x2 + ov, y, z1 - ov], [xm, y + rise, z1 - ov], [xm, y + rise, z2 + ov], [x2 + ov, y, z2 + ov], 0, tint); s.tri([x1, y, z1], [x2, y, z1], [xm, y + rise, z1], 0, tint); s.tri([x1, y, z2], [xm, y + rise, z2], [x2, y, z2], 0, tint);
        s.line([xm, y + rise, z1 - ov, xm, y + rise, z2 + ov, x1 - ov, y, z1 - ov, x1 - ov, y, z2 + ov, x2 + ov, y, z1 - ov, x2 + ov, y, z2 + ov, x1 - ov, y, z1 - ov, xm, y + rise, z1 - ov, x2 + ov, y, z1 - ov, xm, y + rise, z1 - ov, x1 - ov, y, z2 + ov, xm, y + rise, z2 + ov, x2 + ov, y, z2 + ov, xm, y + rise, z2 + ov, x1, y, z1, x2, y, z1, x1, y, z2, x2, y, z2]);
        const a = []; for (let z = z1 + 1; z < z2; z += 1.5) a.push(x1 - ov + .1, y + .02, z, xm - .02, y + rise - .05, z, x2 + ov - .1, y + .02, z + .4, xm + .02, y + rise - .05, z + .4); dt(x1, z1).line(a); } }
    else { solid(x1 - .15, z1 - .15, x2 + .15, z2 + .15, y - .25, y + .05, { tone: .33, slab: true }); for (const [a, b, c, d] of [[x1 - .15, z1 - .15, x2 + .15, z1 + .1], [x1 - .15, z2 - .1, x2 + .15, z2 + .15], [x1 - .15, z1, x1 + .1, z2], [x2 - .1, z1, x2 + .15, z2]]) solid(a, b, c, d, y, y + .45, { tone: .66 });
      if (R() < .5) { s.box(.9, .7, .9, x1 + 1.2, y + .4, z2 - 1.2, { tone: .33 }); s.cyl(.25, .25, 1.4, 7, x2 - 1, y + .7, z1 + 1, { tone: .33 }); } } }
  /* iron ladder up the outside of a flat-roofed house: foot cell on the ground, top just inside the parapet; the roof is registered as a floor whose stair is the ladder */
  function ironLadder(x1, z1, x2, z2, y0, H, side, at) { const ax = side === 'N' || side === 'S', wall = side === 'N' ? z1 : side === 'S' ? z2 : side === 'W' ? x1 : x2, out = side === 'N' || side === 'W' ? -1 : 1, fx = ax ? at + .5 : wall + out * .72, fz = ax ? wall + out * .72 : at + .5, gy = Math.min(...[.3, .9, 1.4].map(q => tY(ax ? fx : wall + out * q, ax ? wall + out * q : fz))); if (gy < y0 - 3 || gy > y0 + 1.2 || y0 - gy > .6) return; const y1 = Math.min(gy, y0), y2 = y0 + H + .05, tpx = ax ? fx : wall - out * 1.0, tpz = ax ? wall - out * 1.0 : fz; if (MAP.solids.some(q => (q.veg && q.x2 > fx - 1.3 && q.x1 < fx + 1.3 && q.z2 > fz - 1.3 && q.z1 < fz + 1.3) || (q.x2 > tpx - .8 && q.x1 < tpx + .8 && q.z2 > tpz - .8 && q.z1 < tpz + .8 && q.y2 > y2 + .1 && q.y1 < y2 + 1.7)) || MAP.buildings.some(q => fx > q.x1 - 1.5 && fx < q.x2 + 1.5 && fz > q.z1 - 1.5 && fz < q.z2 + 1.5)) return; const s = sk(fx, fz), rx = ax ? 0 : wall + out * .3, rz = ax ? wall + out * .3 : 0;
    for (const q of [-.25, .25]) s.bx((ax ? fx + q : rx) - .03, y1, (ax ? rz : fz + q) - .03, (ax ? fx + q : rx) + .03, y2 + .5, (ax ? rz : fz + q) + .03, { tone: .33 }); const a = []; for (let y = y1 + .3; y < y2 + .45; y += .3) a.push(ax ? fx - .25 : rx, y, ax ? rz : fz - .25, ax ? fx + .25 : rx, y, ax ? rz : fz + .25); for (let y = y1 + 1.2; y < y2 - .4; y += 1.2) a.push(ax ? fx - .25 : rx, y, ax ? rz : fz - .25, ax ? fx - .25 : wall, y, ax ? wall : fz - .25, ax ? fx + .25 : rx, y, ax ? rz : fz + .25, ax ? fx + .25 : wall, y, ax ? wall : fz + .25); s.line(a);
    const top = { x: ax ? fx : wall - out * .65, z: ax ? wall - out * .65 : fz, y: y2 }, exit = { x: ax ? fx : wall - out * 1.3, z: ax ? wall - out * 1.3 : fz, y: y2 }, yaw = side === 'N' ? Math.PI : side === 'S' ? 0 : side === 'W' ? -Math.PI / 2 : Math.PI / 2;
    ladder({ x: fx, z: fz, y1, y2, yaw, side, top, exit }); floor({ x1: x1 - .1, z1: z1 - .1, x2: x2 + .1, z2: z2 + .1, y: y2, bottom: { x: fx, z: fz, y: y1 }, top, exit, roof: true }); spot(ax ? (at < (x1 + x2) / 2 ? x2 - 2.2 : x1 + 2.2) : (side === 'W' ? x2 - 2.2 : x1 + 2.2), ax ? (side === 'N' ? z2 - 2.2 : z1 + 2.2) : (at < (z1 + z2) / 2 ? z2 - 2.2 : z1 + 2.2), y2); }
  /* house: footprint, pad height, options {h, floors, roof, door:{side,at}, win, stair:'W'|'E'|'N'|'S', props} */
  function house(x1, z1, x2, z2, y0, o = {}) {
    const floors = o.floors || 1, h = o.h || FL, H = floors * h, door = o.door || { side: 'S', at: Math.floor((x1 + x2) / 2) - 1 }, win = o.win !== false, wk = R(), WS = wk < .3 ? [.8, .8, 1.5] : wk < .8 ? [1.2, 1.1, 1.0] : [2.0, 1.1, 1.0];
    /* the plan: which wall carries the stair, the furnishable strip, and where the partition (if any) will stand — decided first so windows can keep clear of it */
    const stE = o.stair ? o.stair === 'E' : door.side === 'W', ix1 = x1 + T, iz1 = z1 + T, ix2 = x2 - T, iz2 = z2 - T, sx1 = floors > 1 && !stE ? ix1 + 1.6 : ix1, sx2 = floors > 1 && stE ? ix2 - 1.6 : ix2, wide = x2 - x1 >= 8, deep = z2 - z1 >= 8, alongZ = wide && (x2 - x1 >= z2 - z1 || !deep);
    const roofKind = o.roof || (R() < .5 ? 'gable' : 'flat'), ladS = roofKind === 'flat' && floors <= 3 && o.ladder !== false ? (door.side === 'N' || door.side === 'S' ? (R() < .5 ? 'W' : 'E') : (R() < .5 ? 'N' : 'S')) : null, ladAt = ladS === 'W' || ladS === 'E' ? Math.round((z1 + z2) / 2) - 1 : Math.round((x1 + x2) / 2) - 1;
    const dcx0 = door.side === 'N' || door.side === 'S' ? door.at + .7 : door.side === 'W' ? x1 : x2, dcz0 = door.side === 'W' || door.side === 'E' ? door.at + .7 : door.side === 'N' ? z1 : z2; let pxm = null, pzm = null;
    if (o.props !== false && (wide || deep)) { if (alongZ) { let xm = Math.round((sx1 + sx2) / 2); if ((door.side === 'N' || door.side === 'S') && Math.abs(xm - dcx0) < 2.3) xm = Math.round(dcx0 < (sx1 + sx2) / 2 ? dcx0 + 2.3 : dcx0 - 2.3); if (xm - sx1 >= 3 && sx2 - xm >= 3) pxm = xm; } else { let zm = Math.round((z1 + z2) / 2); if ((door.side === 'W' || door.side === 'E') && Math.abs(zm - dcz0) < 2.3) zm = Math.round(dcz0 < (z1 + z2) / 2 ? dcz0 + 2.3 : dcz0 - 2.3); if (zm - z1 >= 3 && z2 - zm >= 3) pzm = zm; } }
    const wins = (a1, a2, side) => { const out = []; if (!win) return out; const pm = side === 'N' || side === 'S' ? pxm : pzm, stairSide = stE ? 'E' : 'W'; for (let f = 0; f < floors; f++) for (let a = a1 + 1.5; a + WS[0] <= a2 - 1; a += 3) { if (door.side === side && a + WS[0] > door.at - .3 && a < door.at + 1.7) continue; if (pm !== null && a < pm + .6 && a + WS[0] > pm - .6) continue; if (ladS === side && a < ladAt + 1.6 && a + WS[0] > ladAt - .6) continue; if (floors > 1 && f === 0 && side === stairSide) continue; if (R() < .18) continue; out.push({ a, w: WS[0], y: f * h + WS[2], h: WS[1], glass: true }); } return out; };
    const d = (side, a1) => door.side === side ? [{ a: door.at, w: 1.4, y: 0, h: 2.2, in: true }] : [], x0 = door.side === 'N' ? z1 : z2;
    face('x', x1, x2, z1 + T / 2, y0, H, [...d('N'), ...wins(x1, x2, 'N')]); face('x', x1, x2, z2 - T / 2, y0, H, [...d('S'), ...wins(x1, x2, 'S')]);
    face('z', z1 + T, z2 - T, x1 + T / 2, y0, H, [...d('W'), ...wins(z1, z2, 'W')]); face('z', z1 + T, z2 - T, x2 - T / 2, y0, H, [...d('E'), ...wins(z1, z2, 'E')]);
    const s = sk((x1 + x2) / 2, (z1 + z2) / 2); s.quad([x1 + T, y0 + .01, z1 + T], [x1 + T, y0 + .01, z2 - T], [x2 - T, y0 + .01, z2 - T], [x2 - T, y0 + .01, z1 + T], -.06, PAPER);   // floor wash
    const holes = []; for (let f = 1; f < floors; f++) { const y = y0 + f * h, sx = stE ? x2 - T - 1.2 : x1 + T, n = Math.round(h / .25), tread = Math.max(.3, Math.min(.5, (z2 - z1 - 2 * T - 1.6) / n)), len = n * tread; stair(sx, z2 - T - len, y - h, y, '+z', 1.2, tread); const hole = [sx - (stE ? .35 : 0), Math.max(z1 + T, z2 - T - len - .3), sx + 1.2 + (stE ? 0 : .35), z2 - T]; holes.push(hole); slab(x1 + T, z1 + T, x2 - T, z2 - T, y, hole);
      { const rx = stE ? hole[0] : hole[2], k = sk(rx, hole[1]); solid(hole[0], hole[1] - .06, hole[2], hole[1], y, y + .85, { tone: .66 }); solid(rx - .03, hole[1], rx + .03, hole[3] - 1.3, y, y + .85, { tone: .66 }); const a = []; for (let q = 0; q <= 3; q++) { const zz = hole[1] + q * (hole[3] - 1.3 - hole[1]) / 3; a.push(rx, y, zz, rx, y + .95, zz); } for (let q = 0; q <= 2; q++) { const xx = hole[0] + q * (hole[2] - hole[0]) / 2; a.push(xx, y, hole[1], xx, y + .95, hole[1]); } a.push(rx, y + .95, hole[1], rx, y + .95, hole[3] - 1.3, hole[0], y + .95, hole[1], hole[2], y + .95, hole[1]); k.line(a); } floor({ x1: x1 + T, z1: z1 + T, x2: x2 - T, z2: z2 - T, y, bottom: { x: sx + .6, z: Math.max(z1 + T + .45, z2 - T - len - .7), y: y - h }, top: { x: sx + .6, z: z2 - T - .45, y }, exit: { x: sx + (stE ? -.7 : 1.9), z: z2 - T - .6, y } });   // climb toward the back wall, step off sideways at the top
      for (let a = z1 + 1.5; a + 1.2 <= z2 - 1; a += 3) {} }
    for (let f = 1; f < floors; f++) s.bx(x1 - .06, y0 + f * h - .12, z1 - .06, x2 + .06, y0 + f * h + .02, z2 + .06, { tone: .66 });
    roof(x1, z1, x2, z2, y0 + H, roofKind); if (ladS) ironLadder(x1, z1, x2, z2, y0, H, ladS, ladAt);
    /* porch: two posts and a little sloped canopy over the door; chimney on the ridge of a gable roof */
    if (o.porch !== false && floors === 1) { const sd = door.side, at = door.at, py = y0 + Math.min(2.6, h - .3); if (sd === 'N' || sd === 'S') { const zz = sd === 'N' ? z1 - 1.3 : z2 + 1.3, zw = sd === 'N' ? z1 : z2; for (const px of [at - .4, at + 1.8]) pole(px, zz, y0, py - y0 - .05); s.quad([at - .6, py + .35, zw], [at + 2.0, py + .35, zw], [at + 2.0, py - .05, zz + (sd === 'N' ? -.3 : .3)], [at - .6, py - .05, zz + (sd === 'N' ? -.3 : .3)], .33, PAPER); s.line([at - .6, py + .35, zw, at - .6, py - .05, zz + (sd === 'N' ? -.3 : .3), at + 2.0, py + .35, zw, at + 2.0, py - .05, zz + (sd === 'N' ? -.3 : .3), at - .6, py - .05, zz + (sd === 'N' ? -.3 : .3), at + 2.0, py - .05, zz + (sd === 'N' ? -.3 : .3)]); }
      else { const xx = sd === 'W' ? x1 - 1.3 : x2 + 1.3, xw = sd === 'W' ? x1 : x2; for (const pz of [at - .4, at + 1.8]) pole(xx, pz, y0, py - y0 - .05); s.quad([xw, py + .35, at - .6], [xw, py + .35, at + 2.0], [xx + (sd === 'W' ? -.3 : .3), py - .05, at + 2.0], [xx + (sd === 'W' ? -.3 : .3), py - .05, at - .6], .33, PAPER); s.line([xw, py + .35, at - .6, xx + (sd === 'W' ? -.3 : .3), py - .05, at - .6, xw, py + .35, at + 2.0, xx + (sd === 'W' ? -.3 : .3), py - .05, at + 2.0, xx + (sd === 'W' ? -.3 : .3), py - .05, at - .6, xx + (sd === 'W' ? -.3 : .3), py - .05, at + 2.0]); } }
    if (roofKind === 'gable' && R() < .7) { const alongX = x2 - x1 >= z2 - z1, rise = Math.min(2.2, (alongX ? z2 - z1 : x2 - x1) * .32), cxx = alongX ? x1 + 1.6 : (x1 + x2) / 2, czz = alongX ? (z1 + z2) / 2 : z1 + 1.6, top = y0 + H + rise + .6; s.box(.7, 1.6, .7, cxx, top - .8, czz, { tone: .33 }); s.box(.9, .12, .9, cxx, top + .04, czz, { tone: .66 }); s.line([cxx - .35, top - .4, czz - .36, cxx + .35, top - .4, czz - .36, cxx - .35, top - .4, czz + .36, cxx + .35, top - .4, czz + .36]); }
    if (o.steps !== false) doorSteps(x1, z1, x2, z2, y0, door.side, door.at);
    /* rooms: wide houses get a partition wall with its own doorway and two templated rooms per floor; small ones a single templated room */
    const dcx = door.side === 'N' || door.side === 'S' ? door.at + .7 : door.side === 'W' ? x1 : x2, dcz = door.side === 'W' || door.side === 'E' ? door.at + .7 : door.side === 'N' ? z1 : z2, nearDoor = (ax1, az1, ax2, az2) => Math.hypot(Math.max(ax1 - dcx, 0, dcx - ax2), Math.max(az1 - dcz, 0, dcz - az2)) < 2.2;
    if (o.props !== false) {
      for (let f = 0; f < floors; f++) { const y = y0 + f * h, hole = f > 0 ? holes[f - 1] : null, uses = typeof o.use === 'string' ? [o.use, o.use] : f === 0 ? (o.use ? o.use : ['kitchen', 'bed']) : (o.use2 || ['bed', 'office']);
        if (!wide && !deep) { room(sx1, iz1, sx2, iz2, y, uses[0] === 'kitchen' && f === 0 && !o.use ? 'bed' : uses[0], { x: dcx, z: dcz }); continue; }
        if (alongZ) { if (pxm === null) { room(sx1, iz1, sx2, iz2, y, uses[0], { x: dcx, z: dcz }); continue; } const xm = pxm, dz0 = door.side === 'N' ? z1 + 2 : door.side === 'S' ? z2 - 4 : Math.round((z1 + z2) / 2) - 1; partition('z', iz1, iz2, xm, y, h, dz0); const pd = { x: xm, z: dz0 + .7 }, left = dcx <= xm; room(sx1, iz1, xm - T / 2, iz2, y, uses[left ? 0 : 1], left ? { x: dcx, z: dcz } : pd); room(xm + T / 2, iz1, sx2, iz2, y, uses[left ? 1 : 0], left ? pd : { x: dcx, z: dcz }); }
        else { if (pzm === null) { room(sx1, iz1, sx2, iz2, y, uses[0], { x: dcx, z: dcz }); continue; } const zm = pzm, dx0 = door.side === 'W' ? Math.round(sx1) + 1 : door.side === 'E' ? Math.round(sx2) - 3 : Math.round((sx1 + sx2) / 2) - 1; partition('x', sx1, sx2, zm, y, h, dx0); const pd = { x: dx0 + .7, z: zm }, front = dcz <= zm; room(sx1, iz1, sx2, zm - T / 2, y, uses[front ? 0 : 1], front ? { x: dcx, z: dcz } : pd); room(sx1, zm + T / 2, sx2, iz2, y, uses[front ? 1 : 0], front ? pd : { x: dcx, z: dcz }); } } }
    for (let f = 0; f < floors; f++) { const n = Math.max(1, Math.round((x2 - x1) * (z2 - z1) / 30)), hole = f > 0 ? holes[f - 1] : null; for (let i = 0, tries = 0; i < n && tries < 40; tries++) { const px = rr(x1 + 1.2, x2 - 1.2), pz = rr(z1 + 1.2, z2 - 1.2); if (hole && px > hole[0] - .4 && px < hole[2] + .4 && pz > hole[1] - .4 && pz < hole[3] + .4) continue; if (f === 0 && nearDoor(px, pz, px, pz)) continue; spot(px, pz, y0 + f * h); i++; } }
    building({ kind: 'house', x1, z1, x2, z2, y0, floors, door, stair: stE ? 'E' : 'W' }); return { x1, z1, x2, z2, y0, H };
  }
  /* ---------- room templates: every piece is a solid (cover + a loot surface) placed away from the doorway; `near(ax1,az1,ax2,az2)` says whether a box crowds the door ---------- */
  const furn = { table: (x, z, y0, w = 1.6, d = .9) => { solid(x, z, x + w, z + d, y0, y0 + .75, { tint: WOOD, tone: .33 }); const k = sk(x, z); k.line([x, y0 + .75 + e, z, x + w, y0 + .75 + e, z + d, x, y0 + .75 + e, z + d, x + w, y0 + .75 + e, z]); spot(x + w / 2, z + d / 2, y0 + .75); },
    bed: (x, z, y0, alongX = true) => { const w = alongX ? 1.9 : .9, d = alongX ? .9 : 1.9; solid(x, z, x + w, z + d, y0, y0 + .5, { tint: WOOD, tone: .33 }); const k = sk(x, z); k.bx(x, y0 + .5, z, x + w, y0 + .62, z + d, { tone: 0 }); k.box(alongX ? .5 : .7, .12, alongX ? .7 : .5, x + (alongX ? .3 : w / 2), y0 + .68, z + (alongX ? d / 2 : .3), { tone: 0 }); spot(x + w / 2, z + d / 2, y0 + .5); },
    stand: (x, z, y0) => { solid(x, z, x + .5, z + .5, y0, y0 + .6, { tint: WOOD, tone: .66 }); sk(x, z).line([x, y0 + .6 + e, z, x + .5, y0 + .6 + e, z + .5]); spot(x + .25, z + .25, y0 + .6); },
    wardrobe: (x, z, y0, alongX = true) => { const w = alongX ? 1.2 : .6, d = alongX ? .6 : 1.2; solid(x, z, x + w, z + d, y0, y0 + 1.9, { tint: WOOD, tone: .33 }); const k = sk(x, z), fx = alongX ? [x + w / 2, z + d + .01] : [x + w + .01, z + d / 2]; k.line(alongX ? [fx[0], y0 + .1, fx[1], fx[0], y0 + 1.8, fx[1], fx[0] - .25, y0 + 1.0, fx[1], fx[0] - .15, y0 + 1.0, fx[1]] : [fx[0], y0 + .1, fx[1], fx[0], y0 + 1.8, fx[1], fx[0], y0 + 1.0, fx[1] - .25, fx[0], y0 + 1.0, fx[1] - .15]); },
    counter: (x, z, y0, len = 2.4, alongX = true) => { const w = alongX ? len : .6, d = alongX ? .6 : len; solid(x, z, x + w, z + d, y0, y0 + .9, { tone: .33 }); const k = sk(x, z); k.box(.6, .1, .6, x + (alongX ? .4 : .3), y0 + .95, z + (alongX ? .3 : .4), { tone: .66 }); k.line([x + (alongX ? .4 : .3) - .22, y0 + 1.0, z + (alongX ? .3 : .4) - .22, x + (alongX ? .4 : .3) + .22, y0 + 1.0, z + (alongX ? .3 : .4) + .22, x + (alongX ? .4 : .3) + .22, y0 + 1.0, z + (alongX ? .3 : .4) - .22, x + (alongX ? .4 : .3) - .22, y0 + 1.0, z + (alongX ? .3 : .4) + .22]); k.line([x, y0 + .9 + e, z, x + w, y0 + .9 + e, z, x, y0 + .9 + e, z + d, x + w, y0 + .9 + e, z + d, x + (alongX ? 1.4 : .3), y0 + .9 + e, z + (alongX ? .1 : 1.4), x + (alongX ? 1.4 : .3), y0 + .9 + e, z + (alongX ? .5 : 1.8)]); spot(x + w / 2 + (alongX ? .4 : 0), z + d / 2 + (alongX ? 0 : .4), y0 + .9); },
    stool: (x, z, y0) => { sk(x, z).box(.35, .35, .35, x, y0 + .18, z, { tint: WOOD, tone: .66 }); },
    desk: (x, z, y0) => { solid(x, z, x + 1.6, z + .8, y0, y0 + .75, { tint: WOOD, tone: .33 }); const k = sk(x, z); k.line([x, y0 + .75 + e, z, x + 1.6, y0 + .75 + e, z, x, y0 + .75 + e, z + .8, x + 1.6, y0 + .75 + e, z + .8, x + .9, y0 + .75 + e, z, x + .9, y0 + .75 + e, z + .8]); k.box(.5, .5, .5, x + .8, y0 + .25, z + 1.2, { tint: WOOD, tone: .66 }); spot(x + .4, z + .4, y0 + .75); spot(x + 1.2, z + .4, y0 + .75); },
    cabinet: (x, z, y0) => { solid(x, z, x + .5, z + .6, y0, y0 + 1.4, { tone: .33 }); const k = sk(x, z); for (let yy = .35; yy < 1.4; yy += .35) k.line([x + .5 + e, y0 + yy, z, x + .5 + e, y0 + yy, z + .6]); spot(x + .25, z + .3, y0 + 1.4); },
    shelf: (x, z, y0, alongX = true, len = 2) => { const w = alongX ? len : .4, d = alongX ? .4 : len; for (const [px, pz] of [[x, z], [x + w - .06, z], [x, z + d - .06], [x + w - .06, z + d - .06]]) solid(px, pz, px + .06, pz + .06, y0, y0 + 1.9, { tone: .66 }); for (const yy of [.08, .55, 1.0, 1.45, 1.9]) solid(x, z, x + w, z + d, y0 + yy - .06, y0 + yy, { tone: .33 }); const k = sk(x, z); k.line(alongX ? [x, y0 + 1.9, z, x + w, y0 + 1.9, z, x, y0 + 1.9, z + d, x + w, y0 + 1.9, z + d] : [x, y0 + 1.9, z, x, y0 + 1.9, z + d, x + w, y0 + 1.9, z, x + w, y0 + 1.9, z + d]); spot(x + w / 2, z + d / 2, y0 + .63); spot(x + w * (alongX ? .25 : .5), z + d * (alongX ? .5 : .25), y0 + 1.08); },
    rack: (x, z, y0, alongX = true, len = 3) => { const w = alongX ? len : .6, d = alongX ? .6 : len; for (const [px, pz] of [[x, z], [x + w - .08, z], [x, z + d - .08], [x + w - .08, z + d - .08]]) solid(px, pz, px + .08, pz + .08, y0, y0 + 2.2, { tone: .66 }); for (const yy of [.25, 1.0, 1.75]) solid(x, z, x + w, z + d, y0 + yy, y0 + yy + .08, { tone: .33 }); spot(x + w * .3, z + d / 2, y0 + .33); spot(x + w * .7, z + d / 2, y0 + 1.08); },
    bales: (x, z, y0, n = 2) => { for (let i = 0; i < n; i++) { const bx = x + i * 2.1; solid(bx, z, bx + 2, z + 2, y0, y0 + 2, { tint: WOOD, tone: .66 }); const k = sk(bx, z); k.line([bx, y0 + .7, z - .01, bx + 2, y0 + .7, z - .01, bx, y0 + 1.4, z - .01, bx + 2, y0 + 1.4, z - .01]); } spot(x + 1, z + 2.6, y0); } };
  /* a room gets a template by use: 卧室 T1 / 厨房 T2 / 办公室 T4; furniture hugs the wall farthest from the doorway */
  const room = (x1, z1, x2, z2, y0, use, dpt) => { const w = x2 - x1, d = z2 - z1, near = (ax1, az1, ax2, az2) => Math.hypot(Math.max(ax1 - dpt.x, 0, dpt.x - ax2), Math.max(az1 - dpt.z, 0, dpt.z - az2)) < 2.2, farX = dpt.x < (x1 + x2) / 2, farZ = dpt.z < (z1 + z2) / 2, winClash = (ax1, az1, ax2, az2) => MAP.windows.some(wn => wn.axis === 'x' ? (Math.abs(wn.fixed - az1) < .5 || Math.abs(wn.fixed - az2) < .5) && wn.s1 > ax1 - .3 && wn.s0 < ax2 + .3 : (Math.abs(wn.fixed - ax1) < .5 || Math.abs(wn.fixed - ax2) < .5) && wn.s1 > az1 - .3 && wn.s0 < az2 + .3), put = (ax1, az1, ax2, az2, fn, tall = false) => { if (ax1 >= x1 && az1 >= z1 && ax2 <= x2 && az2 <= z2 && !near(ax1, az1, ax2, az2) && !(tall && winClash(ax1, az1, ax2, az2))) { fn(); return true; } return false; };
    if (use === 'bed') { const bx = farX ? x2 - .3 - 1.9 : x1 + .3, bz = farZ ? z2 - .3 - .9 : z1 + .3; put(bx, bz, bx + 1.9, bz + .9, () => furn.bed(bx, bz, y0, true)); const sx = farX ? bx - .6 : bx + 2.0; put(sx, bz, sx + .5, bz + .5, () => furn.stand(sx, bz, y0)); const wx = farX ? x1 + .3 : x2 - .3 - 1.2, wz = farZ ? z1 + .3 : z2 - .3 - .6; if (w > 4.5) put(wx, wz, wx + 1.2, wz + .6, () => furn.wardrobe(wx, wz, y0, true), true); }
    else if (use === 'kitchen') { const cz = farZ ? z2 - .3 - .6 : z1 + .3, cx = farX ? x2 - .3 - 2.4 : x1 + .3; put(cx, cz, cx + 2.4, cz + .6, () => furn.counter(cx, cz, y0, Math.min(2.4, w - 1), true)); const tx = x1 + w / 2 - .8, tz = z1 + d / 2 - .45 + (farZ ? -.6 : .6); if (w > 4.6 && d > 4.6) put(tx, tz, tx + 1.6, tz + .9, () => { furn.table(tx, tz, y0); furn.stool(tx - .35, tz + .45, y0); furn.stool(tx + 1.95, tz + .45, y0); }); }
    else if (use === 'office') { const dx = farX ? x2 - .3 - 1.6 : x1 + .3, dz = farZ ? z2 - .3 - 2.0 : z1 + .3; put(dx, dz, dx + 1.6, dz + 2.0, () => furn.desk(dx, dz, y0)); const cx = farX ? x1 + .3 : x2 - .3 - .5, cz = farZ ? z2 - .3 - 1.3 : z1 + .3; put(cx, cz, cx + .5, cz + 1.3, () => { furn.cabinet(cx, cz, y0); furn.cabinet(cx, cz + .7, y0); }, true); }
    else if (use === 'barracks') { const alongX = w >= d, L = alongX ? w : d, n = Math.max(1, Math.floor((L - 1.2) / 2.5)); for (let i = 0; i < n; i++) for (const side of [0, 1]) { const a = (alongX ? x1 : z1) + .6 + i * 2.5, bx = alongX ? a : (side ? x2 - .3 - .9 : x1 + .3), bz = alongX ? (side ? z2 - .3 - .9 : z1 + .3) : a; const bw = alongX ? 1.9 : .9, bd = alongX ? .9 : 1.9; put(bx, bz, bx + bw, bz + bd, () => furn.bed(bx, bz, y0, alongX)); const sx = alongX ? bx + 1.9 : (side ? bx - .55 : bx + .95), sz = alongX ? (side ? bz + .4 : bz) : bz + 1.9; if (i < n - 1 || !alongX) put(sx, sz, sx + .5, sz + .5, () => furn.stand(sx, sz, y0)); } }
    else if (use === 'fishhut') { const bx = farX ? x2 - .3 - 1.9 : x1 + .3, bz = farZ ? z2 - .3 - .9 : z1 + .3; put(bx, bz, bx + 1.9, bz + .9, () => furn.bed(bx, bz, y0, true)); const cx = farX ? x1 + .3 : x2 - .3 - .6, cz = farZ ? z1 + .3 : z2 - .3 - 1.8; put(cx, cz, cx + .6, cz + 1.8, () => furn.counter(cx, cz, y0, 1.8, false)); const k = sk(x1, z1), nx = farX ? x1 + .32 : x2 - .32; k.line([nx, y0 + 1.9, z1 + .6, nx, y0 + 1.9, z2 - .6, nx, y0 + 1.9, z1 + .6, nx, y0 + 1.1, z1 + 1.4, nx, y0 + 1.9, z2 - .6, nx, y0 + 1.1, z2 - 1.4, nx, y0 + 1.1, z1 + 1.4, nx, y0 + 1.1, z2 - 1.4]); }
    else if (use === 'shop') { const cz = farZ ? z2 - .3 - 2.2 : z1 + 1.6, cx = x1 + .3; put(cx, cz, cx + Math.min(2.4, w - 2.2), cz + .6, () => furn.counter(cx, cz, y0, Math.min(2.4, w - 2.2), true)); const sx = x2 - .7, sz = farZ ? z2 - .3 - 2 : z1 + .3; put(sx, sz, sx + .4, sz + 2, () => furn.shelf(sx, sz, y0, false, 2), true); const bx = x1 + .4, bz = farZ ? cz + .8 : cz - 1.2; put(bx, bz, bx + 1, bz + 1, () => { crate(bx, bz, y0, 1, WOOD, false); spot(bx + .5, bz + .5, y0 + 1); }); }
    else if (use === 'store') { const sx = farX ? x2 - .3 - .4 : x1 + .3; for (let sz = z1 + .5; sz + 2 <= z2 - .3; sz += 2.5) put(sx, sz, sx + .4, sz + 2, () => furn.shelf(sx, sz, y0, false, 2), true); const cx = x1 + .5, cz = farZ ? z2 - .3 - 1 : z1 + .3; put(cx, cz, cx + 1, cz + 1, () => { crate(cx, cz, y0, 1, WOOD, false); spot(cx + .5, cz + .5, y0 + 1); }); } };
  /* an interior wall along z at x = at (or along x at z = at) with a 1.4 m doorway at door (integer) — same face() so it inks like the outer walls */
  const partition = (axis, a1, a2, at, y0, h, door) => face(axis, a1, a2, at, y0, h, [{ a: door, w: 1.4, y: 0, h: 2.1, leaf: false }], { tone: .66 });
  /* door steps: when the ground outside a doorway is lower than the pad, a 1.6 m flight of 0.25 m steps climbs to the threshold (at most eight) */
  const doorSteps = (x1, z1, x2, z2, y0, sd, at) => { const dx = sd === 'N' || sd === 'S' ? at + .7 : sd === 'W' ? x1 - 1.2 : x2 + 1.2, dz = sd === 'W' || sd === 'E' ? at + .7 : sd === 'N' ? z1 - 1.2 : z2 + 1.2; let g = tY(dx, dz); for (let q = 1; q <= 2; q++) g = Math.min(g, tY(dx + (sd === 'W' ? -q : sd === 'E' ? q : 0), dz + (sd === 'N' ? -q : sd === 'S' ? q : 0))); g = Math.max(Math.round(g * 4) / 4, y0 - 2); const n = Math.round((y0 - g) / .25);
    if (n >= 1) { const len = n * .5, sw = 1.6; if (sd === 'N') stair(at - .1, z1 - len, g, y0, '+z', sw); else if (sd === 'S') stair(at - .1, z2 + len, g, y0, '-z', sw); else if (sd === 'W') stair(x1 - len, at - .1, g, y0, '+x', sw); else stair(x2 + len, at - .1, g, y0, '-x', sw); } };
  const shed = (x1, z1, x2, z2, y0, h, open = 'S', fill = 'racks') => { const ops = (side) => open === side ? [fill === 'shrine' ? { a: Math.round((side === 'N' || side === 'S' ? x1 + x2 : z1 + z2) / 2) - 2, w: 4, y: 0, h: h - .4, leaf: false } : { a: side === 'N' || side === 'S' ? x1 + 1 : z1 + 1, w: (side === 'N' || side === 'S' ? x2 - x1 : z2 - z1) - 2, y: 0, h: h - .4, leaf: false }] : [];
    face('x', x1, x2, z1 + T / 2, y0, h, ops('N')); face('x', x1, x2, z2 - T / 2, y0, h, ops('S')); face('z', z1 + T, z2 - T, x1 + T / 2, y0, h, ops('W')); face('z', z1 + T, z2 - T, x2 - T / 2, y0, h, ops('E'));
    roof(x1, z1, x2, z2, y0 + h, 'gable'); const s = sk(x1, z1), a = []; for (let x = x1 + 1; x < x2; x += 3) a.push(x, y0 + h - .4, z1 + .3, x, y0 + h - .4, z2 - .3); s.line(a); for (let i = 0; i < 3; i++) spot(rr(x1 + 1, x2 - 1), rr(z1 + 1, z2 - 1), y0);
    if (fill === 'shrine') { const ax = (x1 + x2) / 2 - 1.2, az = open === 'N' ? z2 - 1.8 : z1 + .6; furn.table(ax, az, y0, 2.4, .8); const k = sk(x1, z1); k.box(.5, .8, .3, ax + 1.2, y0 + 1.15, az + .4, { tone: 1 }); k.line([ax + .3, y0 + 1.6, az + .4, ax + 2.1, y0 + 1.6, az + .4]); for (let r = 0; r < 2; r++) for (let i = 0; i < 4; i++) { const qx = x1 + 2 + i * (x2 - x1 - 4) / 3, qz = open === 'N' ? az - 2.2 - r * 1.4 : az + 2.0 + r * 1.4; k.box(.5, .12, .5, qx, y0 + .06, qz, { tone: .33 }); k.line([qx - .25, y0 + .13, qz - .25, qx + .25, y0 + .13, qz + .25]); } for (const [px, pz] of [[x1 + 2.5, z1 + 2.5], [x2 - 2.5, z1 + 2.5], [x1 + 2.5, z2 - 2.5], [x2 - 2.5, z2 - 2.5]]) pole(px, pz, y0, h - .3, PAPER); }
    else if (fill && (x2 - x1) * (z2 - z1) < 90 && (x2 - x1) * (z2 - z1) >= 24) { const alongX = open === 'N' || open === 'S'; if (alongX) furn.rack(x1 + .6, open === 'N' ? z2 - 1.0 : z1 + .4, y0, true, Math.min(2.5, x2 - x1 - 1.2)); else furn.rack(open === 'W' ? x2 - 1.0 : x1 + .4, z1 + .6, y0, false, Math.min(2.5, z2 - z1 - 1.2)); }
    else if (fill && (x2 - x1) * (z2 - z1) >= 90) { const alongX = open === 'N' || open === 'S', first = alongX ? (open === 'N' ? z1 + 2.6 : z1 + 1.0) : (open === 'W' ? x1 + 2.6 : x1 + 1.0); for (let a = first; a + .6 <= (alongX ? z2 : x2) - 1.0; a += 2.6) { const len = Math.min(3, (alongX ? x2 - x1 : z2 - z1) - 2.4); if (fill === 'bales') { if (alongX) furn.bales(x1 + 1.2, a, y0, Math.max(1, Math.floor((x2 - x1 - 2.4) / 2.1))); else { furn.bales(a, z1 + 1.2, y0, 1); if (z2 - z1 > 10) furn.bales(a, z2 - 3.4, y0, 1); } } else if (alongX) { furn.rack(x1 + 1.2, a, y0, true, len); if (x2 - x1 > 10) furn.rack(x2 - 1.2 - len, a, y0, true, len); } else { furn.rack(a, z1 + 1.2, y0, false, len); if (z2 - z1 > 10) furn.rack(a, z2 - 1.2 - len, y0, false, len); } } } doorSteps(x1, z1, x2, z2, y0, open, (open === 'N' || open === 'S' ? (x1 + x2) / 2 : (z1 + z2) / 2) - .7); building({ kind: 'shed', x1, z1, x2, z2, y0, floors: 1, door: { side: open, at: null } }); };
  const crate = (x, z, y0, s = 1, tint = WOOD, loot = true) => { if (loot && R() < .5) spot(x + s / 2 + rr(-1.5, 1.5), z + s + .8, y0); solid(x, z, x + s, z + s, y0, y0 + s, { tint, tone: .33 }); const k = sk(x, z); k.line([x + .1, y0 + s + e, z + .1, x + s - .1, y0 + s + e, z + s - .1, x + .1, y0 + s + e, z + s - .1, x + s - .1, y0 + s + e, z + .1]); };
  const barrel = (x, z, y0, tint = PAPER) => { solid(x - .32, z - .32, x + .32, z + .32, y0, y0 + .9, { vis: false }); const s = sk(x, z); s.cyl(.32, .32, .9, 9, x, y0 + .45, z, { tint, tone: .33, ea: 50 }); s.line([x - .32, y0 + .25, z, x - .3, y0 + .25, z - .12, x - .32, y0 + .65, z, x - .3, y0 + .65, z - .12]); };
  const sandbags = (x1, z1, x2, z2, y0) => { solid(x1, z1, x2, z2, y0, y0 + .85, { tone: .33 }); const s = sk(x1, z1), a = []; for (let y = .28; y < .85; y += .28) { a.push(x1 - .02, y0 + y, z1 - .02, x2 + .02, y0 + y, z1 - .02, x1 - .02, y0 + y, z2 + .02, x2 + .02, y0 + y, z2 + .02, x1 - .02, y0 + y, z1, x1 - .02, y0 + y, z2, x2 + .02, y0 + y, z1, x2 + .02, y0 + y, z2); } for (let x = x1 + .45; x < x2; x += .9) a.push(x, y0 + .02, z1 - .02, x, y0 + .83, z1 - .02); s.line(a); };
  const lamp = (x, z, y0, dx, dz) => { const s = sk(x, z); s.cyl(.06, .09, 4.6, 6, x, y0 + 2.3, z, { ea: 50 }); s.line([x, y0 + 4.6, z, x + dx * .9, y0 + 4.9, z + dz * .9]); s.box(.34, .4, .34, x + dx * .9, y0 + 4.65, z + dz * .9, { tint: AMBER, tone: 0 }); solid(x - .1, z - .1, x + .1, z + .1, y0, y0 + 4.6, { vis: false }); };
  const fence = (x1, z1, x2, z2, y0, gapAt = -1) => { const alongX = Math.abs(x2 - x1) > Math.abs(z2 - z1), len = alongX ? x2 - x1 : z2 - z1, s = sk(x1, z1), a = [];
    for (let t = 0; t <= len; t += 2) { if (gapAt >= 0 && t > gapAt - .1 && t < gapAt + 2.1) continue; const x = alongX ? x1 + t : x1, z = alongX ? z1 : z1 + t, y = tY(x, z); s.box(.12, 1.1, .12, x, y + .55, z, { tint: WOOD, tone: .33 }); }
    for (let t = 0; t < len; t += 2) { if (gapAt >= 0 && t >= gapAt - .1 && t < gapAt + 1.9) continue; const xa = alongX ? x1 + t : x1, za = alongX ? z1 : z1 + t, xb = alongX ? x1 + t + 2 : x1, zb = alongX ? z1 : z1 + t + 2, ya = tY(xa, za), yb = tY(xb, zb); a.push(xa, ya + .5, za, xb, yb + .5, zb, xa, ya + .95, za, xb, yb + .95, zb); if (alongX) solid(xa, za - .08, xb, zb + .08, Math.min(ya, yb), Math.max(ya, yb) + .85, { vis: false }); else solid(xa - .08, za, xb + .08, zb, Math.min(ya, yb), Math.max(ya, yb) + .85, { vis: false }); } s.line(a); };   // .85 m: a running jump clears it
  const wall = (x1, z1, x2, z2, y0, h, o = {}) => { solid(x1, z1, x2, z2, y0, y0 + h, o); sk(x1, z1).bx(x1 - .08, y0 + h, z1 - .08, x2 + .08, y0 + h + .2, z2 + .08, { tone: .33 }); };
  const tower = (x, z, y0) => { for (const [px, pz] of [[x, z], [x + 3.6, z], [x, z + 3.6], [x + 3.6, z + 3.6]]) solid(px, pz, px + .4, pz + .4, y0, y0 + 5, { tone: .66 });
    solid(x - .2, z - .2, x + 4.2, z + 4.2, y0 + 5, y0 + 5.3, { tone: .33 }); for (const [a, b, c, d] of [[x - .2, z - .2, x + 1.2, z], [x + 2.8, z - .2, x + 4.2, z], [x - .2, z + 4, x + 4.2, z + 4.2], [x - .2, z, x, z + 4], [x + 4, z, x + 4.2, z + 4]]) solid(a, b, c, d, y0 + 5.3, y0 + 6.3, { tone: .66 });
    roof(x - .4, z - .4, x + 4.4, z + 4.4, y0 + 8.6, 'gable'); for (const [px, pz] of [[x, z], [x + 3.6, z], [x, z + 3.6], [x + 3.6, z + 3.6]]) solid(px + .05, pz + .05, px + .35, pz + .35, y0 + 6.3, y0 + 8.4, { tone: .66 });
    spot(x + 2, z + 2, y0 + 5.3); stair(x + 1.4, z - 11, y0, y0 + 5.3, '+z'); floor({ x1: x - .2, z1: z - .2, x2: x + 4.2, z2: z + 4.2, y: y0 + 5.3, bottom: { x: x + 2, z: z - 11.6, y: y0 }, top: { x: x + 2, z: z - .6, y: y0 + 5.3 }, exit: { x: x + 2, z: z + 1.2, y: y0 + 5.3 } }); const s = sk(x, z); for (const px of [x + 1.3, x + 2.7]) s.line([px, y0 + .9, z - 11, px, y0 + 6.2, z - .4]); };   // stair handrails
  const pole = (x, z, y0, h, tint = WOOD) => { sk(x, z).cyl(.09, .11, h, 6, x, y0 + h / 2, z, { ea: 50, tint }); solid(x - .12, z - .12, x + .12, z + .12, y0, y0 + h, { vis: false }); };
  const litter = (cx, cz, r, n) => { const s = dt(cx, cz), a = []; for (let i = 0; i < n; i++) { const x = cx + rr(-r, r), z = cz + rr(-r, r), y = tY(x, z) + .01, an = rr(0, 6.28), l = rr(.15, .5); a.push(x, y, z, x + Math.cos(an) * l, y, z + Math.sin(an) * l); } s.line(a); };
  const SG = { bg: '#f5f2ea', border: 5 };
  const nameBoard = (t, x, y, z, ry) => sign(`${t.name} · ${t.en}`, x, y, z, ry, 6.5, .95, SG);

  /* ================= 1 · 军械库 ARMORY: walled compound, two barracks, a bunker, corner towers ================= */
  { const t = TOWNS[0], y = t.pad, cx = t.x, cz = t.z;
    wall(cx - 26, cz - 20, cx + 26, cz - 19, y, 3); wall(cx - 26, cz + 19, cx - 4, cz + 20, y, 3); wall(cx + 4, cz + 19, cx + 26, cz + 20, y, 3); wall(cx - 26, cz - 19, cx - 25, cz + 19, y, 3); wall(cx + 25, cz - 19, cx + 26, cz + 19, y, 3);
    wall(cx - 4, cz + 19, cx - 3, cz + 20, y, 4.2); wall(cx + 3, cz + 19, cx + 4, cz + 20, y, 4.2); solid(cx - 4, cz + 19, cx + 4, cz + 20, y + 3.4, y + 4.2, { tone: .66 }); nameBoard(t, cx, y + 3.8, cz + 20.08, 0);
    tower(cx - 24, cz - 17, y); tower(cx + 20.4, cz + 13, y);
    house(cx - 20, cz - 14, cx - 4, cz - 7, y, { h: 3.2, door: { side: 'S', at: cx - 13 }, roof: 'gable', use: 'barracks' }); house(cx + 4, cz - 14, cx + 20, cz - 7, y, { h: 3.2, door: { side: 'S', at: cx + 11 }, roof: 'gable', use: 'barracks' });
    house(cx - 8, cz + 2, cx + 8, cz + 12, y, { floors: 2, roof: 'flat', door: { side: 'N', at: cx - 1 }, stair: 'E', use: ['store', 'store'], use2: ['office', 'store'] }); sign('军械库 · 弹药室', cx, y + 2.6, cz + 1.92, Math.PI, 5, .8, SG);
    house(cx - 22, cz + 4, cx - 12, cz + 12, y, { h: 3, door: { side: 'E', at: cz + 7 }, roof: 'flat', use: ['office', 'bed'] }); sign('哨所', cx - 11.92, y + 2.5, cz + 10, Math.PI / 2, 2.4, .7, SG);
    sandbags(cx - 3, cz + 15, cx + 3, cz + 16, y); sandbags(cx + 12, cz - 2, cx + 18, cz - 1, y); sandbags(cx + 18, cz - 2, cx + 19, cz + 3, y);
    for (let i = 0; i < 6; i++) crate(cx + 14 + (i % 3) * 1.3, cz + 6 + Math.floor(i / 3) * 1.3, y, 1.2); crate(cx + 15.3, cz + 6, y + 1.2, 1.2); for (let i = 0; i < 4; i++) barrel(cx - 21.5 + i * .8, cz - 3, y, i % 2 ? AMBER : PAPER);
    lamp(cx - 10, cz - 2, y, 1, 0); lamp(cx + 10, cz + 16, y, -1, 0); pole(cx, cz - 3, y, 9); sk(cx, cz).line([cx, y + 9, cz, cx + 1.6, y + 8.6, cz + .2, cx, y + 8.1, cz, cx + 1.6, y + 8.6, cz + .2]); litter(cx, cz, 24, 120);
    const s = sk(cx, cz); for (let x = cx - 24; x < cx + 24; x += 6) s.line([x, y + .02, cz - 5, x + 3, y + .02, cz - 5]); }

  /* ================= 2 · 晒纸场 DRYING YARD: open shed, rows of drying racks, three cottages, a well ================= */
  { const t = TOWNS[1], y = t.pad, cx = t.x, cz = t.z;
    shed(cx - 12, cz - 20, cx + 10, cz - 8, y, 5, 'S'); sign('晒纸场 · 大棚', cx - 1, y + 4.3, cz - 7.92, 0, 5, .8, SG); nameBoard(t, cx, y + 3.2, cz + 26.08, 0);
    for (let row = 0; row < 4; row++) { const rz = cz - 2 + row * 5; for (let x = cx - 14; x <= cx + 14; x += 7) { pole(x, rz, y, 2.6); pole(x, rz + 2.6, y, 2.6); } const s = sk(cx, rz), a = []; a.push(cx - 14, y + 2.5, rz, cx + 14, y + 2.5, rz, cx - 14, y + 2.5, rz + 2.6, cx + 14, y + 2.5, rz + 2.6);
      for (let x = cx - 13; x < cx + 14; x += 1.4) { if (R() < .2) continue; const h = rr(1.4, 2.0); s.bx(x, y + 2.45 - h, rz + 1.2, x + 1.0, y + 2.45, rz + 1.4, { tone: 0 }); a.push(x, y + 2.45, rz + 1.3, x, y + 2.45 - h, rz + 1.3, x + 1, y + 2.45, rz + 1.3, x + 1, y + 2.45 - h, rz + 1.3); solid(x, rz + 1.15, x + 1, rz + 1.45, y + 2.45 - h, y + 2.45, { vis: false }); } s.line(a); }
    house(cx - 26, cz + 2, cx - 18, cz + 9, y, { door: { side: 'E', at: cz + 5 }, roof: 'gable' }); house(cx + 18, cz - 6, cx + 26, cz + 2, y, { door: { side: 'W', at: cz - 3 }, roof: 'gable' }); house(cx + 16, cz + 10, cx + 26, cz + 18, y, { floors: 2, door: { side: 'N', at: cx + 20 }, roof: 'gable', stair: 'E' });
    solid(cx - 20, cz + 18, cx - 17, cz + 21, y, y + 1, { tone: .33 }); sk(cx, cz).cyl(1.5, 1.5, .25, 10, cx - 18.5, y + 1.12, cz + 19.5, { tone: .66 }); pole(cx - 20.2, cz + 19.5, y, 3); pole(cx - 16.8, cz + 19.5, y, 3); sk(cx, cz).line([cx - 20.2, y + 3, cz + 19.5, cx - 16.8, y + 3, cz + 19.5, cx - 18.5, y + 3, cz + 19.5, cx - 18.5, y + 1.3, cz + 19.5]);
    for (let i = 0; i < 5; i++) crate(cx - 10 + i * 1.3, cz - 6, y, 1); barrel(cx + 8, cz - 10, y); barrel(cx + 8.8, cz - 10, y); fence(cx - 28, cz + 24, cx + 28, cz + 24, y, 26); lamp(cx - 14, cz + 20, y, 1, 0); litter(cx, cz, 22, 90); }

  /* ================= 3 · 灯塔渔村 LANTERN COVE: lighthouse tower, huts, pier, boats ================= */
  { const t = TOWNS[2], y = t.pad, cx = t.x, cz = t.z; const L = house(cx + 7, cz - 15, cx + 14, cz - 8, y, { floors: 5, h: 3, roof: 'flat', door: { side: 'W', at: cz - 12 }, win: false, stair: 'E', use: 'store' });
    const s = sk(cx + 10, cz - 12); for (let f = 1; f < 5; f++) s.bx(cx + 9.9, y + f * 3 - 1.4, cz - 15.05, cx + 11.1, y + f * 3 - .6, cz - 14.95, { tint: GLASS, tone: 0 });
    { const g = new THREE.CylinderGeometry(5.3, 6.2, 15, 8, 1, true); g.rotateY(Math.PI / 8); s.add(g, new THREE.Matrix4().makeTranslation(cx + 10.5, y + 7.5, cz - 11.5), { tone: .33, ea: 20 }); const ring = []; for (let i = 0; i <= 8; i++) { const a = i / 8 * 6.2832 + Math.PI / 8; ring.push([cx + 10.5 + Math.cos(a) * 5.7, y + 15.3, cz - 11.5 + Math.sin(a) * 5.7]); } s.poly(ring); s.poly(ring.map(p => [p[0], p[1] + .9, p[2]])); const rl = []; ring.forEach(p => rl.push(p[0], p[1], p[2], p[0], p[1] + .9, p[2])); s.line(rl); const sp = []; for (let i = 0; i < 48; i++) { const t = i / 48, a = t * 6.2832 * 3 + .3, r = 6.2 - t * .9 + .03; sp.push(cx + 10.5 + Math.cos(a) * r, y + .4 + t * 14.4, cz - 11.5 + Math.sin(a) * r, cx + 10.5 + Math.cos(a + .13) * r, y + .4 + (t + 1 / 48) * 14.4, cz - 11.5 + Math.sin(a + .13) * r); } s.line(sp); }
    for (const [px, pz] of [[cx + 7.6, cz - 14.4], [cx + 13.2, cz - 14.4], [cx + 7.6, cz - 8.8], [cx + 13.2, cz - 8.8]]) solid(px, pz, px + .2, pz + .2, y + 15.3, y + 18, { tone: .66 });
    s.bx(cx + 7.7, y + 15.4, cz - 14.3, cx + 13.3, y + 17.8, cz - 8.7, { tint: GLASS, tone: 0 }); s.box(1.1, 1.1, 1.1, cx + 10.5, y + 16.6, cz - 11.5, { tint: AMBER, tone: 0 }); roof(cx + 7.2, cz - 14.8, cx + 13.8, cz - 8.2, y + 18.3, 'gable'); sign('灯 塔', cx + 10.5, y + 10, cz - 15.08, 0, 2.4, .8, SG);
    nameBoard(t, cx - 4, y + 3.2, cz - 16.08, 0);
    for (const [hx, hz, side] of [[cx - 18, cz - 8, 'S'], [cx - 8, cz - 4, 'E'], [cx - 20, cz + 4, 'N'], [cx - 6, cz + 8, 'W'], [cx + 2, cz + 2, 'S']]) house(hx, hz, hx + 6, hz + 5, y, { h: 2.8, door: { side, at: (side === 'N' || side === 'S') ? hx + 2 : hz + 2 }, roof: 'gable', use: 'fishhut' });
    house(cx - 2, cz - 12, cx + 5, cz - 6, y, { h: 3.4, door: { side: 'S', at: cx + 1 }, roof: 'flat', use: 'shop' }); sign('鱼 行', cx + 1.5, y + 2.9, cz - 5.92, 0, 2.4, .7, SG);
    // pier: planks out to sea on posts
    { const px = cx + 14, pz0 = cz + 6, len = 26; for (let z = pz0; z < pz0 + len; z += 2) { const yy = Math.max(tY(px, z), MAP.sea) + .5; solid(px - 1.5, z, px + 1.5, z + 2, yy - .18, yy, { tint: WOOD, tone: .33 }); pole(px - 1.6, z + 1, Math.min(tY(px, z), MAP.sea - 1), yy - Math.min(tY(px, z), MAP.sea - 1) + .9); pole(px + 1.6, z + 1, Math.min(tY(px, z), MAP.sea - 1), yy - Math.min(tY(px, z), MAP.sea - 1) + .9); const k = sk(px, z), a = []; for (let q = z + .4; q < z + 2; q += .4) a.push(px - 1.45, yy + e, q, px + 1.45, yy + e, q); k.line(a); } }
    // boats hauled up on the sand
    for (const [bx, bz, ry] of [[cx - 10, cz + 22, .3], [cx + 4, cz + 26, -.5], [cx + 26, cz + 14, 1.2]]) { const yb = Math.max(tY(bx, bz), MAP.sea) + .25, M = new THREE.Matrix4().makeRotationY(ry).setPosition(bx, yb, bz), k = sk(bx, bz); k.prof([[-2.6, 0], [-2.3, -.35], [2.2, -.35], [2.8, .4], [2.4, .55], [-2.2, .55], [-2.6, .3]], 1.4, { m: M, tint: WOOD, tone: .33 }); k.box(.3, .9, .2, 0, .8, 0, { m: M, tone: .66 }); k.line([-1.5, .56, -.7, -1.5, .56, .7, .6, .56, -.7, .6, .56, .7], M); solid(bx - 1.6, bz - 1.6, bx + 1.6, bz + 1.6, yb - .5, yb + .6, { vis: false }); }
    for (let i = 0; i < 4; i++) crate(cx - 2 + i * 1.2, cz - 15, y, 1); barrel(cx + 6, cz - 15, y); fence(cx - 22, cz + 12, cx + 2, cz + 12, y, 10); lamp(cx - 12, cz, y, 0, 1); pole(cx + 16, cz + 2, y, 6); litter(cx, cz, 20, 70); }

  /* ================= 4 · 墨池农庄 INK POND FARM: farmhouse, barn, silo, fields, the ink pond ================= */
  { const t = TOWNS[3], y = t.pad, cx = t.x, cz = t.z;
    house(cx - 8, cz - 20, cx + 6, cz - 10, y, { floors: 2, roof: 'gable', door: { side: 'S', at: cx - 2 }, stair: 'W' }); nameBoard(t, cx - 1, y + 6.4, cz - 9.92, 0);
    shed(cx + 10, cz - 22, cx + 26, cz - 10, y, 6, 'W', 'bales'); sign('谷仓', cx + 18, y + 5.2, cz - 9.92, 0, 2.6, .8, SG);
    for (const [hw, hd] of [[2.5, 1.0], [2.15, 1.75], [1.3, 2.4]]) solid(cx + 30.5 - hw, cz - 17.5 - hd, cx + 30.5 + hw, cz - 17.5 + hd, y, y + 9, { vis: false }); { const k = sk(cx + 30, cz - 17); k.cyl(2.5, 2.5, 9, 12, cx + 30.5, y + 4.5, cz - 17.5, { tone: .33, ea: 40 }); k.cone(2.7, 1.6, 12, cx + 30.5, y + 9.8, cz - 17.5, { tone: .66, ea: 40 }); const a = []; for (let yy = 1.5; yy < 9; yy += 1.5) for (let i = 0; i < 12; i++) { const a0 = i / 12 * 6.2832, a1 = (i + 1) / 12 * 6.2832; a.push(cx + 30.5 + Math.cos(a0) * 2.52, y + yy, cz - 17.5 + Math.sin(a0) * 2.52, cx + 30.5 + Math.cos(a1) * 2.52, y + yy, cz - 17.5 + Math.sin(a1) * 2.52); } k.line(a); }
    // fields: furrow rows with low stone walls
    for (const [fx, fz, fw, fd, ax] of [[cx - 30, cz - 2, 22, 16, true], [cx - 4, cz - 2, 20, 16, false], [cx - 30, cz + 18, 48, 12, true]]) { const k = dt(fx, fz), a = []; for (let i = 1; i < (ax ? fd : fw); i += 1.2) { if (ax) a.push(fx + .5, tY(fx + .5, fz + i) + .03, fz + i, fx + fw - .5, tY(fx + fw - .5, fz + i) + .03, fz + i); else a.push(fx + i, tY(fx + i, fz + .5) + .03, fz + .5, fx + i, tY(fx + i, fz + fd - .5) + .03, fz + fd - .5); } k.line(a); sk(fx, fz).quad([fx, y + .02, fz], [fx, y + .02, fz + fd], [fx + fw, y + .02, fz + fd], [fx + fw, y + .02, fz], -.05, PAPER); fence(fx, fz, fx + fw, fz, y, fw / 2); fence(fx, fz + fd, fx + fw, fz + fd, y); fence(fx, fz, fx, fz + fd, y); fence(fx + fw, fz, fx + fw, fz + fd, y); }
    // scarecrow
    { const k = sk(cx - 20, cz + 6); pole(cx - 20, cz + 6, y, 2.4); k.line([cx - 21, y + 1.8, cz + 6, cx - 19, y + 1.8, cz + 6]); k.box(.7, .9, .4, cx - 20, y + 1.6, cz + 6, { tone: .33 }); k.sph(.25, cx - 20, y + 2.3, cz + 6, { tint: WOOD, tone: 0 }); k.cone(.45, .25, 6, cx - 20, y + 2.55, cz + 6, { tone: .66 }); }
    // the ink pond: a dark wash sunk into the pad, reeds around it
    { const k = sk(cx + 14, cz + 8), pts = []; for (let i = 0; i < 16; i++) { const a = i / 16 * 6.2832, r = 7 + Math.sin(i * 1.9) * 1.4; pts.push([cx + 14 + Math.cos(a) * r, y + .015, cz + 8 + Math.sin(a) * r * .7]); } for (let i = 0; i < 16; i++) k.tri([cx + 14, y + .015, cz + 8], pts[i], pts[(i + 1) % 16], 1); k.poly(pts, true); const a = []; for (let i = 0; i < 40; i++) { const an = rr(0, 6.28), r = rr(7, 9); const x = cx + 14 + Math.cos(an) * r, z = cz + 8 + Math.sin(an) * r * .7; a.push(x, y, z, x + rr(-.2, .2), y + rr(.6, 1.2), z); } k.line(a); sign('墨 池', cx + 14, y + .03, cz + 16, 0, 3, 1, { ...SG, flat: true }); }
    for (let i = 0; i < 3; i++) crate(cx + 7.2, cz - 20 + i * 1.4, y, 1.2); for (let i = 0; i < 3; i++) barrel(cx + 24 - i * .8, cz - 11, y, AMBER); lamp(cx + 8, cz - 8, y, -1, 0); litter(cx, cz, 26, 60); }

  /* ================= 5 · 山顶观测站 HILLTOP POST: dome, mast, bunker ================= */
  { const t = TOWNS[4], y = t.pad, cx = t.x, cz = t.z;
    house(cx - 5, cz - 5, cx + 5, cz + 5, y, { h: 4, roof: 'flat', door: { side: 'S', at: cx - 1 }, win: false, props: false, ladder: false }); const k = sk(cx, cz); k.add(new THREE.SphereGeometry(4.6, 14, 9, 0, 6.2832, 0, Math.PI / 2), new THREE.Matrix4().makeTranslation(cx, y + 4, cz), { tone: .33, ws: 14, hs: 9, ea: 20 }); solid(cx - 4, cz - 4, cx + 4, cz + 4, y + 4, y + 8.5, { vis: false }); k.line([cx - 4.6, y + 4.6, cz, cx + 4.6, y + 4.6, cz, cx, y + 4.6, cz - 4.6, cx, y + 4.6, cz + 4.6, cx - 1, y + 4.4, cz - 4.5, cx - 1, y + 8.9, cz - .2, cx + 1, y + 4.4, cz - 4.5, cx + 1, y + 8.9, cz - .2]);
    sign('观 测 站', cx, y + 3, cz + 5.08, 0, 3.2, .8, SG); nameBoard(t, cx, y + 2.6, cz + 14.08, 0);
    pole(cx + 10, cz - 8, y, 14, PAPER); k.line([cx + 10, y + 14, cz - 8, cx + 13, y, cz - 11, cx + 10, y + 14, cz - 8, cx + 7, y, cz - 11, cx + 10, y + 14, cz - 8, cx + 10, y, cz - 4, cx + 9.4, y + 11, cz - 8, cx + 10.6, y + 11, cz - 8, cx + 10, y + 11, cz - 8.6, cx + 10, y + 11, cz - 7.4]); k.box(.5, .5, .5, cx + 10, y + 14.3, cz - 8, { tint: RED, tone: 0 });
    house(cx - 14, cz + 2, cx - 6, cz + 8, y, { h: 2.6, roof: 'flat', door: { side: 'E', at: cz + 4 }, win: false, use: ['office', 'bed'] }); const b = sk(cx - 10, cz + 5); for (const z of [cz + 3, cz + 6]) b.bx(cx - 14.05, y + 1.5, z, cx - 13.95, y + 1.8, z + 1.2, { tint: GLASS, tone: 0 }); sign('掩 体', cx - 10, y + 2.3, cz + 8.08, 0, 2, .6, SG);
    sandbags(cx + 2, cz + 9, cx + 8, cz + 10, y); sandbags(cx + 8, cz + 6, cx + 9, cz + 10, y); for (let i = 0; i < 3; i++) crate(cx - 4 + i * 1.3, cz - 9, y, 1.1); barrel(cx + 6, cz - 2, y); barrel(cx + 6.8, cz - 2.2, y, AMBER); lamp(cx - 8, cz - 6, y, 1, 0); litter(cx, cz, 14, 40); }

  /* ================= 6 · 废弃印厂 OLD PRINT WORKS: great hall with skylights, mezzanine, bales, chimney, office ================= */
  { const t = TOWNS[5], y = t.pad, cx = t.x, cz = t.z, x1 = cx - 16, z1 = cz - 12, x2 = cx + 14, z2 = cz + 6, h = 8;
    face('x', x1, x2, z1 + T / 2, y, h, [{ a: cx - 2, w: 4, y: 0, h: 4.2, leaf: false }, { a: x1 + 3, w: 2, y: 5, h: 1.6, glass: true }, { a: x2 - 5, w: 2, y: 5, h: 1.6, glass: true }]); face('x', x1, x2, z2 - T / 2, y, h, [{ a: x1 + 4, w: 1.6, y: 0, h: 2.3, in: true }, { a: cx + 4, w: 4, y: 0, h: 4.2, leaf: false }]);
    face('z', z1 + T, z2 - T, x1 + T / 2, y, h, [{ a: cz - 4, w: 2, y: 5, h: 1.6, glass: true }, { a: cz, w: 2, y: 5, h: 1.6, glass: true }]); face('z', z1 + T, z2 - T, x2 - T / 2, y, h, [{ a: cz - 6, w: 1.6, y: 0, h: 2.3, in: true }]);
    solid(x1 - .2, z1 - .2, x2 + .2, z2 + .2, y + h, y + h + .3, { tone: .33 }); { const k = sk(cx, cz), a = []; for (let x = x1 + 2; x < x2; x += 4) { k.bx(x - .15, y + h - .5, z1, x + .15, y + h, z2, { tint: WOOD, tone: .66 }); k.bx(x + 1, y + h + .3, z1 + 1, x + 3, y + h + .34, z2 - 1, { tint: GLASS, tone: 0 }); a.push(x + 1, y + h + .36, z1 + 1, x + 3, y + h + .36, z2 - 1, x + 3, y + h + .36, z1 + 1, x + 1, y + h + .36, z2 - 1); } for (const z of [z1 + 6, z2 - 6]) k.bx(x1, y + h - .9, z - .2, x2, y + h - .5, z + .2, { tone: .66 }); k.line(a); }
    sign('印 厂', cx, y + 6.5, z1 - .08, 0, 4, 1.1, SG); nameBoard(t, cx + 8, y + 3, z2 + .08, 0);
    // mezzanine along the west wall with a stair and rail
    slab(x1 + T, z1 + T, x1 + 7, z2 - T, y + 4, [x1 + 5.8, z2 - T - 8.3, x1 + 7, z2 - T]); stair(x1 + 5.8, z2 - T - 8, y, y + 4, '+z'); floor({ x1: x1 + T, z1: z1 + T, x2: x1 + 5.8, z2: z2 - T, y: y + 4, bottom: { x: x1 + 6.4, z: z2 - T - 8.7, y }, top: { x: x1 + 6.4, z: z2 - T - .45, y: y + 4 }, exit: { x: x1 + 5.1, z: z2 - T - .6, y: y + 4 } }); solid(x1 + 7, z1 + T, x1 + 7.05, z2 - T - 8, y + 4, y + 5, { tone: .66 });
    for (let i = 0; i < 10; i++) spot(rr(x1 + 2, x2 - 2), rr(z1 + 2, z2 - 2), y); for (let i = 0; i < 3; i++) spot(rr(x1 + 1, x1 + 6), rr(z1 + 1, z2 - 9), y + 4);
    // presses: heavy blocks with rollers; paper bales; a crane gantry
    for (const [px, pz] of [[cx - 4, cz - 6], [cx + 3, cz - 6], [cx - 4, cz], [cx + 3, cz]]) { solid(px, pz, px + 3, pz + 2, y, y + 1.6, { tone: .33 }); const k = sk(px, pz); k.cyl(.45, .45, 2.2, 10, px + 1.5, y + 2.0, pz + 1, { ax: 'x', tone: .66 }); k.box(.3, .6, .3, px + .4, y + 1.9, pz + 1.7, { tone: 0 }); k.line([px + .2, y + 1.6 + e, pz + .2, px + 2.8, y + 1.6 + e, pz + 1.8]); }
    for (let i = 0; i < 8; i++) { const bx = x2 - 6 + (i % 2) * 2.2, bz = z1 + 2 + Math.floor(i / 2) * 2.3; crate(bx, bz, y, 2, PAPER, false); if (i % 2 === 0) spot(bx - 1.3, bz + 1, y); if (i % 3 === 0) crate(bx, bz, y + 2, 2, PAPER, false); const k = sk(bx, bz), a = []; for (let yy = .4; yy < 2; yy += .4) a.push(bx - .01, y + yy, bz - .01, bx - .01, y + yy, bz + 2.01, bx - .01, y + yy, bz - .01, bx + 2.01, y + yy, bz - .01); k.line(a); }
    { const k = sk(cx, cz); for (const x of [x1 + 9, x2 - 3]) k.bx(x - .25, y, z1 + 1, x + .25, y + 6.5, z1 + 1.5, { tint: AMBER, tone: .33 }); k.bx(x1 + 9, y + 6.5, z1 + .9, x2 - 3, y + 7, z1 + 1.6, { tint: AMBER, tone: .33 }); k.box(1, .8, 1, cx, y + 6.1, z1 + 1.25, { tone: .66 }); k.line([cx, y + 5.7, z1 + 1.25, cx, y + 3.2, z1 + 1.25]); k.box(1.2, .3, .4, cx, y + 3.05, z1 + 1.25, { tone: .33 }); for (const x of [x1 + 9, x2 - 3]) solid(x - .25, z1 + 1, x + .25, z1 + 1.5, y, y + 6.5, { vis: false }); }
    // chimney and the office block
    solid(x2 + 2, z1 - 2, x2 + 5, z1 + 1, y, y + 16, { tone: .33 }); { const k = sk(x2 + 3, z1), a = []; for (let yy = 2; yy < 16; yy += 2) a.push(x2 + 1.98, y + yy, z1 - 2.02, x2 + 1.98, y + yy, z1 + 1.02, x2 + 1.98, y + yy, z1 - 2.02, x2 + 5.02, y + yy, z1 - 2.02); k.line(a); k.bx(x2 + 1.7, y + 16, z1 - 2.3, x2 + 5.3, y + 16.6, z1 + 1.3, { tone: .66 }); }
    house(cx - 16, cz + 10, cx - 6, cz + 18, y, { floors: 2, roof: 'flat', door: { side: 'N', at: cx - 12 }, stair: 'E', use: ['office', 'office'], use2: ['office', 'store'] }); sign('办公楼', cx - 11, y + 5.2, cz + 9.92, Math.PI, 2.8, .7, SG);
    house(cx + 4, cz + 10, cx + 12, cz + 16, y, { h: 3, roof: 'gable', door: { side: 'W', at: cz + 12 } });
    for (let i = 0; i < 6; i++) barrel(cx + 16 + (i % 3) * .8, cz + 8 + Math.floor(i / 3) * .8, y, i % 2 ? PAPER : AMBER); sandbags(cx - 2, cz + 9, cx + 2, cz + 10, y); lamp(cx - 18, cz - 14, y, 1, 0); lamp(cx + 16, cz + 2, y, -1, 0); fence(cx - 18, cz + 20, cx + 14, cz + 20, y, 14); litter(cx, cz, 26, 110); }
  const plinth = (x1, z1, x2, z2, y0) => { let lo = y0; for (let i = 0; i <= 8; i++) for (let j = 0; j <= 8; j++) lo = Math.min(lo, tY(x1 + (x2 - x1) * i / 8, z1 + (z2 - z1) * j / 8)); if (y0 - lo > .1) solid(x1 - .1, z1 - .1, x2 + .1, z2 + .1, lo - 1.5, y0, { tone: .33 }); };
  const padOf = (x1, z1, x2, z2) => { let hi = -99; for (let i = 0; i <= 4; i++) for (let j = 0; j <= 4; j++) hi = Math.max(hi, tY(x1 + (x2 - x1) * i / 4, z1 + (z2 - z1) * j / 4)); return Math.round(hi * 4) / 4 + .05; };

  /* ================= 7 · 码头货栈 WHARF: warehouse, long pier, crane, fuel tank, office ================= */
  { const t = TOWNS[6], y = t.pad, cx = t.x, cz = t.z;
    shed(cx - 4, cz - 6, cx + 18, cz + 8, y, 6, 'W'); sign('货 栈', cx + 7, y + 5.2, cz - 6.08, 0, 2.8, .8, SG); nameBoard(t, cx, y + 3.2, cz + 16.08, 0);
    house(cx + 2, cz + 12, cx + 12, cz + 20, y, { floors: 2, roof: 'flat', door: { side: 'N', at: cx + 6 }, stair: 'E', use: ['office', 'store'], use2: ['office', 'bed'] }); sign('港务所', cx + 7, y + 5.4, cz + 11.92, Math.PI, 2.8, .7, SG);
    for (const [hw, hd] of [[4, 1.6], [3.5, 2.9], [2.1, 3.9]]) solid(cx - 12 - hw, cz + 14 - hd, cx - 12 + hw, cz + 14 + hd, y, y + 5, { vis: false }); { const k = sk(cx - 12, cz + 14); k.cyl(4, 4, 5, 14, cx - 12, y + 2.5, cz + 14, { tone: .33, ea: 40 }); k.cyl(4.1, 4.1, .3, 14, cx - 12, y + 5.1, cz + 14, { tone: .66, ea: 40 }); const a = []; for (let yy = 1; yy < 5; yy += 1.3) for (let i = 0; i < 14; i++) { const a0 = i / 14 * 6.2832, a1 = (i + 1) / 14 * 6.2832; a.push(cx - 12 + Math.cos(a0) * 4.02, y + yy, cz + 14 + Math.sin(a0) * 4.02, cx - 12 + Math.cos(a1) * 4.02, y + yy, cz + 14 + Math.sin(a1) * 4.02); } k.line(a); k.line([cx - 8, y + 5.1, cz + 14, cx - 8, y, cz + 14, cx - 8.4, y + 4, cz + 14.4, cx - 7.6, y + 4, cz + 13.6]); }
    { const px0 = cx - 20, pz = cz - 2, len = 44; for (let x = px0; x > px0 - len; x -= 2) { const yy = Math.max(tY(x, pz), MAP.sea) + .6; solid(x - 2, pz - 2, x, pz + 2, yy - .2, yy, { tint: WOOD, tone: .33 }); for (const q of [pz - 2.1, pz + 2.1]) pole(x - 1, q, Math.min(tY(x, pz), MAP.sea - 1), yy - Math.min(tY(x, pz), MAP.sea - 1) + 1); const k = sk(x, pz), a = []; for (let u = x - .4; u > x - 2; u -= .4) a.push(u, yy + e, pz - 1.9, u, yy + e, pz + 1.9); k.line(a); if (((x - px0) / 2) % 6 === 3) { lamp(x - 1, pz + 2.6, yy, 0, -1); } } }
    for (const [bx, bz, ry] of [[cx - 40, cz - 8, 1.4], [cx - 48, cz + 4, 1.1]]) { const yb = MAP.sea + .25, M = new THREE.Matrix4().makeRotationY(ry).setPosition(bx, yb, bz), k = sk(bx, bz); k.prof([[-3.4, 0], [-3, -.4], [2.8, -.4], [3.6, .5], [3, .7], [-2.8, .7], [-3.4, .4]], 2, { m: M, tint: WOOD, tone: .33 }); k.box(1.4, 1.2, 1.2, -.6, 1.3, 0, { m: M, tone: .33 }); k.line([-1.6, .72, -.9, -1.6, .72, .9, 1.2, .72, -.9, 1.2, .72, .9], M); solid(bx - 2, bz - 2, bx + 2, bz + 2, yb - .5, yb + .8, { vis: false }); }
    { const k = sk(cx, cz); for (const x of [cx - 2, cx + 14]) { k.bx(x - .3, y, cz - 11, x + .3, y + 9, cz - 10.4, { tint: AMBER, tone: .33 }); solid(x - .3, cz - 11, x + .3, cz - 10.4, y, y + 9, { vis: false }); } k.bx(cx - 2.6, y + 9, cz - 11.2, cx + 14.6, y + 9.6, cz - 10.2, { tint: AMBER, tone: .33 }); k.box(1.2, 1, 1.2, cx + 6, y + 8.4, cz - 10.7, { tone: .66 }); k.line([cx + 6, y + 7.9, cz - 10.7, cx + 6, y + 2.6, cz - 10.7]); crate(cx + 5, cz - 12, y, 2, PAPER); }
    for (let i = 0; i < 9; i++) { const bx = cx + 20 + (i % 3) * 2.3, bz = cz - 10 + Math.floor(i / 3) * 2.3; crate(bx, bz, y, 2, i % 2 ? WOOD : PAPER, false); if (i % 3 === 0) spot(bx - 1.3, bz + 1, y); if (i % 4 === 0) crate(bx, bz, y + 2, 2, PAPER, false); }
    for (let i = 0; i < 5; i++) barrel(cx - 6 + i * .8, cz - 12, y, i % 2 ? AMBER : PAPER); fence(cx - 18, cz + 22, cx + 16, cz + 22, y, 16); lamp(cx + 16, cz + 10, y, -1, 0); litter(cx, cz, 24, 90); }

  /* ================= 8 · 断桥村 BROKEN BRIDGE: houses on both banks, a bridge with its middle gone ================= */
  { const t = TOWNS[7], y = t.pad, cx = t.x, cz = t.z, rx = -30;   // the river runs near x = -30 here
    for (const [hx, hz, side, fl] of [[cx + 6, cz - 20, 'W', 1], [cx + 12, cz - 8, 'W', 2], [cx + 8, cz + 6, 'N', 1], [cx + 16, cz + 14, 'W', 1], [cx - 44, cz - 14, 'E', 1], [cx - 42, cz + 4, 'E', 2], [cx - 36, cz + 16, 'N', 1]]) { const w = 7 + (fl - 1) * 2, d = 6 + (fl - 1); const y0 = padOf(hx, hz, hx + w, hz + d); plinth(hx, hz, hx + w, hz + d, y0); house(hx, hz, hx + w, hz + d, y0, { floors: fl, h: 3, roof: 'gable', door: { side, at: side === 'N' || side === 'S' ? hx + 2 : hz + 2 } }); }
    shed(cx + 4, cz + 20, cx + 18, cz + 30, padOf(cx + 4, cz + 20, cx + 18, cz + 30), 4.5, 'N', 'shrine'); sign('祠 堂', cx + 11, padOf(cx + 4, cz + 20, cx + 18, cz + 30) + 3.6, cz + 19.92, Math.PI, 2.6, .8, SG); nameBoard(t, cx + 2, y + 3, cz - 24.08, 0);
    // bridge decks from each bank, the span between them fallen into the river
    { const by = y + .4; for (const [a, b] of [[rx - 18, rx - 6], [rx + 6, rx + 18]]) { solid(a, cz - 3, b, cz + 3, by - .4, by, { tone: .33 }); solid(a, cz - 3.4, b, cz - 3, by, by + 1, { tone: .66 }); solid(a, cz + 3, b, cz + 3.4, by, by + 1, { tone: .66 }); const k = sk((a + b) / 2, cz), q = []; for (let x = a + 1; x < b; x += 1) q.push(x, by + e, cz - 2.9, x, by + e, cz + 2.9); k.line(q); for (const px of [a + 1, b - 1]) pole(px, cz - 3.2, by - 4, 5.2); for (const px of [a + 1, b - 1]) pole(px, cz + 3.2, by - 4, 5.2); }
      const k = sk(rx, cz); k.box(5, .4, 5.5, rx - 1, -1.2, cz + 1, { tone: .33, r: [.3, .2, .5] }); k.box(4, .4, 5.5, rx + 3, -1.6, cz - 1, { tone: .33, r: [-.4, .1, -.3] }); k.line([rx - 6, by + .2, cz - 2.8, rx - 3.5, by - 1.5, cz - 2.2, rx + 6, by + .2, cz + 2.8, rx + 3.2, by - 1.2, cz + 2.1]); sign('桥 断', rx - 12, by + 1.6, cz - 3.48, 0, 2.2, .6, SG); }
    solid(cx - 2, cz + 10, cx + 1, cz + 13, y, y + 1, { tone: .33 }); sk(cx, cz).cyl(1.5, 1.5, .25, 10, cx - .5, y + 1.12, cz + 11.5, { tone: .66 }); fence(cx - 46, cz - 24, cx - 32, cz - 24, y); fence(cx + 2, cz - 26, cx + 22, cz - 26, y, 8); for (let i = 0; i < 4; i++) crate(cx + 20 + i * 1.3, cz - 2, y, 1); barrel(cx - 40, cz + 10, y); lamp(cx + 4, cz, y, 1, 0); lamp(cx - 38, cz - 6, y, 1, 0); litter(cx, cz, 26, 80); }

  /* ================= 9 · 石矿场 QUARRY: stepped stone benches, crusher, conveyor, rail carts ================= */
  { const t = TOWNS[8], y = t.pad, cx = t.x, cz = t.z;
    for (let i = 0; i < 3; i++) { const w = 26 - i * 6, d = 18 - i * 4, h = y + (i + 1) * 1.5; solid(cx - w, cz - d, cx + w, cz + d, h - 1.5, h, { tone: .33, terrace: true }); const k = dt(cx, cz), a = []; for (let x = cx - w; x < cx + w; x += 1.7) a.push(x, h + e, cz - d + .2, x + .9, h + e, cz - d + 2.3, x, h + e, cz + d - 2.3, x + .9, h + e, cz + d - .2); k.line(a); stair(cx - w - 3, cz - 1.2, h - 1.5, h, '+x', 2.4); }
    floor({ x1: cx - 14, z1: cz - 10, x2: cx + 14, z2: cz + 10, y: y + 4.5, bottom: { x: cx - 30, z: cz, y }, top: { x: cx - 13.4, z: cz, y: y + 4.5 }, exit: { x: cx - 11, z: cz, y: y + 4.5 } });
    shed(cx - 6, cz - 6, cx + 8, cz + 4, y + 4.5, 5, 'S'); sign('破 碎 车 间', cx + 1, y + 8.6, cz + 4.08, 0, 4, .9, SG); nameBoard(t, cx, y + 3, cz - 26.08, 0);
    { const k = sk(cx, cz); k.box(3, 3, 2.6, cx + 1, y + 6, cz - 2, { tone: .33 }); k.cone(1.9, 1.6, 8, cx + 1, y + 8.3, cz - 2, { tone: .66, r: [Math.PI, 0, 0] }); for (let i = 0; i < 10; i++) { const u = i / 9, x0 = cx + 10 + u * 22, h0 = y + 4.5 + .4 - u * 4; k.box(.3, .3, 2.2, x0, h0 - .3, cz, { tone: .66 }); if (i < 9) k.line([x0, h0, cz - 1.1, x0 + 22 / 9, h0 - 4 / 9, cz - 1.1, x0, h0, cz + 1.1, x0 + 22 / 9, h0 - 4 / 9, cz + 1.1]); if (i % 3 === 0) { pole(x0, cz - 1.3, y, h0 - y - .3); pole(x0, cz + 1.3, y, h0 - y - .3); } } }
    for (const [sx, sz] of [[cx + 31, cz - 10], [cx + 31, cz + 10]]) { for (let i = 0; i < 6; i++) rock(sx + rr(-3, 3), sz + rr(-2.5, 2.5), rr(.6, 1.8)); }
    house(cx - 30, cz + 22, cx - 20, cz + 30, y, { h: 3, roof: 'flat', door: { side: 'N', at: cx - 26 }, use: ['office', 'store'] }); sign('矿 务 室', cx - 25, y + 2.6, cz + 21.92, Math.PI, 2.8, .7, SG);
    for (let i = 0; i < 3; i++) { const bx = cx + 12 + i * 3.2, bz = cz + 20; solid(bx, bz, bx + 2.2, bz + 1.4, y, y + 1.1, { tone: .33 }); const k = sk(bx, bz); k.cyl(.3, .3, .2, 8, bx + .5, y + .3, bz - .1, { ax: 'z', tone: .66 }); k.cyl(.3, .3, .2, 8, bx + 1.7, y + .3, bz - .1, { ax: 'z', tone: .66 }); k.line([bx + .1, y + 1.1 + e, bz + .1, bx + 2.1, y + 1.1 + e, bz + 1.3]); } { const k = sk(cx, cz), a = []; for (let x = cx + 10; x < cx + 24; x += .5) a.push(x, y + .02, cz + 20.2, x, y + .02, cz + 21.2); a.push(cx + 10, y + .03, cz + 20.2, cx + 24, y + .03, cz + 20.2, cx + 10, y + .03, cz + 21.2, cx + 24, y + .03, cz + 21.2); k.line(a); }
    for (let i = 0; i < 4; i++) barrel(cx - 30 + i * .8, cz - 14, y, i % 2 ? AMBER : PAPER); crate(cx - 30, cz - 11, y, 1.2); lamp(cx - 28, cz - 10, y, 1, 0); fence(cx - 32, cz + 33, cx + 32, cz + 33, y, 30); litter(cx, cz, 28, 100); }

  /* ================= street cover: an L of sandbags plus a crate stack 6–8 m out from a building's door, parallel to its wall; at most four per town, never on a road ================= */
  for (const t of TOWNS) { const y = t.pad, bs = MAP.buildings.filter(b => Math.hypot((b.x1 + b.x2) / 2 - t.x, (b.z1 + b.z2) / 2 - t.z) < t.r + 10 && b.door.at !== null); let placed = 0; for (let k = 0; k < 40 && placed < 4 && bs.length; k++) { const b = bs[(R() * bs.length) | 0], d = b.door, out = 6 + R() * 2, ax = d.side === 'N' || d.side === 'S' ? d.at + .7 : d.side === 'W' ? b.x1 - out : b.x2 + out, az = d.side === 'W' || d.side === 'E' ? d.at + .7 : d.side === 'N' ? b.z1 - out : b.z2 + out, along = d.side === 'N' || d.side === 'S';
      const x = Math.round(ax - (along ? 2 : .5)), z = Math.round(az - (along ? .5 : 2)), w = along ? 4 : 1, dd = along ? 1 : 4; if (Math.abs(tY(x + w / 2, z + dd / 2) - y) > .6 || MAP.roadDist(x + w / 2, z + dd / 2) < 4) continue; if (MAP.buildings.some(q => x < q.x2 + 2.5 && x + w > q.x1 - 2.5 && z < q.z2 + 2.5 && z + dd > q.z1 - 2.5)) continue; if (MAP.solids.some(q => !q.veg && q.y2 > y + .2 && x < q.x2 + 1.2 && x + w > q.x1 - 1.2 && z < q.z2 + 1.2 && z + dd > q.z1 - 1.2)) continue;
      sandbags(x, z, x + w, z + dd, y); if (along) sandbags(x + (R() < .5 ? -1 : 4), z, x + (R() < .5 ? 0 : 5), z + 3, y); else sandbags(x, z + (R() < .5 ? -1 : 4), x + 3, z + (R() < .5 ? 0 : 5), y); const cxx = x + (along ? 1 : 1.6), czz = z + (along ? 1.6 : 1); crate(cxx, czz, y, 1, WOOD, false); crate(cxx + .5, czz + .05, y + 1, .8, WOOD, false); placed++; } }
  /* ================= wild houses: lone farmhouses and sheds scattered over the open land ================= */
  { let n = 0; const placed = []; for (let k = 0; k < 4000 && n < 44; k++) { const E = MAP.size / 2 - 30, x = Math.round(rr(-E, E)), z = Math.round(rr(-E, E)), h = tY(x, z); if (h < 2.2 || h > 26) continue; if (placed.some(p => x < p[2] + 6 && x + 10 > p[0] - 6 && z < p[3] + 6 && z + 8 > p[1] - 6)) continue; let bad = false; for (const t of TOWNS) if (Math.hypot(x - t.x, z - t.z) < t.r + 26) bad = true; if (bad || MAP.roadDist(x, z) < 7 || polyDist(x, z, RIVER) < 14) continue; if (Math.abs(tY(x + 6, z) - tY(x - 6, z)) + Math.abs(tY(x, z + 6) - tY(x, z - 6)) > 1.6) continue;
      const kind = R(), w = kind < .35 ? 6 : kind < .8 ? 8 : 10, d = kind < .35 ? 5 : kind < .8 ? 7 : 8, y0 = padOf(x, z, x + w, z + d); if (MAP.solids.some(s => s.veg && s.x2 > x - 1 && s.x1 < x + w + 1 && s.z2 > z - 1 && s.z1 < z + d + 1)) continue; placed.push([x, z, x + w, z + d]); { let lo = 99, hi = -99; for (let i = 0; i <= 8; i++) for (let j = 0; j <= 8; j++) { const q = tY(x + w * i / 8, z + d * j / 8); lo = Math.min(lo, q); hi = Math.max(hi, q); } if (hi - lo > 1.0 || y0 - lo > 1.3) continue; } plinth(x, z, x + w, z + d, y0);
      const drop = sd => y0 - Math.min(...[1, 2.5].map(q => tY(sd === 'W' ? x - q : sd === 'E' ? x + w + q : x + w / 2, sd === 'N' ? z - q : sd === 'S' ? z + d + q : z + d / 2))), sides = ['N', 'S', 'E', 'W'].sort((a, b) => drop(a) - drop(b)), side = drop(sides[0]) > 1.6 ? null : (drop(sides[1]) <= 1.0 && R() < .5 ? sides[1] : sides[0]); if (!side) continue; const at = (side === 'N' || side === 'S' ? x + Math.floor(w / 2) - 1 : z + Math.floor(d / 2) - 1); if (kind < .2) shed(x, z, x + w, z + d, y0, 3.6, side); else house(x, z, x + w, z + d, y0, { floors: kind > .8 ? 2 : 1, h: 3, roof: R() < .6 ? 'gable' : 'flat', door: { side, at } });
      if (R() < .5) fence(x - 3, z - 3, x + w + 3, z - 3, y0, side === 'N' ? at - (x - 3) - .3 : 3); if (R() < .3) { const ex = side === 'E' ? x - 2.5 : x + w + 1; crate(ex, z + 1, y0, 1); barrel(ex + .5, z + 3, y0); } if (R() < .4) pole(x - 2, z + d + 2, y0, 7); n++; } }
}
